set shell := ["bash", "-cu"]

# Generate all
gen:
    just gen-sqlc

gen-sqlc:
    sqlc generate

test:
    @echo "no tests for identityx"

#testf:
#    mkdir -p generated/coverage
#    gotestsum --format testdox --format-icons nerdfonts \
#        -- -coverprofile=generated/coverage/coverage.out ./...
#    ~/go/bin/gcov2lcov -infile=generated/coverage/coverage.out -outfile=generated/coverage/coverage.lcov -use-absolute-source-path
#    genhtml generated/coverage/coverage.lcov -o generated/coverage/html