/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthSetupRouteImport } from './routes/auth/setup'
import { Route as AdminOrganizationIDRouteImport } from './routes/admin/$organizationID'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminOrganizationIDIndexRouteImport } from './routes/admin/$organizationID/index'
import { Route as AdminProjectsProjectIDRouteImport } from './routes/admin/projects/$projectID'
import { Route as AdminOrganizationIDMembersRouteImport } from './routes/admin/$organizationID/members'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/auth/setup',
  path: '/auth/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationIDRoute = AdminOrganizationIDRouteImport.update({
  id: '/$organizationID',
  path: '/$organizationID',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationIDIndexRoute =
  AdminOrganizationIDIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminOrganizationIDRoute,
  } as any)
const AdminProjectsProjectIDRoute = AdminProjectsProjectIDRouteImport.update({
  id: '/projects/$projectID',
  path: '/projects/$projectID',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationIDMembersRoute =
  AdminOrganizationIDMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AdminOrganizationIDRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/$organizationID': typeof AdminOrganizationIDRouteWithChildren
  '/auth/setup': typeof AuthSetupRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/$organizationID/members': typeof AdminOrganizationIDMembersRoute
  '/admin/projects/$projectID': typeof AdminProjectsProjectIDRoute
  '/admin/$organizationID/': typeof AdminOrganizationIDIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/setup': typeof AuthSetupRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/admin/$organizationID/members': typeof AdminOrganizationIDMembersRoute
  '/admin/projects/$projectID': typeof AdminProjectsProjectIDRoute
  '/admin/$organizationID': typeof AdminOrganizationIDIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/$organizationID': typeof AdminOrganizationIDRouteWithChildren
  '/auth/setup': typeof AuthSetupRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/$organizationID/members': typeof AdminOrganizationIDMembersRoute
  '/admin/projects/$projectID': typeof AdminProjectsProjectIDRoute
  '/admin/$organizationID/': typeof AdminOrganizationIDIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/$organizationID'
    | '/auth/setup'
    | '/admin/'
    | '/auth/'
    | '/admin/$organizationID/members'
    | '/admin/projects/$projectID'
    | '/admin/$organizationID/'
    | '/admin/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/setup'
    | '/admin'
    | '/auth'
    | '/admin/$organizationID/members'
    | '/admin/projects/$projectID'
    | '/admin/$organizationID'
    | '/admin/projects'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/$organizationID'
    | '/auth/setup'
    | '/admin/'
    | '/auth/'
    | '/admin/$organizationID/members'
    | '/admin/projects/$projectID'
    | '/admin/$organizationID/'
    | '/admin/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthSetupRoute: typeof AuthSetupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/setup': {
      id: '/auth/setup'
      path: '/auth/setup'
      fullPath: '/auth/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$organizationID': {
      id: '/admin/$organizationID'
      path: '/$organizationID'
      fullPath: '/admin/$organizationID'
      preLoaderRoute: typeof AdminOrganizationIDRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$organizationID/': {
      id: '/admin/$organizationID/'
      path: '/'
      fullPath: '/admin/$organizationID/'
      preLoaderRoute: typeof AdminOrganizationIDIndexRouteImport
      parentRoute: typeof AdminOrganizationIDRoute
    }
    '/admin/projects/$projectID': {
      id: '/admin/projects/$projectID'
      path: '/projects/$projectID'
      fullPath: '/admin/projects/$projectID'
      preLoaderRoute: typeof AdminProjectsProjectIDRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$organizationID/members': {
      id: '/admin/$organizationID/members'
      path: '/members'
      fullPath: '/admin/$organizationID/members'
      preLoaderRoute: typeof AdminOrganizationIDMembersRouteImport
      parentRoute: typeof AdminOrganizationIDRoute
    }
  }
}

interface AdminOrganizationIDRouteChildren {
  AdminOrganizationIDMembersRoute: typeof AdminOrganizationIDMembersRoute
  AdminOrganizationIDIndexRoute: typeof AdminOrganizationIDIndexRoute
}

const AdminOrganizationIDRouteChildren: AdminOrganizationIDRouteChildren = {
  AdminOrganizationIDMembersRoute: AdminOrganizationIDMembersRoute,
  AdminOrganizationIDIndexRoute: AdminOrganizationIDIndexRoute,
}

const AdminOrganizationIDRouteWithChildren =
  AdminOrganizationIDRoute._addFileChildren(AdminOrganizationIDRouteChildren)

interface AdminRouteChildren {
  AdminOrganizationIDRoute: typeof AdminOrganizationIDRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProjectsProjectIDRoute: typeof AdminProjectsProjectIDRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrganizationIDRoute: AdminOrganizationIDRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminProjectsProjectIDRoute: AdminProjectsProjectIDRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthSetupRoute: AuthSetupRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
