/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSetupRouteImport } from './routes/auth/setup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthResendVerificationRouteImport } from './routes/auth/resend-verification'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminIntrospectRouteImport } from './routes/admin/introspect'
import { Route as AdminOrganizationIDRouteImport } from './routes/admin/$organizationID'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminOrganizationIDIndexRouteImport } from './routes/admin/$organizationID/index'
import { Route as AuthProviderCallbackRouteImport } from './routes/auth/$provider/callback'
import { Route as AdminProjectsProjectIDRouteImport } from './routes/admin/projects/$projectID'
import { Route as AdminOrganizationIDMembersRouteImport } from './routes/admin/$organizationID/members'
import { Route as AdminProjectsProjectIDIndexRouteImport } from './routes/admin/projects/$projectID/index'
import { Route as AdminProjectsProjectIDProfilesRouteImport } from './routes/admin/projects/$projectID/profiles'
import { Route as AdminProjectsProjectIDOauthRouteImport } from './routes/admin/projects/$projectID/oauth'
import { Route as AdminProjectsProjectIDMembersRouteImport } from './routes/admin/projects/$projectID/members'
import { Route as AdminProjectsProjectIDEmailsRouteImport } from './routes/admin/projects/$projectID/emails'
import { Route as AdminProjectsProjectIDCapabilitiesRouteImport } from './routes/admin/projects/$projectID/capabilities'
import { Route as AdminProjectsProjectIDActorsRouteImport } from './routes/admin/projects/$projectID/actors'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/auth/setup',
  path: '/auth/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResendVerificationRoute = AuthResendVerificationRouteImport.update({
  id: '/auth/resend-verification',
  path: '/auth/resend-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntrospectRoute = AdminIntrospectRouteImport.update({
  id: '/introspect',
  path: '/introspect',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationIDRoute = AdminOrganizationIDRouteImport.update({
  id: '/$organizationID',
  path: '/$organizationID',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationIDIndexRoute =
  AdminOrganizationIDIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminOrganizationIDRoute,
  } as any)
const AuthProviderCallbackRoute = AuthProviderCallbackRouteImport.update({
  id: '/auth/$provider/callback',
  path: '/auth/$provider/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsProjectIDRoute = AdminProjectsProjectIDRouteImport.update({
  id: '/projects/$projectID',
  path: '/projects/$projectID',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationIDMembersRoute =
  AdminOrganizationIDMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AdminOrganizationIDRoute,
  } as any)
const AdminProjectsProjectIDIndexRoute =
  AdminProjectsProjectIDIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminProjectsProjectIDRoute,
  } as any)
const AdminProjectsProjectIDProfilesRoute =
  AdminProjectsProjectIDProfilesRouteImport.update({
    id: '/profiles',
    path: '/profiles',
    getParentRoute: () => AdminProjectsProjectIDRoute,
  } as any)
const AdminProjectsProjectIDOauthRoute =
  AdminProjectsProjectIDOauthRouteImport.update({
    id: '/oauth',
    path: '/oauth',
    getParentRoute: () => AdminProjectsProjectIDRoute,
  } as any)
const AdminProjectsProjectIDMembersRoute =
  AdminProjectsProjectIDMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AdminProjectsProjectIDRoute,
  } as any)
const AdminProjectsProjectIDEmailsRoute =
  AdminProjectsProjectIDEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AdminProjectsProjectIDRoute,
  } as any)
const AdminProjectsProjectIDCapabilitiesRoute =
  AdminProjectsProjectIDCapabilitiesRouteImport.update({
    id: '/capabilities',
    path: '/capabilities',
    getParentRoute: () => AdminProjectsProjectIDRoute,
  } as any)
const AdminProjectsProjectIDActorsRoute =
  AdminProjectsProjectIDActorsRouteImport.update({
    id: '/actors',
    path: '/actors',
    getParentRoute: () => AdminProjectsProjectIDRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/$organizationID': typeof AdminOrganizationIDRouteWithChildren
  '/admin/introspect': typeof AdminIntrospectRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/resend-verification': typeof AuthResendVerificationRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup': typeof AuthSetupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/$organizationID/members': typeof AdminOrganizationIDMembersRoute
  '/admin/projects/$projectID': typeof AdminProjectsProjectIDRouteWithChildren
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/admin/$organizationID/': typeof AdminOrganizationIDIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/projects/$projectID/actors': typeof AdminProjectsProjectIDActorsRoute
  '/admin/projects/$projectID/capabilities': typeof AdminProjectsProjectIDCapabilitiesRoute
  '/admin/projects/$projectID/emails': typeof AdminProjectsProjectIDEmailsRoute
  '/admin/projects/$projectID/members': typeof AdminProjectsProjectIDMembersRoute
  '/admin/projects/$projectID/oauth': typeof AdminProjectsProjectIDOauthRoute
  '/admin/projects/$projectID/profiles': typeof AdminProjectsProjectIDProfilesRoute
  '/admin/projects/$projectID/': typeof AdminProjectsProjectIDIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/introspect': typeof AdminIntrospectRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/resend-verification': typeof AuthResendVerificationRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup': typeof AuthSetupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/admin/$organizationID/members': typeof AdminOrganizationIDMembersRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/admin/$organizationID': typeof AdminOrganizationIDIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/projects/$projectID/actors': typeof AdminProjectsProjectIDActorsRoute
  '/admin/projects/$projectID/capabilities': typeof AdminProjectsProjectIDCapabilitiesRoute
  '/admin/projects/$projectID/emails': typeof AdminProjectsProjectIDEmailsRoute
  '/admin/projects/$projectID/members': typeof AdminProjectsProjectIDMembersRoute
  '/admin/projects/$projectID/oauth': typeof AdminProjectsProjectIDOauthRoute
  '/admin/projects/$projectID/profiles': typeof AdminProjectsProjectIDProfilesRoute
  '/admin/projects/$projectID': typeof AdminProjectsProjectIDIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/$organizationID': typeof AdminOrganizationIDRouteWithChildren
  '/admin/introspect': typeof AdminIntrospectRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/resend-verification': typeof AuthResendVerificationRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup': typeof AuthSetupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/$organizationID/members': typeof AdminOrganizationIDMembersRoute
  '/admin/projects/$projectID': typeof AdminProjectsProjectIDRouteWithChildren
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/admin/$organizationID/': typeof AdminOrganizationIDIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/projects/$projectID/actors': typeof AdminProjectsProjectIDActorsRoute
  '/admin/projects/$projectID/capabilities': typeof AdminProjectsProjectIDCapabilitiesRoute
  '/admin/projects/$projectID/emails': typeof AdminProjectsProjectIDEmailsRoute
  '/admin/projects/$projectID/members': typeof AdminProjectsProjectIDMembersRoute
  '/admin/projects/$projectID/oauth': typeof AdminProjectsProjectIDOauthRoute
  '/admin/projects/$projectID/profiles': typeof AdminProjectsProjectIDProfilesRoute
  '/admin/projects/$projectID/': typeof AdminProjectsProjectIDIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/$organizationID'
    | '/admin/introspect'
    | '/auth/forgot-password'
    | '/auth/resend-verification'
    | '/auth/reset'
    | '/auth/reset-password'
    | '/auth/setup'
    | '/auth/verify'
    | '/auth/verify-email'
    | '/admin/'
    | '/auth/'
    | '/admin/$organizationID/members'
    | '/admin/projects/$projectID'
    | '/auth/$provider/callback'
    | '/admin/$organizationID/'
    | '/admin/projects/'
    | '/admin/projects/$projectID/actors'
    | '/admin/projects/$projectID/capabilities'
    | '/admin/projects/$projectID/emails'
    | '/admin/projects/$projectID/members'
    | '/admin/projects/$projectID/oauth'
    | '/admin/projects/$projectID/profiles'
    | '/admin/projects/$projectID/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/introspect'
    | '/auth/forgot-password'
    | '/auth/resend-verification'
    | '/auth/reset'
    | '/auth/reset-password'
    | '/auth/setup'
    | '/auth/verify'
    | '/auth/verify-email'
    | '/admin'
    | '/auth'
    | '/admin/$organizationID/members'
    | '/auth/$provider/callback'
    | '/admin/$organizationID'
    | '/admin/projects'
    | '/admin/projects/$projectID/actors'
    | '/admin/projects/$projectID/capabilities'
    | '/admin/projects/$projectID/emails'
    | '/admin/projects/$projectID/members'
    | '/admin/projects/$projectID/oauth'
    | '/admin/projects/$projectID/profiles'
    | '/admin/projects/$projectID'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/$organizationID'
    | '/admin/introspect'
    | '/auth/forgot-password'
    | '/auth/resend-verification'
    | '/auth/reset'
    | '/auth/reset-password'
    | '/auth/setup'
    | '/auth/verify'
    | '/auth/verify-email'
    | '/admin/'
    | '/auth/'
    | '/admin/$organizationID/members'
    | '/admin/projects/$projectID'
    | '/auth/$provider/callback'
    | '/admin/$organizationID/'
    | '/admin/projects/'
    | '/admin/projects/$projectID/actors'
    | '/admin/projects/$projectID/capabilities'
    | '/admin/projects/$projectID/emails'
    | '/admin/projects/$projectID/members'
    | '/admin/projects/$projectID/oauth'
    | '/admin/projects/$projectID/profiles'
    | '/admin/projects/$projectID/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResendVerificationRoute: typeof AuthResendVerificationRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetupRoute: typeof AuthSetupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthProviderCallbackRoute: typeof AuthProviderCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/setup': {
      id: '/auth/setup'
      path: '/auth/setup'
      fullPath: '/auth/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/resend-verification': {
      id: '/auth/resend-verification'
      path: '/auth/resend-verification'
      fullPath: '/auth/resend-verification'
      preLoaderRoute: typeof AuthResendVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/introspect': {
      id: '/admin/introspect'
      path: '/introspect'
      fullPath: '/admin/introspect'
      preLoaderRoute: typeof AdminIntrospectRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$organizationID': {
      id: '/admin/$organizationID'
      path: '/$organizationID'
      fullPath: '/admin/$organizationID'
      preLoaderRoute: typeof AdminOrganizationIDRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$organizationID/': {
      id: '/admin/$organizationID/'
      path: '/'
      fullPath: '/admin/$organizationID/'
      preLoaderRoute: typeof AdminOrganizationIDIndexRouteImport
      parentRoute: typeof AdminOrganizationIDRoute
    }
    '/auth/$provider/callback': {
      id: '/auth/$provider/callback'
      path: '/auth/$provider/callback'
      fullPath: '/auth/$provider/callback'
      preLoaderRoute: typeof AuthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$projectID': {
      id: '/admin/projects/$projectID'
      path: '/projects/$projectID'
      fullPath: '/admin/projects/$projectID'
      preLoaderRoute: typeof AdminProjectsProjectIDRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$organizationID/members': {
      id: '/admin/$organizationID/members'
      path: '/members'
      fullPath: '/admin/$organizationID/members'
      preLoaderRoute: typeof AdminOrganizationIDMembersRouteImport
      parentRoute: typeof AdminOrganizationIDRoute
    }
    '/admin/projects/$projectID/': {
      id: '/admin/projects/$projectID/'
      path: '/'
      fullPath: '/admin/projects/$projectID/'
      preLoaderRoute: typeof AdminProjectsProjectIDIndexRouteImport
      parentRoute: typeof AdminProjectsProjectIDRoute
    }
    '/admin/projects/$projectID/profiles': {
      id: '/admin/projects/$projectID/profiles'
      path: '/profiles'
      fullPath: '/admin/projects/$projectID/profiles'
      preLoaderRoute: typeof AdminProjectsProjectIDProfilesRouteImport
      parentRoute: typeof AdminProjectsProjectIDRoute
    }
    '/admin/projects/$projectID/oauth': {
      id: '/admin/projects/$projectID/oauth'
      path: '/oauth'
      fullPath: '/admin/projects/$projectID/oauth'
      preLoaderRoute: typeof AdminProjectsProjectIDOauthRouteImport
      parentRoute: typeof AdminProjectsProjectIDRoute
    }
    '/admin/projects/$projectID/members': {
      id: '/admin/projects/$projectID/members'
      path: '/members'
      fullPath: '/admin/projects/$projectID/members'
      preLoaderRoute: typeof AdminProjectsProjectIDMembersRouteImport
      parentRoute: typeof AdminProjectsProjectIDRoute
    }
    '/admin/projects/$projectID/emails': {
      id: '/admin/projects/$projectID/emails'
      path: '/emails'
      fullPath: '/admin/projects/$projectID/emails'
      preLoaderRoute: typeof AdminProjectsProjectIDEmailsRouteImport
      parentRoute: typeof AdminProjectsProjectIDRoute
    }
    '/admin/projects/$projectID/capabilities': {
      id: '/admin/projects/$projectID/capabilities'
      path: '/capabilities'
      fullPath: '/admin/projects/$projectID/capabilities'
      preLoaderRoute: typeof AdminProjectsProjectIDCapabilitiesRouteImport
      parentRoute: typeof AdminProjectsProjectIDRoute
    }
    '/admin/projects/$projectID/actors': {
      id: '/admin/projects/$projectID/actors'
      path: '/actors'
      fullPath: '/admin/projects/$projectID/actors'
      preLoaderRoute: typeof AdminProjectsProjectIDActorsRouteImport
      parentRoute: typeof AdminProjectsProjectIDRoute
    }
  }
}

interface AdminOrganizationIDRouteChildren {
  AdminOrganizationIDMembersRoute: typeof AdminOrganizationIDMembersRoute
  AdminOrganizationIDIndexRoute: typeof AdminOrganizationIDIndexRoute
}

const AdminOrganizationIDRouteChildren: AdminOrganizationIDRouteChildren = {
  AdminOrganizationIDMembersRoute: AdminOrganizationIDMembersRoute,
  AdminOrganizationIDIndexRoute: AdminOrganizationIDIndexRoute,
}

const AdminOrganizationIDRouteWithChildren =
  AdminOrganizationIDRoute._addFileChildren(AdminOrganizationIDRouteChildren)

interface AdminProjectsProjectIDRouteChildren {
  AdminProjectsProjectIDActorsRoute: typeof AdminProjectsProjectIDActorsRoute
  AdminProjectsProjectIDCapabilitiesRoute: typeof AdminProjectsProjectIDCapabilitiesRoute
  AdminProjectsProjectIDEmailsRoute: typeof AdminProjectsProjectIDEmailsRoute
  AdminProjectsProjectIDMembersRoute: typeof AdminProjectsProjectIDMembersRoute
  AdminProjectsProjectIDOauthRoute: typeof AdminProjectsProjectIDOauthRoute
  AdminProjectsProjectIDProfilesRoute: typeof AdminProjectsProjectIDProfilesRoute
  AdminProjectsProjectIDIndexRoute: typeof AdminProjectsProjectIDIndexRoute
}

const AdminProjectsProjectIDRouteChildren: AdminProjectsProjectIDRouteChildren =
  {
    AdminProjectsProjectIDActorsRoute: AdminProjectsProjectIDActorsRoute,
    AdminProjectsProjectIDCapabilitiesRoute:
      AdminProjectsProjectIDCapabilitiesRoute,
    AdminProjectsProjectIDEmailsRoute: AdminProjectsProjectIDEmailsRoute,
    AdminProjectsProjectIDMembersRoute: AdminProjectsProjectIDMembersRoute,
    AdminProjectsProjectIDOauthRoute: AdminProjectsProjectIDOauthRoute,
    AdminProjectsProjectIDProfilesRoute: AdminProjectsProjectIDProfilesRoute,
    AdminProjectsProjectIDIndexRoute: AdminProjectsProjectIDIndexRoute,
  }

const AdminProjectsProjectIDRouteWithChildren =
  AdminProjectsProjectIDRoute._addFileChildren(
    AdminProjectsProjectIDRouteChildren,
  )

interface AdminRouteChildren {
  AdminOrganizationIDRoute: typeof AdminOrganizationIDRouteWithChildren
  AdminIntrospectRoute: typeof AdminIntrospectRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProjectsProjectIDRoute: typeof AdminProjectsProjectIDRouteWithChildren
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrganizationIDRoute: AdminOrganizationIDRouteWithChildren,
  AdminIntrospectRoute: AdminIntrospectRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProjectsProjectIDRoute: AdminProjectsProjectIDRouteWithChildren,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResendVerificationRoute: AuthResendVerificationRoute,
  AuthResetRoute: AuthResetRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetupRoute: AuthSetupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthProviderCallbackRoute: AuthProviderCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
