/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Payssage API
 * Payssage is TrieOH's payments service: wallet and seller management,
 * payment intents (checkout), payment-provider OAuth connections
 * (MercadoPago), and the webhook pipeline that fans provider events out
 * to tenant webhook endpoints.
 *
 * ## Authentication
 *
 * All endpoints except `POST /webhooks/{provider}` (provider calls it)
 * and `GET /providers/{provider}/callback` (browser redirect target)
 * require a bearer JWT issued by IdentityX:
 *
 * | Scheme | Header |
 * |---|---|
 * | Bearer JWT | `Authorization: Bearer <token>` |
 *
 * ## Response envelope
 *
 * Every JSON response is the `fun.Response` envelope:
 *
 * ```json
 * {
 *   "code": 200,
 *   "message": "",
 *   "data": { "...": "operation payload" },
 *   "error": null,
 *   "pagination": null,
 *   "timestamp": "2026-01-01T12:00:00Z",
 *   "module": "Payssage"
 * }
 * ```
 *
 * - Success: `data` carries the payload. Errors: `error` carries an
 *   `AppError` — `{ "code", "message", "fields", "meta" }`.
 * - `pagination` is reserved for paged list endpoints (currently
 *   unused by Payssage routes).
 *
 * ## Error codes → HTTP status
 *
 * The `error.code` sentinel maps to the HTTP status:
 *
 * | code | status |
 * |---|---|
 * | `BAD_REQUEST`, `VALIDATION_ERROR` | 400 |
 * | `UNAUTHORIZED` | 401 |
 * | `PAYMENT_REQUIRED` | 402 |
 * | `FORBIDDEN` | 403 |
 * | `NOT_FOUND` | 404 |
 * | `METHOD_NOT_ALLOWED` | 405 |
 * | `CONFLICT` | 409 |
 * | `UNPROCESSABLE_ENTITY` | 422 |
 * | `TOO_MANY_REQUESTS` | 429 |
 * | `INTERNAL_ERROR` | 500 |
 * | `NOT_IMPLEMENTED` | 501 |
 * | `BAD_GATEWAY` | 502 |
 * | `SERVICE_UNAVAILABLE` | 503 |
 *
 * ## Amounts
 *
 * All monetary amounts are `amount_cents` / `price_cents` — integer
 * cents (`int64`), never floats.
 *
 * ## Webhooks for tenants
 *
 * When a provider event arrives at `POST /webhooks/{provider}`, Payssage
 * records a webhook event and dispatches one delivery per webhook
 * endpoint registered on the event's wallet. Each delivery POSTs to the
 * endpoint URL:
 *
 * | Header | Value |
 * |---|---|
 * | `Content-Type` | `application/json` |
 * | `X-Payssage-Signature` | `hex( HMAC-SHA256( payload, endpoint.secret ) )` |
 * | `X-Payssage-Event-Type` | Normalized event type (e.g. `payment.succeeded`) |
 *
 * The body is a JSON envelope carrying the raw provider event payload
 * plus the correlation key — the Payssage `intent_id` (never a
 * provider-specific id):
 *
 * ```json
 * {
 *   "intent_id": "...", "wallet_id": "...", "provider": "mercadopago",
 *   "external_id": "<mp_payment_id>", "event_type": "payment.succeeded",
 *   "payload": { ...raw provider payload... }
 * }
 * ```
 *
 * Verify the signature before trusting the payload. Deliveries are
 * retried up to **5 attempts** (any 2xx counts as success; request
 * failures and non-2xx count as failed attempts), after which the
 * delivery is marked `failed`.
 *
 * ## Rate limits
 *
 * The harness applies a fixed rate limit of 400 requests/second with a
 * burst of 20, keyed by client IP. Exceeded requests receive
 * `429 TOO_MANY_REQUESTS`.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { Uuid } from './uuid';
import type { WebhookDeliveryStatus } from './webhookDeliveryStatus';

/**
 * One delivery attempt chain for a webhook event to an endpoint.
 * Retried up to 5 attempts; `attempts` counts them, `response_status`
 * / `response_body` record the last response received from the
 * endpoint. Mirrors `models.WebhookDelivery`.
 */
export interface WebhookDelivery {
  id: Uuid;
  endpoint_id: Uuid;
  event_id: Uuid;
  status: WebhookDeliveryStatus;
  /** Number of attempts made so far (max 5). */
  attempts: number;
  /** @nullable */
  last_attempted_at?: string | null;
  /**
     * HTTP status received from the endpoint on the last attempt.
     * @nullable
     */
  response_status?: number | null;
  /**
     * Response body received from the endpoint on the last attempt (truncated at 10 KB).
     * @nullable
     */
  response_body?: string | null;
  created_at: string;
  /** @nullable */
  updated_at?: string | null;
}
