/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IdentityX API
 * API responsible for authentication, authorization, cryptographic
 * key management, and multi-tenancy across the TrieOH ecosystem.
 *
 * Supports OAuth (Google/GitHub), Ed25519-based JWT issuance, a JWKS
 * endpoint, and multi-tenant project scoping.
 *
 * ## Authentication
 *
 * Every protected endpoint accepts either of:
 *
 * | Scheme | Header | Notes |
 * |---|---|---|
 * | Bearer JWT | `Authorization: Bearer <token>` | Ed25519-signed access token issued by `/auth/login` (or OAuth). |
 * | API key | `X-API-KEY: <key>` | Static key created via `POST /projects/{project_id}/api_keys`; server-to-server access. |
 *
 * Some route groups additionally require a *platform-level* actor
 * (`ClientOnly`) or a *project-scoped* actor (`ProjectClientOnly`);
 * that requirement is called out per operation, since both schemes can
 * satisfy the auth step itself.
 *
 * ## Response envelope
 *
 * Every JSON response (except `/.well-known/jwks.json`, which is a raw
 * JWKS document) is the `fun.Response` envelope:
 *
 * ```json
 * {
 *   "code": 200,
 *   "message": "",
 *   "data": { "...": "operation payload" },
 *   "error": null,
 *   "pagination": null,
 *   "timestamp": "2026-01-01T12:00:00Z",
 *   "module": "IdentityX"
 * }
 * ```
 *
 * - Success: `data` carries the payload. `message` is informational and
 *   often empty.
 * - Failure: `error` carries an `AppError` — `{ "code", "message",
 *   "fields", "meta" }`. `data` is absent.
 * - `pagination` is reserved for paged list endpoints (currently unused
 *   by IdentityX routes).
 *
 * ## Error codes → HTTP status
 *
 * The `error.code` sentinel maps to the HTTP status:
 *
 * | code | status |
 * |---|---|
 * | `BAD_REQUEST`, `VALIDATION_ERROR` | 400 |
 * | `UNAUTHORIZED` | 401 |
 * | `PAYMENT_REQUIRED` | 402 |
 * | `FORBIDDEN` | 403 |
 * | `NOT_FOUND` | 404 |
 * | `METHOD_NOT_ALLOWED` | 405 |
 * | `CONFLICT` | 409 |
 * | `UNPROCESSABLE_ENTITY` | 422 |
 * | `TOO_MANY_REQUESTS` | 429 |
 * | `INTERNAL_ERROR` | 500 |
 * | `NOT_IMPLEMENTED` | 501 |
 * | `BAD_GATEWAY` | 502 |
 * | `SERVICE_UNAVAILABLE` | 503 |
 *
 * ## Rate limits
 *
 * The harness applies a fixed rate limit of 400 requests/second with a
 * burst of 20, keyed by client IP (`RemoteAddr`). Exceeded requests
 * receive `429 TOO_MANY_REQUESTS`.
 *
 * OpenAPI spec version: 0.22.0
 */

/**
 * Request body for removing an org project member. Mirrors `models.RemoveOrgProjectMemberRequest`.
 */
export interface RemoveOrgProjectMemberRequest {
  actor_email: string;
}
