/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComparativeRouteImport } from './routes/comparative'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as VerifyHashRouteImport } from './routes/verify/$hash'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as EventsEventIdProfileRouteImport } from './routes/events/$eventId/profile'
import { Route as AdminEventsEventIdRouteImport } from './routes/admin/events/$eventId'
import { Route as EventsEventIdEditionsIndexRouteImport } from './routes/events/$eventId/editions/index'
import { Route as EventsEventIdEditionsEditionIdIndexRouteImport } from './routes/events/$eventId/editions/$editionId/index'
import { Route as AdminEventsEventIdEditionsIndexRouteImport } from './routes/admin/events/$eventId/editions/index'
import { Route as EventsEventIdEditionsEditionIdProfileRouteImport } from './routes/events/$eventId/editions/$editionId/profile'
import { Route as EventsEventIdEditionsEditionIdProductsRouteImport } from './routes/events/$eventId/editions/$editionId/products'
import { Route as EventsEventIdEditionsEditionIdCheckoutRouteImport } from './routes/events/$eventId/editions/$editionId/checkout'
import { Route as EventsEventIdEditionsEditionIdActivitiesIndexRouteImport } from './routes/events/$eventId/editions/$editionId/activities/index'
import { Route as AdminEventsEventIdEditionsEditionIdIndexRouteImport } from './routes/admin/events/$eventId/editions/$editionId/index'
import { Route as AdminEventsEventIdEditionsEditionIdSignaturesIndexRouteImport } from './routes/admin/events/$eventId/editions/$editionId/signatures/index'
import { Route as AdminEventsEventIdEditionsEditionIdProductsIndexRouteImport } from './routes/admin/events/$eventId/editions/$editionId/products/index'
import { Route as AdminEventsEventIdEditionsEditionIdCheckpointsIndexRouteImport } from './routes/admin/events/$eventId/editions/$editionId/checkpoints/index'
import { Route as AdminEventsEventIdEditionsEditionIdCertificationsIndexRouteImport } from './routes/admin/events/$eventId/editions/$editionId/certifications/index'
import { Route as AdminEventsEventIdEditionsEditionIdActivitiesIndexRouteImport } from './routes/admin/events/$eventId/editions/$editionId/activities/index'
import { Route as AdminEventsEventIdEditionsEditionIdSignaturesEditorRouteImport } from './routes/admin/events/$eventId/editions/$editionId/signatures/editor'
import { Route as AdminEventsEventIdEditionsEditionIdCertificationsEditorRouteImport } from './routes/admin/events/$eventId/editions/$editionId/certifications/editor'
import { Route as AdminEventsEventIdEditionsEditionIdCallbackPaymentRouteImport } from './routes/admin/events/$eventId/editions/$editionId/callback.payment'

const AdminEventsEventIdIndexLazyRouteImport = createFileRoute(
  '/admin/events/$eventId/',
)()

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativeRoute = ComparativeRouteImport.update({
  id: '/comparative',
  path: '/comparative',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/events/index.lazy').then((d) => d.Route))
const VerifyHashRoute = VerifyHashRouteImport.update({
  id: '/verify/$hash',
  path: '/verify/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/events/$eventId/index.lazy').then((d) => d.Route),
)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/events/index.lazy').then((d) => d.Route),
)
const EventsEventIdProfileRoute = EventsEventIdProfileRouteImport.update({
  id: '/events/$eventId/profile',
  path: '/events/$eventId/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventIdRoute = AdminEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsEventIdIndexLazyRoute =
  AdminEventsEventIdIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminEventsEventIdRoute,
  } as any).lazy(() =>
    import('./routes/admin/events/$eventId/index.lazy').then((d) => d.Route),
  )
const EventsEventIdEditionsIndexRoute =
  EventsEventIdEditionsIndexRouteImport.update({
    id: '/events/$eventId/editions/',
    path: '/events/$eventId/editions/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/events/$eventId/editions/index.lazy').then((d) => d.Route),
  )
const EventsEventIdEditionsEditionIdIndexRoute =
  EventsEventIdEditionsEditionIdIndexRouteImport.update({
    id: '/events/$eventId/editions/$editionId/',
    path: '/events/$eventId/editions/$editionId/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/events/$eventId/editions/$editionId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminEventsEventIdEditionsIndexRoute =
  AdminEventsEventIdEditionsIndexRouteImport.update({
    id: '/editions/',
    path: '/editions/',
    getParentRoute: () => AdminEventsEventIdRoute,
  } as any).lazy(() =>
    import('./routes/admin/events/$eventId/editions/index.lazy').then(
      (d) => d.Route,
    ),
  )
const EventsEventIdEditionsEditionIdProfileRoute =
  EventsEventIdEditionsEditionIdProfileRouteImport.update({
    id: '/events/$eventId/editions/$editionId/profile',
    path: '/events/$eventId/editions/$editionId/profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsEventIdEditionsEditionIdProductsRoute =
  EventsEventIdEditionsEditionIdProductsRouteImport.update({
    id: '/events/$eventId/editions/$editionId/products',
    path: '/events/$eventId/editions/$editionId/products',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsEventIdEditionsEditionIdCheckoutRoute =
  EventsEventIdEditionsEditionIdCheckoutRouteImport.update({
    id: '/events/$eventId/editions/$editionId/checkout',
    path: '/events/$eventId/editions/$editionId/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsEventIdEditionsEditionIdActivitiesIndexRoute =
  EventsEventIdEditionsEditionIdActivitiesIndexRouteImport.update({
    id: '/events/$eventId/editions/$editionId/activities/',
    path: '/events/$eventId/editions/$editionId/activities/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/events/$eventId/editions/$editionId/activities/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminEventsEventIdEditionsEditionIdIndexRoute =
  AdminEventsEventIdEditionsEditionIdIndexRouteImport.update({
    id: '/editions/$editionId/',
    path: '/editions/$editionId/',
    getParentRoute: () => AdminEventsEventIdRoute,
  } as any).lazy(() =>
    import('./routes/admin/events/$eventId/editions/$editionId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute =
  AdminEventsEventIdEditionsEditionIdSignaturesIndexRouteImport.update({
    id: '/editions/$editionId/signatures/',
    path: '/editions/$editionId/signatures/',
    getParentRoute: () => AdminEventsEventIdRoute,
  } as any)
const AdminEventsEventIdEditionsEditionIdProductsIndexRoute =
  AdminEventsEventIdEditionsEditionIdProductsIndexRouteImport.update({
    id: '/editions/$editionId/products/',
    path: '/editions/$editionId/products/',
    getParentRoute: () => AdminEventsEventIdRoute,
  } as any).lazy(() =>
    import('./routes/admin/events/$eventId/editions/$editionId/products/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminEventsEventIdEditionsEditionIdCheckpointsIndexRoute =
  AdminEventsEventIdEditionsEditionIdCheckpointsIndexRouteImport.update({
    id: '/editions/$editionId/checkpoints/',
    path: '/editions/$editionId/checkpoints/',
    getParentRoute: () => AdminEventsEventIdRoute,
  } as any)
const AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute =
  AdminEventsEventIdEditionsEditionIdCertificationsIndexRouteImport.update({
    id: '/editions/$editionId/certifications/',
    path: '/editions/$editionId/certifications/',
    getParentRoute: () => AdminEventsEventIdRoute,
  } as any)
const AdminEventsEventIdEditionsEditionIdActivitiesIndexRoute =
  AdminEventsEventIdEditionsEditionIdActivitiesIndexRouteImport.update({
    id: '/editions/$editionId/activities/',
    path: '/editions/$editionId/activities/',
    getParentRoute: () => AdminEventsEventIdRoute,
  } as any).lazy(() =>
    import('./routes/admin/events/$eventId/editions/$editionId/activities/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute =
  AdminEventsEventIdEditionsEditionIdSignaturesEditorRouteImport.update({
    id: '/editions/$editionId/signatures/editor',
    path: '/editions/$editionId/signatures/editor',
    getParentRoute: () => AdminEventsEventIdRoute,
  } as any)
const AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute =
  AdminEventsEventIdEditionsEditionIdCertificationsEditorRouteImport.update({
    id: '/editions/$editionId/certifications/editor',
    path: '/editions/$editionId/certifications/editor',
    getParentRoute: () => AdminEventsEventIdRoute,
  } as any)
const AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute =
  AdminEventsEventIdEditionsEditionIdCallbackPaymentRouteImport.update({
    id: '/editions/$editionId/callback/payment',
    path: '/editions/$editionId/callback/payment',
    getParentRoute: () => AdminEventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/comparative': typeof ComparativeRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/verify/$hash': typeof VerifyHashRoute
  '/events/': typeof EventsIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRouteWithChildren
  '/events/$eventId/profile': typeof EventsEventIdProfileRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/events/$eventId/editions/': typeof EventsEventIdEditionsIndexRoute
  '/admin/events/$eventId/': typeof AdminEventsEventIdIndexLazyRoute
  '/events/$eventId/editions/$editionId/checkout': typeof EventsEventIdEditionsEditionIdCheckoutRoute
  '/events/$eventId/editions/$editionId/products': typeof EventsEventIdEditionsEditionIdProductsRoute
  '/events/$eventId/editions/$editionId/profile': typeof EventsEventIdEditionsEditionIdProfileRoute
  '/admin/events/$eventId/editions/': typeof AdminEventsEventIdEditionsIndexRoute
  '/events/$eventId/editions/$editionId/': typeof EventsEventIdEditionsEditionIdIndexRoute
  '/admin/events/$eventId/editions/$editionId/': typeof AdminEventsEventIdEditionsEditionIdIndexRoute
  '/events/$eventId/editions/$editionId/activities/': typeof EventsEventIdEditionsEditionIdActivitiesIndexRoute
  '/admin/events/$eventId/editions/$editionId/callback/payment': typeof AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute
  '/admin/events/$eventId/editions/$editionId/certifications/editor': typeof AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute
  '/admin/events/$eventId/editions/$editionId/signatures/editor': typeof AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute
  '/admin/events/$eventId/editions/$editionId/activities/': typeof AdminEventsEventIdEditionsEditionIdActivitiesIndexRoute
  '/admin/events/$eventId/editions/$editionId/certifications/': typeof AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute
  '/admin/events/$eventId/editions/$editionId/checkpoints/': typeof AdminEventsEventIdEditionsEditionIdCheckpointsIndexRoute
  '/admin/events/$eventId/editions/$editionId/products/': typeof AdminEventsEventIdEditionsEditionIdProductsIndexRoute
  '/admin/events/$eventId/editions/$editionId/signatures/': typeof AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/comparative': typeof ComparativeRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/verify/$hash': typeof VerifyHashRoute
  '/events': typeof EventsIndexRoute
  '/events/$eventId/profile': typeof EventsEventIdProfileRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/events/$eventId/editions': typeof EventsEventIdEditionsIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdIndexLazyRoute
  '/events/$eventId/editions/$editionId/checkout': typeof EventsEventIdEditionsEditionIdCheckoutRoute
  '/events/$eventId/editions/$editionId/products': typeof EventsEventIdEditionsEditionIdProductsRoute
  '/events/$eventId/editions/$editionId/profile': typeof EventsEventIdEditionsEditionIdProfileRoute
  '/admin/events/$eventId/editions': typeof AdminEventsEventIdEditionsIndexRoute
  '/events/$eventId/editions/$editionId': typeof EventsEventIdEditionsEditionIdIndexRoute
  '/admin/events/$eventId/editions/$editionId': typeof AdminEventsEventIdEditionsEditionIdIndexRoute
  '/events/$eventId/editions/$editionId/activities': typeof EventsEventIdEditionsEditionIdActivitiesIndexRoute
  '/admin/events/$eventId/editions/$editionId/callback/payment': typeof AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute
  '/admin/events/$eventId/editions/$editionId/certifications/editor': typeof AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute
  '/admin/events/$eventId/editions/$editionId/signatures/editor': typeof AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute
  '/admin/events/$eventId/editions/$editionId/activities': typeof AdminEventsEventIdEditionsEditionIdActivitiesIndexRoute
  '/admin/events/$eventId/editions/$editionId/certifications': typeof AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute
  '/admin/events/$eventId/editions/$editionId/checkpoints': typeof AdminEventsEventIdEditionsEditionIdCheckpointsIndexRoute
  '/admin/events/$eventId/editions/$editionId/products': typeof AdminEventsEventIdEditionsEditionIdProductsIndexRoute
  '/admin/events/$eventId/editions/$editionId/signatures': typeof AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/comparative': typeof ComparativeRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/verify/$hash': typeof VerifyHashRoute
  '/events/': typeof EventsIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRouteWithChildren
  '/events/$eventId/profile': typeof EventsEventIdProfileRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/events/$eventId/editions/': typeof EventsEventIdEditionsIndexRoute
  '/admin/events/$eventId/': typeof AdminEventsEventIdIndexLazyRoute
  '/events/$eventId/editions/$editionId/checkout': typeof EventsEventIdEditionsEditionIdCheckoutRoute
  '/events/$eventId/editions/$editionId/products': typeof EventsEventIdEditionsEditionIdProductsRoute
  '/events/$eventId/editions/$editionId/profile': typeof EventsEventIdEditionsEditionIdProfileRoute
  '/admin/events/$eventId/editions/': typeof AdminEventsEventIdEditionsIndexRoute
  '/events/$eventId/editions/$editionId/': typeof EventsEventIdEditionsEditionIdIndexRoute
  '/admin/events/$eventId/editions/$editionId/': typeof AdminEventsEventIdEditionsEditionIdIndexRoute
  '/events/$eventId/editions/$editionId/activities/': typeof EventsEventIdEditionsEditionIdActivitiesIndexRoute
  '/admin/events/$eventId/editions/$editionId/callback/payment': typeof AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute
  '/admin/events/$eventId/editions/$editionId/certifications/editor': typeof AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute
  '/admin/events/$eventId/editions/$editionId/signatures/editor': typeof AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute
  '/admin/events/$eventId/editions/$editionId/activities/': typeof AdminEventsEventIdEditionsEditionIdActivitiesIndexRoute
  '/admin/events/$eventId/editions/$editionId/certifications/': typeof AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute
  '/admin/events/$eventId/editions/$editionId/checkpoints/': typeof AdminEventsEventIdEditionsEditionIdCheckpointsIndexRoute
  '/admin/events/$eventId/editions/$editionId/products/': typeof AdminEventsEventIdEditionsEditionIdProductsIndexRoute
  '/admin/events/$eventId/editions/$editionId/signatures/': typeof AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/comparative'
    | '/contact'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/verify/$hash'
    | '/events/'
    | '/admin/events/$eventId'
    | '/events/$eventId/profile'
    | '/admin/events/'
    | '/events/$eventId/'
    | '/events/$eventId/editions/'
    | '/admin/events/$eventId/'
    | '/events/$eventId/editions/$editionId/checkout'
    | '/events/$eventId/editions/$editionId/products'
    | '/events/$eventId/editions/$editionId/profile'
    | '/admin/events/$eventId/editions/'
    | '/events/$eventId/editions/$editionId/'
    | '/admin/events/$eventId/editions/$editionId/'
    | '/events/$eventId/editions/$editionId/activities/'
    | '/admin/events/$eventId/editions/$editionId/callback/payment'
    | '/admin/events/$eventId/editions/$editionId/certifications/editor'
    | '/admin/events/$eventId/editions/$editionId/signatures/editor'
    | '/admin/events/$eventId/editions/$editionId/activities/'
    | '/admin/events/$eventId/editions/$editionId/certifications/'
    | '/admin/events/$eventId/editions/$editionId/checkpoints/'
    | '/admin/events/$eventId/editions/$editionId/products/'
    | '/admin/events/$eventId/editions/$editionId/signatures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/comparative'
    | '/contact'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/verify/$hash'
    | '/events'
    | '/events/$eventId/profile'
    | '/admin/events'
    | '/events/$eventId'
    | '/events/$eventId/editions'
    | '/admin/events/$eventId'
    | '/events/$eventId/editions/$editionId/checkout'
    | '/events/$eventId/editions/$editionId/products'
    | '/events/$eventId/editions/$editionId/profile'
    | '/admin/events/$eventId/editions'
    | '/events/$eventId/editions/$editionId'
    | '/admin/events/$eventId/editions/$editionId'
    | '/events/$eventId/editions/$editionId/activities'
    | '/admin/events/$eventId/editions/$editionId/callback/payment'
    | '/admin/events/$eventId/editions/$editionId/certifications/editor'
    | '/admin/events/$eventId/editions/$editionId/signatures/editor'
    | '/admin/events/$eventId/editions/$editionId/activities'
    | '/admin/events/$eventId/editions/$editionId/certifications'
    | '/admin/events/$eventId/editions/$editionId/checkpoints'
    | '/admin/events/$eventId/editions/$editionId/products'
    | '/admin/events/$eventId/editions/$editionId/signatures'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/comparative'
    | '/contact'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/verify/$hash'
    | '/events/'
    | '/admin/events/$eventId'
    | '/events/$eventId/profile'
    | '/admin/events/'
    | '/events/$eventId/'
    | '/events/$eventId/editions/'
    | '/admin/events/$eventId/'
    | '/events/$eventId/editions/$editionId/checkout'
    | '/events/$eventId/editions/$editionId/products'
    | '/events/$eventId/editions/$editionId/profile'
    | '/admin/events/$eventId/editions/'
    | '/events/$eventId/editions/$editionId/'
    | '/admin/events/$eventId/editions/$editionId/'
    | '/events/$eventId/editions/$editionId/activities/'
    | '/admin/events/$eventId/editions/$editionId/callback/payment'
    | '/admin/events/$eventId/editions/$editionId/certifications/editor'
    | '/admin/events/$eventId/editions/$editionId/signatures/editor'
    | '/admin/events/$eventId/editions/$editionId/activities/'
    | '/admin/events/$eventId/editions/$editionId/certifications/'
    | '/admin/events/$eventId/editions/$editionId/checkpoints/'
    | '/admin/events/$eventId/editions/$editionId/products/'
    | '/admin/events/$eventId/editions/$editionId/signatures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComparativeRoute: typeof ComparativeRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  TermsRoute: typeof TermsRoute
  VerifyHashRoute: typeof VerifyHashRoute
  EventsIndexRoute: typeof EventsIndexRoute
  EventsEventIdProfileRoute: typeof EventsEventIdProfileRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
  EventsEventIdEditionsIndexRoute: typeof EventsEventIdEditionsIndexRoute
  EventsEventIdEditionsEditionIdCheckoutRoute: typeof EventsEventIdEditionsEditionIdCheckoutRoute
  EventsEventIdEditionsEditionIdProductsRoute: typeof EventsEventIdEditionsEditionIdProductsRoute
  EventsEventIdEditionsEditionIdProfileRoute: typeof EventsEventIdEditionsEditionIdProfileRoute
  EventsEventIdEditionsEditionIdIndexRoute: typeof EventsEventIdEditionsEditionIdIndexRoute
  EventsEventIdEditionsEditionIdActivitiesIndexRoute: typeof EventsEventIdEditionsEditionIdActivitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparative': {
      id: '/comparative'
      path: '/comparative'
      fullPath: '/comparative'
      preLoaderRoute: typeof ComparativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$hash': {
      id: '/verify/$hash'
      path: '/verify/$hash'
      fullPath: '/verify/$hash'
      preLoaderRoute: typeof VerifyHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/$eventId/profile': {
      id: '/events/$eventId/profile'
      path: '/events/$eventId/profile'
      fullPath: '/events/$eventId/profile'
      preLoaderRoute: typeof EventsEventIdProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId': {
      id: '/admin/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AdminEventsEventIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId/': {
      id: '/admin/events/$eventId/'
      path: '/'
      fullPath: '/admin/events/$eventId/'
      preLoaderRoute: typeof AdminEventsEventIdIndexLazyRouteImport
      parentRoute: typeof AdminEventsEventIdRoute
    }
    '/events/$eventId/editions/': {
      id: '/events/$eventId/editions/'
      path: '/events/$eventId/editions'
      fullPath: '/events/$eventId/editions/'
      preLoaderRoute: typeof EventsEventIdEditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/editions/$editionId/': {
      id: '/events/$eventId/editions/$editionId/'
      path: '/events/$eventId/editions/$editionId'
      fullPath: '/events/$eventId/editions/$editionId/'
      preLoaderRoute: typeof EventsEventIdEditionsEditionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/editions/': {
      id: '/admin/events/$eventId/editions/'
      path: '/editions'
      fullPath: '/admin/events/$eventId/editions/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsIndexRouteImport
      parentRoute: typeof AdminEventsEventIdRoute
    }
    '/events/$eventId/editions/$editionId/profile': {
      id: '/events/$eventId/editions/$editionId/profile'
      path: '/events/$eventId/editions/$editionId/profile'
      fullPath: '/events/$eventId/editions/$editionId/profile'
      preLoaderRoute: typeof EventsEventIdEditionsEditionIdProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/editions/$editionId/products': {
      id: '/events/$eventId/editions/$editionId/products'
      path: '/events/$eventId/editions/$editionId/products'
      fullPath: '/events/$eventId/editions/$editionId/products'
      preLoaderRoute: typeof EventsEventIdEditionsEditionIdProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/editions/$editionId/checkout': {
      id: '/events/$eventId/editions/$editionId/checkout'
      path: '/events/$eventId/editions/$editionId/checkout'
      fullPath: '/events/$eventId/editions/$editionId/checkout'
      preLoaderRoute: typeof EventsEventIdEditionsEditionIdCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/editions/$editionId/activities/': {
      id: '/events/$eventId/editions/$editionId/activities/'
      path: '/events/$eventId/editions/$editionId/activities'
      fullPath: '/events/$eventId/editions/$editionId/activities/'
      preLoaderRoute: typeof EventsEventIdEditionsEditionIdActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/editions/$editionId/': {
      id: '/admin/events/$eventId/editions/$editionId/'
      path: '/editions/$editionId'
      fullPath: '/admin/events/$eventId/editions/$editionId/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdIndexRouteImport
      parentRoute: typeof AdminEventsEventIdRoute
    }
    '/admin/events/$eventId/editions/$editionId/signatures/': {
      id: '/admin/events/$eventId/editions/$editionId/signatures/'
      path: '/editions/$editionId/signatures'
      fullPath: '/admin/events/$eventId/editions/$editionId/signatures/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesIndexRouteImport
      parentRoute: typeof AdminEventsEventIdRoute
    }
    '/admin/events/$eventId/editions/$editionId/products/': {
      id: '/admin/events/$eventId/editions/$editionId/products/'
      path: '/editions/$editionId/products'
      fullPath: '/admin/events/$eventId/editions/$editionId/products/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdProductsIndexRouteImport
      parentRoute: typeof AdminEventsEventIdRoute
    }
    '/admin/events/$eventId/editions/$editionId/checkpoints/': {
      id: '/admin/events/$eventId/editions/$editionId/checkpoints/'
      path: '/editions/$editionId/checkpoints'
      fullPath: '/admin/events/$eventId/editions/$editionId/checkpoints/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdCheckpointsIndexRouteImport
      parentRoute: typeof AdminEventsEventIdRoute
    }
    '/admin/events/$eventId/editions/$editionId/certifications/': {
      id: '/admin/events/$eventId/editions/$editionId/certifications/'
      path: '/editions/$editionId/certifications'
      fullPath: '/admin/events/$eventId/editions/$editionId/certifications/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdCertificationsIndexRouteImport
      parentRoute: typeof AdminEventsEventIdRoute
    }
    '/admin/events/$eventId/editions/$editionId/activities/': {
      id: '/admin/events/$eventId/editions/$editionId/activities/'
      path: '/editions/$editionId/activities'
      fullPath: '/admin/events/$eventId/editions/$editionId/activities/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdActivitiesIndexRouteImport
      parentRoute: typeof AdminEventsEventIdRoute
    }
    '/admin/events/$eventId/editions/$editionId/signatures/editor': {
      id: '/admin/events/$eventId/editions/$editionId/signatures/editor'
      path: '/editions/$editionId/signatures/editor'
      fullPath: '/admin/events/$eventId/editions/$editionId/signatures/editor'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesEditorRouteImport
      parentRoute: typeof AdminEventsEventIdRoute
    }
    '/admin/events/$eventId/editions/$editionId/certifications/editor': {
      id: '/admin/events/$eventId/editions/$editionId/certifications/editor'
      path: '/editions/$editionId/certifications/editor'
      fullPath: '/admin/events/$eventId/editions/$editionId/certifications/editor'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdCertificationsEditorRouteImport
      parentRoute: typeof AdminEventsEventIdRoute
    }
    '/admin/events/$eventId/editions/$editionId/callback/payment': {
      id: '/admin/events/$eventId/editions/$editionId/callback/payment'
      path: '/editions/$editionId/callback/payment'
      fullPath: '/admin/events/$eventId/editions/$editionId/callback/payment'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdCallbackPaymentRouteImport
      parentRoute: typeof AdminEventsEventIdRoute
    }
  }
}

interface AdminEventsEventIdRouteChildren {
  AdminEventsEventIdIndexLazyRoute: typeof AdminEventsEventIdIndexLazyRoute
  AdminEventsEventIdEditionsIndexRoute: typeof AdminEventsEventIdEditionsIndexRoute
  AdminEventsEventIdEditionsEditionIdIndexRoute: typeof AdminEventsEventIdEditionsEditionIdIndexRoute
  AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute: typeof AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute
  AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute: typeof AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute
  AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute
  AdminEventsEventIdEditionsEditionIdActivitiesIndexRoute: typeof AdminEventsEventIdEditionsEditionIdActivitiesIndexRoute
  AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute: typeof AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute
  AdminEventsEventIdEditionsEditionIdCheckpointsIndexRoute: typeof AdminEventsEventIdEditionsEditionIdCheckpointsIndexRoute
  AdminEventsEventIdEditionsEditionIdProductsIndexRoute: typeof AdminEventsEventIdEditionsEditionIdProductsIndexRoute
  AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute
}

const AdminEventsEventIdRouteChildren: AdminEventsEventIdRouteChildren = {
  AdminEventsEventIdIndexLazyRoute: AdminEventsEventIdIndexLazyRoute,
  AdminEventsEventIdEditionsIndexRoute: AdminEventsEventIdEditionsIndexRoute,
  AdminEventsEventIdEditionsEditionIdIndexRoute:
    AdminEventsEventIdEditionsEditionIdIndexRoute,
  AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute:
    AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute,
  AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute:
    AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute,
  AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute:
    AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute,
  AdminEventsEventIdEditionsEditionIdActivitiesIndexRoute:
    AdminEventsEventIdEditionsEditionIdActivitiesIndexRoute,
  AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute:
    AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute,
  AdminEventsEventIdEditionsEditionIdCheckpointsIndexRoute:
    AdminEventsEventIdEditionsEditionIdCheckpointsIndexRoute,
  AdminEventsEventIdEditionsEditionIdProductsIndexRoute:
    AdminEventsEventIdEditionsEditionIdProductsIndexRoute,
  AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute:
    AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute,
}

const AdminEventsEventIdRouteWithChildren =
  AdminEventsEventIdRoute._addFileChildren(AdminEventsEventIdRouteChildren)

interface AdminRouteChildren {
  AdminEventsEventIdRoute: typeof AdminEventsEventIdRouteWithChildren
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsEventIdRoute: AdminEventsEventIdRouteWithChildren,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ComparativeRoute: ComparativeRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  TermsRoute: TermsRoute,
  VerifyHashRoute: VerifyHashRoute,
  EventsIndexRoute: EventsIndexRoute,
  EventsEventIdProfileRoute: EventsEventIdProfileRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
  EventsEventIdEditionsIndexRoute: EventsEventIdEditionsIndexRoute,
  EventsEventIdEditionsEditionIdCheckoutRoute:
    EventsEventIdEditionsEditionIdCheckoutRoute,
  EventsEventIdEditionsEditionIdProductsRoute:
    EventsEventIdEditionsEditionIdProductsRoute,
  EventsEventIdEditionsEditionIdProfileRoute:
    EventsEventIdEditionsEditionIdProfileRoute,
  EventsEventIdEditionsEditionIdIndexRoute:
    EventsEventIdEditionsEditionIdIndexRoute,
  EventsEventIdEditionsEditionIdActivitiesIndexRoute:
    EventsEventIdEditionsEditionIdActivitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
