/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComparativeRouteImport } from './routes/comparative'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as VerifyHashRouteImport } from './routes/verify/$hash'
import { Route as SignaturesRevokeRouteImport } from './routes/signatures/revoke'
import { Route as SignatureRequestsFulfillRouteImport } from './routes/signature-requests/fulfill'
import { Route as AdminUploadsRouteImport } from './routes/admin/uploads'
import { Route as EventsSlugIndexRouteImport } from './routes/events/$slug/index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as EventsSlugTicketsRouteImport } from './routes/events/$slug/tickets'
import { Route as EventsSlugProgramsRouteImport } from './routes/events/$slug/programs'
import { Route as EventsSlugProfileRouteImport } from './routes/events/$slug/profile'
import { Route as AuthProviderCallbackRouteImport } from './routes/auth_/$provider/callback'
import { Route as EventsSlugEditionsIndexRouteImport } from './routes/events/$slug/editions/index'
import { Route as AdminEventsEventIdMembersIndexRouteImport } from './routes/admin/events/$eventId/members/index'
import { Route as AdminEventsEventIdEditionsIndexRouteImport } from './routes/admin/events/$eventId/editions/index'
import { Route as EventsEventIdEditionsEditionIdProductsRouteImport } from './routes/events/$eventId/editions/$editionId/products'
import { Route as AdminEventsEventIdEditionsEditionIdIndexRouteImport } from './routes/admin/events/$eventId_.editions.$editionId/index'
import { Route as AdminEventsEventIdEditionsEditionIdSignaturesRouteImport } from './routes/admin/events/$eventId_.editions.$editionId/signatures'
import { Route as AdminEventsEventIdEditionsEditionIdTicketsIndexRouteImport } from './routes/admin/events/$eventId_.editions.$editionId/tickets/index'
import { Route as AdminEventsEventIdEditionsEditionIdSignaturesIndexRouteImport } from './routes/admin/events/$eventId_.editions.$editionId/signatures/index'
import { Route as AdminEventsEventIdEditionsEditionIdProductsIndexRouteImport } from './routes/admin/events/$eventId_.editions.$editionId/products/index'
import { Route as AdminEventsEventIdEditionsEditionIdCertificationsIndexRouteImport } from './routes/admin/events/$eventId_.editions.$editionId/certifications/index'
import { Route as AdminEventsEventIdEditionsEditionIdSignaturesInvitesRouteImport } from './routes/admin/events/$eventId_.editions.$editionId/signatures/invites'
import { Route as AdminEventsEventIdEditionsEditionIdSignaturesEditorRouteImport } from './routes/admin/events/$eventId_.editions.$editionId/signatures/editor'
import { Route as AdminEventsEventIdEditionsEditionIdCertificationsEditorRouteImport } from './routes/admin/events/$eventId_.editions.$editionId/certifications/editor'
import { Route as AdminEventsEventIdEditionsEditionIdCallbackPaymentRouteImport } from './routes/admin/events/$eventId_.editions.$editionId/callback.payment'
import { Route as AdminEventsEventIdEditionsEditionIdProductsProductIdVariantsIndexRouteImport } from './routes/admin/events/$eventId_.editions.$editionId/products/$productId.variants/index'

const AdminEventsEventIdIndexLazyRouteImport = createFileRoute(
  '/admin/events/$eventId/',
)()
const AdminEventsEventIdEditionsEditionIdProgramsIndexLazyRouteImport =
  createFileRoute('/admin/events/$eventId_/editions/$editionId/programs/')()
const AdminEventsEventIdEditionsEditionIdProgramsCalendarLazyRouteImport =
  createFileRoute(
    '/admin/events/$eventId_/editions/$editionId/programs/calendar',
  )()
const AdminEventsEventIdEditionsEditionIdProgramsProgramIdOccurrencesIndexLazyRouteImport =
  createFileRoute(
    '/admin/events/$eventId_/editions/$editionId/programs/$programId/occurrences/',
  )()

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativeRoute = ComparativeRouteImport.update({
  id: '/comparative',
  path: '/comparative',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/events/index.lazy').then((d) => d.Route))
const VerifyHashRoute = VerifyHashRouteImport.update({
  id: '/verify/$hash',
  path: '/verify/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const SignaturesRevokeRoute = SignaturesRevokeRouteImport.update({
  id: '/signatures/revoke',
  path: '/signatures/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const SignatureRequestsFulfillRoute =
  SignatureRequestsFulfillRouteImport.update({
    id: '/signature-requests/fulfill',
    path: '/signature-requests/fulfill',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUploadsRoute = AdminUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AdminRoute,
} as any)
const EventsSlugIndexRoute = EventsSlugIndexRouteImport.update({
  id: '/events/$slug/',
  path: '/events/$slug/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/events/$slug/index.lazy').then((d) => d.Route),
)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/events/index.lazy').then((d) => d.Route),
)
const EventsSlugTicketsRoute = EventsSlugTicketsRouteImport.update({
  id: '/events/$slug/tickets',
  path: '/events/$slug/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugProgramsRoute = EventsSlugProgramsRouteImport.update({
  id: '/events/$slug/programs',
  path: '/events/$slug/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugProfileRoute = EventsSlugProfileRouteImport.update({
  id: '/events/$slug/profile',
  path: '/events/$slug/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProviderCallbackRoute = AuthProviderCallbackRouteImport.update({
  id: '/auth_/$provider/callback',
  path: '/auth/$provider/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventIdIndexLazyRoute =
  AdminEventsEventIdIndexLazyRouteImport.update({
    id: '/events/$eventId/',
    path: '/events/$eventId/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/events/$eventId/index.lazy').then((d) => d.Route),
  )
const EventsSlugEditionsIndexRoute = EventsSlugEditionsIndexRouteImport.update({
  id: '/events/$slug/editions/',
  path: '/events/$slug/editions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventIdMembersIndexRoute =
  AdminEventsEventIdMembersIndexRouteImport.update({
    id: '/events/$eventId/members/',
    path: '/events/$eventId/members/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/events/$eventId/members/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminEventsEventIdEditionsIndexRoute =
  AdminEventsEventIdEditionsIndexRouteImport.update({
    id: '/events/$eventId/editions/',
    path: '/events/$eventId/editions/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/events/$eventId/editions/index.lazy').then(
      (d) => d.Route,
    ),
  )
const EventsEventIdEditionsEditionIdProductsRoute =
  EventsEventIdEditionsEditionIdProductsRouteImport.update({
    id: '/events/$eventId/editions/$editionId/products',
    path: '/events/$eventId/editions/$editionId/products',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEventsEventIdEditionsEditionIdIndexRoute =
  AdminEventsEventIdEditionsEditionIdIndexRouteImport.update({
    id: '/events/$eventId_/editions/$editionId/',
    path: '/events/$eventId/editions/$editionId/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/events/$eventId_.editions.$editionId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminEventsEventIdEditionsEditionIdSignaturesRoute =
  AdminEventsEventIdEditionsEditionIdSignaturesRouteImport.update({
    id: '/events/$eventId_/editions/$editionId/signatures',
    path: '/events/$eventId/editions/$editionId/signatures',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEventsEventIdEditionsEditionIdProgramsIndexLazyRoute =
  AdminEventsEventIdEditionsEditionIdProgramsIndexLazyRouteImport.update({
    id: '/events/$eventId_/editions/$editionId/programs/',
    path: '/events/$eventId/editions/$editionId/programs/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/events/$eventId_.editions.$editionId/programs/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminEventsEventIdEditionsEditionIdTicketsIndexRoute =
  AdminEventsEventIdEditionsEditionIdTicketsIndexRouteImport.update({
    id: '/events/$eventId_/editions/$editionId/tickets/',
    path: '/events/$eventId/editions/$editionId/tickets/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/events/$eventId_.editions.$editionId/tickets/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute =
  AdminEventsEventIdEditionsEditionIdSignaturesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminEventsEventIdEditionsEditionIdSignaturesRoute,
  } as any)
const AdminEventsEventIdEditionsEditionIdProductsIndexRoute =
  AdminEventsEventIdEditionsEditionIdProductsIndexRouteImport.update({
    id: '/events/$eventId_/editions/$editionId/products/',
    path: '/events/$eventId/editions/$editionId/products/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/events/$eventId_.editions.$editionId/products/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute =
  AdminEventsEventIdEditionsEditionIdCertificationsIndexRouteImport.update({
    id: '/events/$eventId_/editions/$editionId/certifications/',
    path: '/events/$eventId/editions/$editionId/certifications/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEventsEventIdEditionsEditionIdProgramsCalendarLazyRoute =
  AdminEventsEventIdEditionsEditionIdProgramsCalendarLazyRouteImport.update({
    id: '/events/$eventId_/editions/$editionId/programs/calendar',
    path: '/events/$eventId/editions/$editionId/programs/calendar',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/events/$eventId_.editions.$editionId/programs/calendar.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminEventsEventIdEditionsEditionIdSignaturesInvitesRoute =
  AdminEventsEventIdEditionsEditionIdSignaturesInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AdminEventsEventIdEditionsEditionIdSignaturesRoute,
  } as any)
const AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute =
  AdminEventsEventIdEditionsEditionIdSignaturesEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => AdminEventsEventIdEditionsEditionIdSignaturesRoute,
  } as any)
const AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute =
  AdminEventsEventIdEditionsEditionIdCertificationsEditorRouteImport.update({
    id: '/events/$eventId_/editions/$editionId/certifications/editor',
    path: '/events/$eventId/editions/$editionId/certifications/editor',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute =
  AdminEventsEventIdEditionsEditionIdCallbackPaymentRouteImport.update({
    id: '/events/$eventId_/editions/$editionId/callback/payment',
    path: '/events/$eventId/editions/$editionId/callback/payment',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEventsEventIdEditionsEditionIdProgramsProgramIdOccurrencesIndexLazyRoute =
  AdminEventsEventIdEditionsEditionIdProgramsProgramIdOccurrencesIndexLazyRouteImport.update(
    {
      id: '/events/$eventId_/editions/$editionId/programs/$programId/occurrences/',
      path: '/events/$eventId/editions/$editionId/programs/$programId/occurrences/',
      getParentRoute: () => AdminRoute,
    } as any,
  ).lazy(() =>
    import('./routes/admin/events/$eventId_.editions.$editionId/programs/$programId.occurrences/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminEventsEventIdEditionsEditionIdProductsProductIdVariantsIndexRoute =
  AdminEventsEventIdEditionsEditionIdProductsProductIdVariantsIndexRouteImport.update(
    {
      id: '/events/$eventId_/editions/$editionId/products/$productId/variants/',
      path: '/events/$eventId/editions/$editionId/products/$productId/variants/',
      getParentRoute: () => AdminRoute,
    } as any,
  ).lazy(() =>
    import('./routes/admin/events/$eventId_.editions.$editionId/products/$productId.variants/index.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/comparative': typeof ComparativeRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/admin/uploads': typeof AdminUploadsRoute
  '/signature-requests/fulfill': typeof SignatureRequestsFulfillRoute
  '/signatures/revoke': typeof SignaturesRevokeRoute
  '/verify/$hash': typeof VerifyHashRoute
  '/events/': typeof EventsIndexRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/events/$slug/profile': typeof EventsSlugProfileRoute
  '/events/$slug/programs': typeof EventsSlugProgramsRoute
  '/events/$slug/tickets': typeof EventsSlugTicketsRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
  '/events/$slug/editions/': typeof EventsSlugEditionsIndexRoute
  '/admin/events/$eventId/': typeof AdminEventsEventIdIndexLazyRoute
  '/events/$eventId/editions/$editionId/products': typeof EventsEventIdEditionsEditionIdProductsRoute
  '/admin/events/$eventId/editions/': typeof AdminEventsEventIdEditionsIndexRoute
  '/admin/events/$eventId/members/': typeof AdminEventsEventIdMembersIndexRoute
  '/admin/events/$eventId/editions/$editionId/signatures': typeof AdminEventsEventIdEditionsEditionIdSignaturesRouteWithChildren
  '/admin/events/$eventId/editions/$editionId/': typeof AdminEventsEventIdEditionsEditionIdIndexRoute
  '/admin/events/$eventId/editions/$editionId/callback/payment': typeof AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute
  '/admin/events/$eventId/editions/$editionId/certifications/editor': typeof AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute
  '/admin/events/$eventId/editions/$editionId/signatures/editor': typeof AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute
  '/admin/events/$eventId/editions/$editionId/signatures/invites': typeof AdminEventsEventIdEditionsEditionIdSignaturesInvitesRoute
  '/admin/events/$eventId/editions/$editionId/programs/calendar': typeof AdminEventsEventIdEditionsEditionIdProgramsCalendarLazyRoute
  '/admin/events/$eventId/editions/$editionId/certifications/': typeof AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute
  '/admin/events/$eventId/editions/$editionId/products/': typeof AdminEventsEventIdEditionsEditionIdProductsIndexRoute
  '/admin/events/$eventId/editions/$editionId/signatures/': typeof AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute
  '/admin/events/$eventId/editions/$editionId/tickets/': typeof AdminEventsEventIdEditionsEditionIdTicketsIndexRoute
  '/admin/events/$eventId/editions/$editionId/programs/': typeof AdminEventsEventIdEditionsEditionIdProgramsIndexLazyRoute
  '/admin/events/$eventId/editions/$editionId/products/$productId/variants/': typeof AdminEventsEventIdEditionsEditionIdProductsProductIdVariantsIndexRoute
  '/admin/events/$eventId/editions/$editionId/programs/$programId/occurrences/': typeof AdminEventsEventIdEditionsEditionIdProgramsProgramIdOccurrencesIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/comparative': typeof ComparativeRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/admin/uploads': typeof AdminUploadsRoute
  '/signature-requests/fulfill': typeof SignatureRequestsFulfillRoute
  '/signatures/revoke': typeof SignaturesRevokeRoute
  '/verify/$hash': typeof VerifyHashRoute
  '/events': typeof EventsIndexRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/events/$slug/profile': typeof EventsSlugProfileRoute
  '/events/$slug/programs': typeof EventsSlugProgramsRoute
  '/events/$slug/tickets': typeof EventsSlugTicketsRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/events/$slug': typeof EventsSlugIndexRoute
  '/events/$slug/editions': typeof EventsSlugEditionsIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdIndexLazyRoute
  '/events/$eventId/editions/$editionId/products': typeof EventsEventIdEditionsEditionIdProductsRoute
  '/admin/events/$eventId/editions': typeof AdminEventsEventIdEditionsIndexRoute
  '/admin/events/$eventId/members': typeof AdminEventsEventIdMembersIndexRoute
  '/admin/events/$eventId/editions/$editionId': typeof AdminEventsEventIdEditionsEditionIdIndexRoute
  '/admin/events/$eventId/editions/$editionId/callback/payment': typeof AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute
  '/admin/events/$eventId/editions/$editionId/certifications/editor': typeof AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute
  '/admin/events/$eventId/editions/$editionId/signatures/editor': typeof AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute
  '/admin/events/$eventId/editions/$editionId/signatures/invites': typeof AdminEventsEventIdEditionsEditionIdSignaturesInvitesRoute
  '/admin/events/$eventId/editions/$editionId/programs/calendar': typeof AdminEventsEventIdEditionsEditionIdProgramsCalendarLazyRoute
  '/admin/events/$eventId/editions/$editionId/certifications': typeof AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute
  '/admin/events/$eventId/editions/$editionId/products': typeof AdminEventsEventIdEditionsEditionIdProductsIndexRoute
  '/admin/events/$eventId/editions/$editionId/signatures': typeof AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute
  '/admin/events/$eventId/editions/$editionId/tickets': typeof AdminEventsEventIdEditionsEditionIdTicketsIndexRoute
  '/admin/events/$eventId/editions/$editionId/programs': typeof AdminEventsEventIdEditionsEditionIdProgramsIndexLazyRoute
  '/admin/events/$eventId/editions/$editionId/products/$productId/variants': typeof AdminEventsEventIdEditionsEditionIdProductsProductIdVariantsIndexRoute
  '/admin/events/$eventId/editions/$editionId/programs/$programId/occurrences': typeof AdminEventsEventIdEditionsEditionIdProgramsProgramIdOccurrencesIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/comparative': typeof ComparativeRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/admin/uploads': typeof AdminUploadsRoute
  '/signature-requests/fulfill': typeof SignatureRequestsFulfillRoute
  '/signatures/revoke': typeof SignaturesRevokeRoute
  '/verify/$hash': typeof VerifyHashRoute
  '/events/': typeof EventsIndexRoute
  '/auth_/$provider/callback': typeof AuthProviderCallbackRoute
  '/events/$slug/profile': typeof EventsSlugProfileRoute
  '/events/$slug/programs': typeof EventsSlugProgramsRoute
  '/events/$slug/tickets': typeof EventsSlugTicketsRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
  '/events/$slug/editions/': typeof EventsSlugEditionsIndexRoute
  '/admin/events/$eventId/': typeof AdminEventsEventIdIndexLazyRoute
  '/events/$eventId/editions/$editionId/products': typeof EventsEventIdEditionsEditionIdProductsRoute
  '/admin/events/$eventId/editions/': typeof AdminEventsEventIdEditionsIndexRoute
  '/admin/events/$eventId/members/': typeof AdminEventsEventIdMembersIndexRoute
  '/admin/events/$eventId_/editions/$editionId/signatures': typeof AdminEventsEventIdEditionsEditionIdSignaturesRouteWithChildren
  '/admin/events/$eventId_/editions/$editionId/': typeof AdminEventsEventIdEditionsEditionIdIndexRoute
  '/admin/events/$eventId_/editions/$editionId/callback/payment': typeof AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute
  '/admin/events/$eventId_/editions/$editionId/certifications/editor': typeof AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute
  '/admin/events/$eventId_/editions/$editionId/signatures/editor': typeof AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute
  '/admin/events/$eventId_/editions/$editionId/signatures/invites': typeof AdminEventsEventIdEditionsEditionIdSignaturesInvitesRoute
  '/admin/events/$eventId_/editions/$editionId/programs/calendar': typeof AdminEventsEventIdEditionsEditionIdProgramsCalendarLazyRoute
  '/admin/events/$eventId_/editions/$editionId/certifications/': typeof AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute
  '/admin/events/$eventId_/editions/$editionId/products/': typeof AdminEventsEventIdEditionsEditionIdProductsIndexRoute
  '/admin/events/$eventId_/editions/$editionId/signatures/': typeof AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute
  '/admin/events/$eventId_/editions/$editionId/tickets/': typeof AdminEventsEventIdEditionsEditionIdTicketsIndexRoute
  '/admin/events/$eventId_/editions/$editionId/programs/': typeof AdminEventsEventIdEditionsEditionIdProgramsIndexLazyRoute
  '/admin/events/$eventId_/editions/$editionId/products/$productId/variants/': typeof AdminEventsEventIdEditionsEditionIdProductsProductIdVariantsIndexRoute
  '/admin/events/$eventId_/editions/$editionId/programs/$programId/occurrences/': typeof AdminEventsEventIdEditionsEditionIdProgramsProgramIdOccurrencesIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/comparative'
    | '/contact'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/admin/uploads'
    | '/signature-requests/fulfill'
    | '/signatures/revoke'
    | '/verify/$hash'
    | '/events/'
    | '/auth/$provider/callback'
    | '/events/$slug/profile'
    | '/events/$slug/programs'
    | '/events/$slug/tickets'
    | '/admin/events/'
    | '/events/$slug/'
    | '/events/$slug/editions/'
    | '/admin/events/$eventId/'
    | '/events/$eventId/editions/$editionId/products'
    | '/admin/events/$eventId/editions/'
    | '/admin/events/$eventId/members/'
    | '/admin/events/$eventId/editions/$editionId/signatures'
    | '/admin/events/$eventId/editions/$editionId/'
    | '/admin/events/$eventId/editions/$editionId/callback/payment'
    | '/admin/events/$eventId/editions/$editionId/certifications/editor'
    | '/admin/events/$eventId/editions/$editionId/signatures/editor'
    | '/admin/events/$eventId/editions/$editionId/signatures/invites'
    | '/admin/events/$eventId/editions/$editionId/programs/calendar'
    | '/admin/events/$eventId/editions/$editionId/certifications/'
    | '/admin/events/$eventId/editions/$editionId/products/'
    | '/admin/events/$eventId/editions/$editionId/signatures/'
    | '/admin/events/$eventId/editions/$editionId/tickets/'
    | '/admin/events/$eventId/editions/$editionId/programs/'
    | '/admin/events/$eventId/editions/$editionId/products/$productId/variants/'
    | '/admin/events/$eventId/editions/$editionId/programs/$programId/occurrences/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/comparative'
    | '/contact'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/admin/uploads'
    | '/signature-requests/fulfill'
    | '/signatures/revoke'
    | '/verify/$hash'
    | '/events'
    | '/auth/$provider/callback'
    | '/events/$slug/profile'
    | '/events/$slug/programs'
    | '/events/$slug/tickets'
    | '/admin/events'
    | '/events/$slug'
    | '/events/$slug/editions'
    | '/admin/events/$eventId'
    | '/events/$eventId/editions/$editionId/products'
    | '/admin/events/$eventId/editions'
    | '/admin/events/$eventId/members'
    | '/admin/events/$eventId/editions/$editionId'
    | '/admin/events/$eventId/editions/$editionId/callback/payment'
    | '/admin/events/$eventId/editions/$editionId/certifications/editor'
    | '/admin/events/$eventId/editions/$editionId/signatures/editor'
    | '/admin/events/$eventId/editions/$editionId/signatures/invites'
    | '/admin/events/$eventId/editions/$editionId/programs/calendar'
    | '/admin/events/$eventId/editions/$editionId/certifications'
    | '/admin/events/$eventId/editions/$editionId/products'
    | '/admin/events/$eventId/editions/$editionId/signatures'
    | '/admin/events/$eventId/editions/$editionId/tickets'
    | '/admin/events/$eventId/editions/$editionId/programs'
    | '/admin/events/$eventId/editions/$editionId/products/$productId/variants'
    | '/admin/events/$eventId/editions/$editionId/programs/$programId/occurrences'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/comparative'
    | '/contact'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/admin/uploads'
    | '/signature-requests/fulfill'
    | '/signatures/revoke'
    | '/verify/$hash'
    | '/events/'
    | '/auth_/$provider/callback'
    | '/events/$slug/profile'
    | '/events/$slug/programs'
    | '/events/$slug/tickets'
    | '/admin/events/'
    | '/events/$slug/'
    | '/events/$slug/editions/'
    | '/admin/events/$eventId/'
    | '/events/$eventId/editions/$editionId/products'
    | '/admin/events/$eventId/editions/'
    | '/admin/events/$eventId/members/'
    | '/admin/events/$eventId_/editions/$editionId/signatures'
    | '/admin/events/$eventId_/editions/$editionId/'
    | '/admin/events/$eventId_/editions/$editionId/callback/payment'
    | '/admin/events/$eventId_/editions/$editionId/certifications/editor'
    | '/admin/events/$eventId_/editions/$editionId/signatures/editor'
    | '/admin/events/$eventId_/editions/$editionId/signatures/invites'
    | '/admin/events/$eventId_/editions/$editionId/programs/calendar'
    | '/admin/events/$eventId_/editions/$editionId/certifications/'
    | '/admin/events/$eventId_/editions/$editionId/products/'
    | '/admin/events/$eventId_/editions/$editionId/signatures/'
    | '/admin/events/$eventId_/editions/$editionId/tickets/'
    | '/admin/events/$eventId_/editions/$editionId/programs/'
    | '/admin/events/$eventId_/editions/$editionId/products/$productId/variants/'
    | '/admin/events/$eventId_/editions/$editionId/programs/$programId/occurrences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComparativeRoute: typeof ComparativeRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  TermsRoute: typeof TermsRoute
  SignatureRequestsFulfillRoute: typeof SignatureRequestsFulfillRoute
  SignaturesRevokeRoute: typeof SignaturesRevokeRoute
  VerifyHashRoute: typeof VerifyHashRoute
  EventsIndexRoute: typeof EventsIndexRoute
  AuthProviderCallbackRoute: typeof AuthProviderCallbackRoute
  EventsSlugProfileRoute: typeof EventsSlugProfileRoute
  EventsSlugProgramsRoute: typeof EventsSlugProgramsRoute
  EventsSlugTicketsRoute: typeof EventsSlugTicketsRoute
  EventsSlugIndexRoute: typeof EventsSlugIndexRoute
  EventsSlugEditionsIndexRoute: typeof EventsSlugEditionsIndexRoute
  EventsEventIdEditionsEditionIdProductsRoute: typeof EventsEventIdEditionsEditionIdProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparative': {
      id: '/comparative'
      path: '/comparative'
      fullPath: '/comparative'
      preLoaderRoute: typeof ComparativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$hash': {
      id: '/verify/$hash'
      path: '/verify/$hash'
      fullPath: '/verify/$hash'
      preLoaderRoute: typeof VerifyHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signatures/revoke': {
      id: '/signatures/revoke'
      path: '/signatures/revoke'
      fullPath: '/signatures/revoke'
      preLoaderRoute: typeof SignaturesRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signature-requests/fulfill': {
      id: '/signature-requests/fulfill'
      path: '/signature-requests/fulfill'
      fullPath: '/signature-requests/fulfill'
      preLoaderRoute: typeof SignatureRequestsFulfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/uploads': {
      id: '/admin/uploads'
      path: '/uploads'
      fullPath: '/admin/uploads'
      preLoaderRoute: typeof AdminUploadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/$slug/': {
      id: '/events/$slug/'
      path: '/events/$slug'
      fullPath: '/events/$slug/'
      preLoaderRoute: typeof EventsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/$slug/tickets': {
      id: '/events/$slug/tickets'
      path: '/events/$slug/tickets'
      fullPath: '/events/$slug/tickets'
      preLoaderRoute: typeof EventsSlugTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/programs': {
      id: '/events/$slug/programs'
      path: '/events/$slug/programs'
      fullPath: '/events/$slug/programs'
      preLoaderRoute: typeof EventsSlugProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/profile': {
      id: '/events/$slug/profile'
      path: '/events/$slug/profile'
      fullPath: '/events/$slug/profile'
      preLoaderRoute: typeof EventsSlugProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/$provider/callback': {
      id: '/auth_/$provider/callback'
      path: '/auth/$provider/callback'
      fullPath: '/auth/$provider/callback'
      preLoaderRoute: typeof AuthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/': {
      id: '/admin/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/admin/events/$eventId/'
      preLoaderRoute: typeof AdminEventsEventIdIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/$slug/editions/': {
      id: '/events/$slug/editions/'
      path: '/events/$slug/editions'
      fullPath: '/events/$slug/editions/'
      preLoaderRoute: typeof EventsSlugEditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/members/': {
      id: '/admin/events/$eventId/members/'
      path: '/events/$eventId/members'
      fullPath: '/admin/events/$eventId/members/'
      preLoaderRoute: typeof AdminEventsEventIdMembersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId/editions/': {
      id: '/admin/events/$eventId/editions/'
      path: '/events/$eventId/editions'
      fullPath: '/admin/events/$eventId/editions/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/$eventId/editions/$editionId/products': {
      id: '/events/$eventId/editions/$editionId/products'
      path: '/events/$eventId/editions/$editionId/products'
      fullPath: '/events/$eventId/editions/$editionId/products'
      preLoaderRoute: typeof EventsEventIdEditionsEditionIdProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId_/editions/$editionId/': {
      id: '/admin/events/$eventId_/editions/$editionId/'
      path: '/events/$eventId/editions/$editionId'
      fullPath: '/admin/events/$eventId/editions/$editionId/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId_/editions/$editionId/signatures': {
      id: '/admin/events/$eventId_/editions/$editionId/signatures'
      path: '/events/$eventId/editions/$editionId/signatures'
      fullPath: '/admin/events/$eventId/editions/$editionId/signatures'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId_/editions/$editionId/programs/': {
      id: '/admin/events/$eventId_/editions/$editionId/programs/'
      path: '/events/$eventId/editions/$editionId/programs'
      fullPath: '/admin/events/$eventId/editions/$editionId/programs/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdProgramsIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId_/editions/$editionId/tickets/': {
      id: '/admin/events/$eventId_/editions/$editionId/tickets/'
      path: '/events/$eventId/editions/$editionId/tickets'
      fullPath: '/admin/events/$eventId/editions/$editionId/tickets/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdTicketsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId_/editions/$editionId/signatures/': {
      id: '/admin/events/$eventId_/editions/$editionId/signatures/'
      path: '/'
      fullPath: '/admin/events/$eventId/editions/$editionId/signatures/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesIndexRouteImport
      parentRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesRoute
    }
    '/admin/events/$eventId_/editions/$editionId/products/': {
      id: '/admin/events/$eventId_/editions/$editionId/products/'
      path: '/events/$eventId/editions/$editionId/products'
      fullPath: '/admin/events/$eventId/editions/$editionId/products/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId_/editions/$editionId/certifications/': {
      id: '/admin/events/$eventId_/editions/$editionId/certifications/'
      path: '/events/$eventId/editions/$editionId/certifications'
      fullPath: '/admin/events/$eventId/editions/$editionId/certifications/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdCertificationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId_/editions/$editionId/programs/calendar': {
      id: '/admin/events/$eventId_/editions/$editionId/programs/calendar'
      path: '/events/$eventId/editions/$editionId/programs/calendar'
      fullPath: '/admin/events/$eventId/editions/$editionId/programs/calendar'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdProgramsCalendarLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId_/editions/$editionId/signatures/invites': {
      id: '/admin/events/$eventId_/editions/$editionId/signatures/invites'
      path: '/invites'
      fullPath: '/admin/events/$eventId/editions/$editionId/signatures/invites'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesInvitesRouteImport
      parentRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesRoute
    }
    '/admin/events/$eventId_/editions/$editionId/signatures/editor': {
      id: '/admin/events/$eventId_/editions/$editionId/signatures/editor'
      path: '/editor'
      fullPath: '/admin/events/$eventId/editions/$editionId/signatures/editor'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesEditorRouteImport
      parentRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesRoute
    }
    '/admin/events/$eventId_/editions/$editionId/certifications/editor': {
      id: '/admin/events/$eventId_/editions/$editionId/certifications/editor'
      path: '/events/$eventId/editions/$editionId/certifications/editor'
      fullPath: '/admin/events/$eventId/editions/$editionId/certifications/editor'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdCertificationsEditorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId_/editions/$editionId/callback/payment': {
      id: '/admin/events/$eventId_/editions/$editionId/callback/payment'
      path: '/events/$eventId/editions/$editionId/callback/payment'
      fullPath: '/admin/events/$eventId/editions/$editionId/callback/payment'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdCallbackPaymentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId_/editions/$editionId/programs/$programId/occurrences/': {
      id: '/admin/events/$eventId_/editions/$editionId/programs/$programId/occurrences/'
      path: '/events/$eventId/editions/$editionId/programs/$programId/occurrences'
      fullPath: '/admin/events/$eventId/editions/$editionId/programs/$programId/occurrences/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdProgramsProgramIdOccurrencesIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId_/editions/$editionId/products/$productId/variants/': {
      id: '/admin/events/$eventId_/editions/$editionId/products/$productId/variants/'
      path: '/events/$eventId/editions/$editionId/products/$productId/variants'
      fullPath: '/admin/events/$eventId/editions/$editionId/products/$productId/variants/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdProductsProductIdVariantsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminEventsEventIdEditionsEditionIdSignaturesRouteChildren {
  AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute
  AdminEventsEventIdEditionsEditionIdSignaturesInvitesRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesInvitesRoute
  AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute
}

const AdminEventsEventIdEditionsEditionIdSignaturesRouteChildren: AdminEventsEventIdEditionsEditionIdSignaturesRouteChildren =
  {
    AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute:
      AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute,
    AdminEventsEventIdEditionsEditionIdSignaturesInvitesRoute:
      AdminEventsEventIdEditionsEditionIdSignaturesInvitesRoute,
    AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute:
      AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute,
  }

const AdminEventsEventIdEditionsEditionIdSignaturesRouteWithChildren =
  AdminEventsEventIdEditionsEditionIdSignaturesRoute._addFileChildren(
    AdminEventsEventIdEditionsEditionIdSignaturesRouteChildren,
  )

interface AdminRouteChildren {
  AdminUploadsRoute: typeof AdminUploadsRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminEventsEventIdIndexLazyRoute: typeof AdminEventsEventIdIndexLazyRoute
  AdminEventsEventIdEditionsIndexRoute: typeof AdminEventsEventIdEditionsIndexRoute
  AdminEventsEventIdMembersIndexRoute: typeof AdminEventsEventIdMembersIndexRoute
  AdminEventsEventIdEditionsEditionIdSignaturesRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesRouteWithChildren
  AdminEventsEventIdEditionsEditionIdIndexRoute: typeof AdminEventsEventIdEditionsEditionIdIndexRoute
  AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute: typeof AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute
  AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute: typeof AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute
  AdminEventsEventIdEditionsEditionIdProgramsCalendarLazyRoute: typeof AdminEventsEventIdEditionsEditionIdProgramsCalendarLazyRoute
  AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute: typeof AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute
  AdminEventsEventIdEditionsEditionIdProductsIndexRoute: typeof AdminEventsEventIdEditionsEditionIdProductsIndexRoute
  AdminEventsEventIdEditionsEditionIdTicketsIndexRoute: typeof AdminEventsEventIdEditionsEditionIdTicketsIndexRoute
  AdminEventsEventIdEditionsEditionIdProgramsIndexLazyRoute: typeof AdminEventsEventIdEditionsEditionIdProgramsIndexLazyRoute
  AdminEventsEventIdEditionsEditionIdProductsProductIdVariantsIndexRoute: typeof AdminEventsEventIdEditionsEditionIdProductsProductIdVariantsIndexRoute
  AdminEventsEventIdEditionsEditionIdProgramsProgramIdOccurrencesIndexLazyRoute: typeof AdminEventsEventIdEditionsEditionIdProgramsProgramIdOccurrencesIndexLazyRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUploadsRoute: AdminUploadsRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminEventsEventIdIndexLazyRoute: AdminEventsEventIdIndexLazyRoute,
  AdminEventsEventIdEditionsIndexRoute: AdminEventsEventIdEditionsIndexRoute,
  AdminEventsEventIdMembersIndexRoute: AdminEventsEventIdMembersIndexRoute,
  AdminEventsEventIdEditionsEditionIdSignaturesRoute:
    AdminEventsEventIdEditionsEditionIdSignaturesRouteWithChildren,
  AdminEventsEventIdEditionsEditionIdIndexRoute:
    AdminEventsEventIdEditionsEditionIdIndexRoute,
  AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute:
    AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute,
  AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute:
    AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute,
  AdminEventsEventIdEditionsEditionIdProgramsCalendarLazyRoute:
    AdminEventsEventIdEditionsEditionIdProgramsCalendarLazyRoute,
  AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute:
    AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute,
  AdminEventsEventIdEditionsEditionIdProductsIndexRoute:
    AdminEventsEventIdEditionsEditionIdProductsIndexRoute,
  AdminEventsEventIdEditionsEditionIdTicketsIndexRoute:
    AdminEventsEventIdEditionsEditionIdTicketsIndexRoute,
  AdminEventsEventIdEditionsEditionIdProgramsIndexLazyRoute:
    AdminEventsEventIdEditionsEditionIdProgramsIndexLazyRoute,
  AdminEventsEventIdEditionsEditionIdProductsProductIdVariantsIndexRoute:
    AdminEventsEventIdEditionsEditionIdProductsProductIdVariantsIndexRoute,
  AdminEventsEventIdEditionsEditionIdProgramsProgramIdOccurrencesIndexLazyRoute:
    AdminEventsEventIdEditionsEditionIdProgramsProgramIdOccurrencesIndexLazyRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ComparativeRoute: ComparativeRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  TermsRoute: TermsRoute,
  SignatureRequestsFulfillRoute: SignatureRequestsFulfillRoute,
  SignaturesRevokeRoute: SignaturesRevokeRoute,
  VerifyHashRoute: VerifyHashRoute,
  EventsIndexRoute: EventsIndexRoute,
  AuthProviderCallbackRoute: AuthProviderCallbackRoute,
  EventsSlugProfileRoute: EventsSlugProfileRoute,
  EventsSlugProgramsRoute: EventsSlugProgramsRoute,
  EventsSlugTicketsRoute: EventsSlugTicketsRoute,
  EventsSlugIndexRoute: EventsSlugIndexRoute,
  EventsSlugEditionsIndexRoute: EventsSlugEditionsIndexRoute,
  EventsEventIdEditionsEditionIdProductsRoute:
    EventsEventIdEditionsEditionIdProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
