/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComparativeRouteImport } from './routes/comparative'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as EventsEventIdEditionsIndexRouteImport } from './routes/events/$eventId/editions/index'
import { Route as EventsEventIdEditionsEditionIdIndexRouteImport } from './routes/events/$eventId/editions/$editionId/index'
import { Route as AdminEventsEventIdEditionsIndexRouteImport } from './routes/admin/events/$eventId/editions/index'
import { Route as EventsEventIdEditionsEditionIdProductsRouteImport } from './routes/events/$eventId/editions/$editionId/products'
import { Route as EventsEventIdEditionsEditionIdCheckoutRouteImport } from './routes/events/$eventId/editions/$editionId/checkout'
import { Route as EventsEventIdEditionsEditionIdActivitiesIndexRouteImport } from './routes/events/$eventId/editions/$editionId/activities/index'
import { Route as AdminEventsEventIdEditionsEditionIdSignaturesIndexRouteImport } from './routes/admin/events/$eventId/editions/$editionId/signatures/index'
import { Route as AdminEventsEventIdEditionsEditionIdProductsIndexRouteImport } from './routes/admin/events/$eventId/editions/$editionId/products/index'
import { Route as AdminEventsEventIdEditionsEditionIdCheckpointsIndexRouteImport } from './routes/admin/events/$eventId/editions/$editionId/checkpoints/index'
import { Route as AdminEventsEventIdEditionsEditionIdCertificationsIndexRouteImport } from './routes/admin/events/$eventId/editions/$editionId/certifications/index'
import { Route as AdminEventsEventIdEditionsEditionIdActivitiesIndexRouteImport } from './routes/admin/events/$eventId/editions/$editionId/activities/index'
import { Route as AdminEventsEventIdEditionsEditionIdSignaturesEditorRouteImport } from './routes/admin/events/$eventId/editions/$editionId/signatures/editor'
import { Route as AdminEventsEventIdEditionsEditionIdCertificationsEditorRouteImport } from './routes/admin/events/$eventId/editions/$editionId/certifications/editor'
import { Route as AdminEventsEventIdEditionsEditionIdCallbackPaymentRouteImport } from './routes/admin/events/$eventId/editions/$editionId/callback.payment'

const ComparativeRoute = ComparativeRouteImport.update({
  id: '/comparative',
  path: '/comparative',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/events/index.lazy').then((d) => d.Route))
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/events/$eventId/index.lazy').then((d) => d.Route),
)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/admin/events/',
  path: '/admin/events/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin/events/index.lazy').then((d) => d.Route),
)
const EventsEventIdEditionsIndexRoute =
  EventsEventIdEditionsIndexRouteImport.update({
    id: '/events/$eventId/editions/',
    path: '/events/$eventId/editions/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/events/$eventId/editions/index.lazy').then((d) => d.Route),
  )
const EventsEventIdEditionsEditionIdIndexRoute =
  EventsEventIdEditionsEditionIdIndexRouteImport.update({
    id: '/events/$eventId/editions/$editionId/',
    path: '/events/$eventId/editions/$editionId/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/events/$eventId/editions/$editionId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminEventsEventIdEditionsIndexRoute =
  AdminEventsEventIdEditionsIndexRouteImport.update({
    id: '/admin/events/$eventId/editions/',
    path: '/admin/events/$eventId/editions/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/admin/events/$eventId/editions/index.lazy').then(
      (d) => d.Route,
    ),
  )
const EventsEventIdEditionsEditionIdProductsRoute =
  EventsEventIdEditionsEditionIdProductsRouteImport.update({
    id: '/events/$eventId/editions/$editionId/products',
    path: '/events/$eventId/editions/$editionId/products',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsEventIdEditionsEditionIdCheckoutRoute =
  EventsEventIdEditionsEditionIdCheckoutRouteImport.update({
    id: '/events/$eventId/editions/$editionId/checkout',
    path: '/events/$eventId/editions/$editionId/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsEventIdEditionsEditionIdActivitiesIndexRoute =
  EventsEventIdEditionsEditionIdActivitiesIndexRouteImport.update({
    id: '/events/$eventId/editions/$editionId/activities/',
    path: '/events/$eventId/editions/$editionId/activities/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/events/$eventId/editions/$editionId/activities/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute =
  AdminEventsEventIdEditionsEditionIdSignaturesIndexRouteImport.update({
    id: '/admin/events/$eventId/editions/$editionId/signatures/',
    path: '/admin/events/$eventId/editions/$editionId/signatures/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEventsEventIdEditionsEditionIdProductsIndexRoute =
  AdminEventsEventIdEditionsEditionIdProductsIndexRouteImport.update({
    id: '/admin/events/$eventId/editions/$editionId/products/',
    path: '/admin/events/$eventId/editions/$editionId/products/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/admin/events/$eventId/editions/$editionId/products/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminEventsEventIdEditionsEditionIdCheckpointsIndexRoute =
  AdminEventsEventIdEditionsEditionIdCheckpointsIndexRouteImport.update({
    id: '/admin/events/$eventId/editions/$editionId/checkpoints/',
    path: '/admin/events/$eventId/editions/$editionId/checkpoints/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute =
  AdminEventsEventIdEditionsEditionIdCertificationsIndexRouteImport.update({
    id: '/admin/events/$eventId/editions/$editionId/certifications/',
    path: '/admin/events/$eventId/editions/$editionId/certifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEventsEventIdEditionsEditionIdActivitiesIndexRoute =
  AdminEventsEventIdEditionsEditionIdActivitiesIndexRouteImport.update({
    id: '/admin/events/$eventId/editions/$editionId/activities/',
    path: '/admin/events/$eventId/editions/$editionId/activities/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/admin/events/$eventId/editions/$editionId/activities/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute =
  AdminEventsEventIdEditionsEditionIdSignaturesEditorRouteImport.update({
    id: '/admin/events/$eventId/editions/$editionId/signatures/editor',
    path: '/admin/events/$eventId/editions/$editionId/signatures/editor',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute =
  AdminEventsEventIdEditionsEditionIdCertificationsEditorRouteImport.update({
    id: '/admin/events/$eventId/editions/$editionId/certifications/editor',
    path: '/admin/events/$eventId/editions/$editionId/certifications/editor',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute =
  AdminEventsEventIdEditionsEditionIdCallbackPaymentRouteImport.update({
    id: '/admin/events/$eventId/editions/$editionId/callback/payment',
    path: '/admin/events/$eventId/editions/$editionId/callback/payment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comparative': typeof ComparativeRoute
  '/events/': typeof EventsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/events/$eventId/editions/': typeof EventsEventIdEditionsIndexRoute
  '/events/$eventId/editions/$editionId/checkout': typeof EventsEventIdEditionsEditionIdCheckoutRoute
  '/events/$eventId/editions/$editionId/products': typeof EventsEventIdEditionsEditionIdProductsRoute
  '/admin/events/$eventId/editions/': typeof AdminEventsEventIdEditionsIndexRoute
  '/events/$eventId/editions/$editionId/': typeof EventsEventIdEditionsEditionIdIndexRoute
  '/events/$eventId/editions/$editionId/activities/': typeof EventsEventIdEditionsEditionIdActivitiesIndexRoute
  '/admin/events/$eventId/editions/$editionId/callback/payment': typeof AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute
  '/admin/events/$eventId/editions/$editionId/certifications/editor': typeof AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute
  '/admin/events/$eventId/editions/$editionId/signatures/editor': typeof AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute
  '/admin/events/$eventId/editions/$editionId/activities/': typeof AdminEventsEventIdEditionsEditionIdActivitiesIndexRoute
  '/admin/events/$eventId/editions/$editionId/certifications/': typeof AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute
  '/admin/events/$eventId/editions/$editionId/checkpoints/': typeof AdminEventsEventIdEditionsEditionIdCheckpointsIndexRoute
  '/admin/events/$eventId/editions/$editionId/products/': typeof AdminEventsEventIdEditionsEditionIdProductsIndexRoute
  '/admin/events/$eventId/editions/$editionId/signatures/': typeof AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comparative': typeof ComparativeRoute
  '/events': typeof EventsIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/events/$eventId/editions': typeof EventsEventIdEditionsIndexRoute
  '/events/$eventId/editions/$editionId/checkout': typeof EventsEventIdEditionsEditionIdCheckoutRoute
  '/events/$eventId/editions/$editionId/products': typeof EventsEventIdEditionsEditionIdProductsRoute
  '/admin/events/$eventId/editions': typeof AdminEventsEventIdEditionsIndexRoute
  '/events/$eventId/editions/$editionId': typeof EventsEventIdEditionsEditionIdIndexRoute
  '/events/$eventId/editions/$editionId/activities': typeof EventsEventIdEditionsEditionIdActivitiesIndexRoute
  '/admin/events/$eventId/editions/$editionId/callback/payment': typeof AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute
  '/admin/events/$eventId/editions/$editionId/certifications/editor': typeof AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute
  '/admin/events/$eventId/editions/$editionId/signatures/editor': typeof AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute
  '/admin/events/$eventId/editions/$editionId/activities': typeof AdminEventsEventIdEditionsEditionIdActivitiesIndexRoute
  '/admin/events/$eventId/editions/$editionId/certifications': typeof AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute
  '/admin/events/$eventId/editions/$editionId/checkpoints': typeof AdminEventsEventIdEditionsEditionIdCheckpointsIndexRoute
  '/admin/events/$eventId/editions/$editionId/products': typeof AdminEventsEventIdEditionsEditionIdProductsIndexRoute
  '/admin/events/$eventId/editions/$editionId/signatures': typeof AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comparative': typeof ComparativeRoute
  '/events/': typeof EventsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/events/$eventId/editions/': typeof EventsEventIdEditionsIndexRoute
  '/events/$eventId/editions/$editionId/checkout': typeof EventsEventIdEditionsEditionIdCheckoutRoute
  '/events/$eventId/editions/$editionId/products': typeof EventsEventIdEditionsEditionIdProductsRoute
  '/admin/events/$eventId/editions/': typeof AdminEventsEventIdEditionsIndexRoute
  '/events/$eventId/editions/$editionId/': typeof EventsEventIdEditionsEditionIdIndexRoute
  '/events/$eventId/editions/$editionId/activities/': typeof EventsEventIdEditionsEditionIdActivitiesIndexRoute
  '/admin/events/$eventId/editions/$editionId/callback/payment': typeof AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute
  '/admin/events/$eventId/editions/$editionId/certifications/editor': typeof AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute
  '/admin/events/$eventId/editions/$editionId/signatures/editor': typeof AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute
  '/admin/events/$eventId/editions/$editionId/activities/': typeof AdminEventsEventIdEditionsEditionIdActivitiesIndexRoute
  '/admin/events/$eventId/editions/$editionId/certifications/': typeof AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute
  '/admin/events/$eventId/editions/$editionId/checkpoints/': typeof AdminEventsEventIdEditionsEditionIdCheckpointsIndexRoute
  '/admin/events/$eventId/editions/$editionId/products/': typeof AdminEventsEventIdEditionsEditionIdProductsIndexRoute
  '/admin/events/$eventId/editions/$editionId/signatures/': typeof AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comparative'
    | '/events/'
    | '/admin/events/'
    | '/events/$eventId/'
    | '/events/$eventId/editions/'
    | '/events/$eventId/editions/$editionId/checkout'
    | '/events/$eventId/editions/$editionId/products'
    | '/admin/events/$eventId/editions/'
    | '/events/$eventId/editions/$editionId/'
    | '/events/$eventId/editions/$editionId/activities/'
    | '/admin/events/$eventId/editions/$editionId/callback/payment'
    | '/admin/events/$eventId/editions/$editionId/certifications/editor'
    | '/admin/events/$eventId/editions/$editionId/signatures/editor'
    | '/admin/events/$eventId/editions/$editionId/activities/'
    | '/admin/events/$eventId/editions/$editionId/certifications/'
    | '/admin/events/$eventId/editions/$editionId/checkpoints/'
    | '/admin/events/$eventId/editions/$editionId/products/'
    | '/admin/events/$eventId/editions/$editionId/signatures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comparative'
    | '/events'
    | '/admin/events'
    | '/events/$eventId'
    | '/events/$eventId/editions'
    | '/events/$eventId/editions/$editionId/checkout'
    | '/events/$eventId/editions/$editionId/products'
    | '/admin/events/$eventId/editions'
    | '/events/$eventId/editions/$editionId'
    | '/events/$eventId/editions/$editionId/activities'
    | '/admin/events/$eventId/editions/$editionId/callback/payment'
    | '/admin/events/$eventId/editions/$editionId/certifications/editor'
    | '/admin/events/$eventId/editions/$editionId/signatures/editor'
    | '/admin/events/$eventId/editions/$editionId/activities'
    | '/admin/events/$eventId/editions/$editionId/certifications'
    | '/admin/events/$eventId/editions/$editionId/checkpoints'
    | '/admin/events/$eventId/editions/$editionId/products'
    | '/admin/events/$eventId/editions/$editionId/signatures'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/comparative'
    | '/events/'
    | '/admin/events/'
    | '/events/$eventId/'
    | '/events/$eventId/editions/'
    | '/events/$eventId/editions/$editionId/checkout'
    | '/events/$eventId/editions/$editionId/products'
    | '/admin/events/$eventId/editions/'
    | '/events/$eventId/editions/$editionId/'
    | '/events/$eventId/editions/$editionId/activities/'
    | '/admin/events/$eventId/editions/$editionId/callback/payment'
    | '/admin/events/$eventId/editions/$editionId/certifications/editor'
    | '/admin/events/$eventId/editions/$editionId/signatures/editor'
    | '/admin/events/$eventId/editions/$editionId/activities/'
    | '/admin/events/$eventId/editions/$editionId/certifications/'
    | '/admin/events/$eventId/editions/$editionId/checkpoints/'
    | '/admin/events/$eventId/editions/$editionId/products/'
    | '/admin/events/$eventId/editions/$editionId/signatures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ComparativeRoute: typeof ComparativeRoute
  EventsIndexRoute: typeof EventsIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
  EventsEventIdEditionsIndexRoute: typeof EventsEventIdEditionsIndexRoute
  EventsEventIdEditionsEditionIdCheckoutRoute: typeof EventsEventIdEditionsEditionIdCheckoutRoute
  EventsEventIdEditionsEditionIdProductsRoute: typeof EventsEventIdEditionsEditionIdProductsRoute
  AdminEventsEventIdEditionsIndexRoute: typeof AdminEventsEventIdEditionsIndexRoute
  EventsEventIdEditionsEditionIdIndexRoute: typeof EventsEventIdEditionsEditionIdIndexRoute
  EventsEventIdEditionsEditionIdActivitiesIndexRoute: typeof EventsEventIdEditionsEditionIdActivitiesIndexRoute
  AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute: typeof AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute
  AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute: typeof AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute
  AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute
  AdminEventsEventIdEditionsEditionIdActivitiesIndexRoute: typeof AdminEventsEventIdEditionsEditionIdActivitiesIndexRoute
  AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute: typeof AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute
  AdminEventsEventIdEditionsEditionIdCheckpointsIndexRoute: typeof AdminEventsEventIdEditionsEditionIdCheckpointsIndexRoute
  AdminEventsEventIdEditionsEditionIdProductsIndexRoute: typeof AdminEventsEventIdEditionsEditionIdProductsIndexRoute
  AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/comparative': {
      id: '/comparative'
      path: '/comparative'
      fullPath: '/comparative'
      preLoaderRoute: typeof ComparativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/admin/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/editions/': {
      id: '/events/$eventId/editions/'
      path: '/events/$eventId/editions'
      fullPath: '/events/$eventId/editions/'
      preLoaderRoute: typeof EventsEventIdEditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/editions/$editionId/': {
      id: '/events/$eventId/editions/$editionId/'
      path: '/events/$eventId/editions/$editionId'
      fullPath: '/events/$eventId/editions/$editionId/'
      preLoaderRoute: typeof EventsEventIdEditionsEditionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/editions/': {
      id: '/admin/events/$eventId/editions/'
      path: '/admin/events/$eventId/editions'
      fullPath: '/admin/events/$eventId/editions/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/editions/$editionId/products': {
      id: '/events/$eventId/editions/$editionId/products'
      path: '/events/$eventId/editions/$editionId/products'
      fullPath: '/events/$eventId/editions/$editionId/products'
      preLoaderRoute: typeof EventsEventIdEditionsEditionIdProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/editions/$editionId/checkout': {
      id: '/events/$eventId/editions/$editionId/checkout'
      path: '/events/$eventId/editions/$editionId/checkout'
      fullPath: '/events/$eventId/editions/$editionId/checkout'
      preLoaderRoute: typeof EventsEventIdEditionsEditionIdCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/editions/$editionId/activities/': {
      id: '/events/$eventId/editions/$editionId/activities/'
      path: '/events/$eventId/editions/$editionId/activities'
      fullPath: '/events/$eventId/editions/$editionId/activities/'
      preLoaderRoute: typeof EventsEventIdEditionsEditionIdActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/editions/$editionId/signatures/': {
      id: '/admin/events/$eventId/editions/$editionId/signatures/'
      path: '/admin/events/$eventId/editions/$editionId/signatures'
      fullPath: '/admin/events/$eventId/editions/$editionId/signatures/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/editions/$editionId/products/': {
      id: '/admin/events/$eventId/editions/$editionId/products/'
      path: '/admin/events/$eventId/editions/$editionId/products'
      fullPath: '/admin/events/$eventId/editions/$editionId/products/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/editions/$editionId/checkpoints/': {
      id: '/admin/events/$eventId/editions/$editionId/checkpoints/'
      path: '/admin/events/$eventId/editions/$editionId/checkpoints'
      fullPath: '/admin/events/$eventId/editions/$editionId/checkpoints/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdCheckpointsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/editions/$editionId/certifications/': {
      id: '/admin/events/$eventId/editions/$editionId/certifications/'
      path: '/admin/events/$eventId/editions/$editionId/certifications'
      fullPath: '/admin/events/$eventId/editions/$editionId/certifications/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdCertificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/editions/$editionId/activities/': {
      id: '/admin/events/$eventId/editions/$editionId/activities/'
      path: '/admin/events/$eventId/editions/$editionId/activities'
      fullPath: '/admin/events/$eventId/editions/$editionId/activities/'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/editions/$editionId/signatures/editor': {
      id: '/admin/events/$eventId/editions/$editionId/signatures/editor'
      path: '/admin/events/$eventId/editions/$editionId/signatures/editor'
      fullPath: '/admin/events/$eventId/editions/$editionId/signatures/editor'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdSignaturesEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/editions/$editionId/certifications/editor': {
      id: '/admin/events/$eventId/editions/$editionId/certifications/editor'
      path: '/admin/events/$eventId/editions/$editionId/certifications/editor'
      fullPath: '/admin/events/$eventId/editions/$editionId/certifications/editor'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdCertificationsEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/editions/$editionId/callback/payment': {
      id: '/admin/events/$eventId/editions/$editionId/callback/payment'
      path: '/admin/events/$eventId/editions/$editionId/callback/payment'
      fullPath: '/admin/events/$eventId/editions/$editionId/callback/payment'
      preLoaderRoute: typeof AdminEventsEventIdEditionsEditionIdCallbackPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ComparativeRoute: ComparativeRoute,
  EventsIndexRoute: EventsIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
  EventsEventIdEditionsIndexRoute: EventsEventIdEditionsIndexRoute,
  EventsEventIdEditionsEditionIdCheckoutRoute:
    EventsEventIdEditionsEditionIdCheckoutRoute,
  EventsEventIdEditionsEditionIdProductsRoute:
    EventsEventIdEditionsEditionIdProductsRoute,
  AdminEventsEventIdEditionsIndexRoute: AdminEventsEventIdEditionsIndexRoute,
  EventsEventIdEditionsEditionIdIndexRoute:
    EventsEventIdEditionsEditionIdIndexRoute,
  EventsEventIdEditionsEditionIdActivitiesIndexRoute:
    EventsEventIdEditionsEditionIdActivitiesIndexRoute,
  AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute:
    AdminEventsEventIdEditionsEditionIdCallbackPaymentRoute,
  AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute:
    AdminEventsEventIdEditionsEditionIdCertificationsEditorRoute,
  AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute:
    AdminEventsEventIdEditionsEditionIdSignaturesEditorRoute,
  AdminEventsEventIdEditionsEditionIdActivitiesIndexRoute:
    AdminEventsEventIdEditionsEditionIdActivitiesIndexRoute,
  AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute:
    AdminEventsEventIdEditionsEditionIdCertificationsIndexRoute,
  AdminEventsEventIdEditionsEditionIdCheckpointsIndexRoute:
    AdminEventsEventIdEditionsEditionIdCheckpointsIndexRoute,
  AdminEventsEventIdEditionsEditionIdProductsIndexRoute:
    AdminEventsEventIdEditionsEditionIdProductsIndexRoute,
  AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute:
    AdminEventsEventIdEditionsEditionIdSignaturesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
