name: Build, Publish & Deploy

on:
  push:
    tags:
      - '*/v*'

defaults:
  run:
    shell: bash

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - name: Set up Docker
        run: curl -fsSL https://get.docker.com | sh
      - name: Build & publish via Dagger
        uses: https://github.com/dagger/dagger-for-github@v6
        env:
          FJ_TOKEN: ${{ secrets.FJ_TOKEN }}
        with:
          version: "v0.21.7"
          verb: call
          module: .dagger
          args: publish --source=. --registry-username=${{ secrets.FJ_USER }} --registry-password=env:FJ_TOKEN --tag=${{ github.ref_name }}