name: Trivy Scan

on:
  pull_request:
    branches:
      - main

jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trivy scan
        uses: https://github.com/aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          severity: LOW,MEDIUM,HIGH,CRITICAL
          scanners: vuln,secret,misconfig
          exit-code: '1'