/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminNamespaceIDRouteImport } from './routes/admin/$namespaceID'
import { Route as AdminNamespaceIDIndexRouteImport } from './routes/admin/$namespaceID/index'
import { Route as AdminNamespaceIDKeysRouteImport } from './routes/admin/$namespaceID/keys'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNamespaceIDRoute = AdminNamespaceIDRouteImport.update({
  id: '/$namespaceID',
  path: '/$namespaceID',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNamespaceIDIndexRoute = AdminNamespaceIDIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminNamespaceIDRoute,
} as any)
const AdminNamespaceIDKeysRoute = AdminNamespaceIDKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AdminNamespaceIDRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/$namespaceID': typeof AdminNamespaceIDRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/$namespaceID/keys': typeof AdminNamespaceIDKeysRoute
  '/admin/$namespaceID/': typeof AdminNamespaceIDIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/$namespaceID/keys': typeof AdminNamespaceIDKeysRoute
  '/admin/$namespaceID': typeof AdminNamespaceIDIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/$namespaceID': typeof AdminNamespaceIDRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/$namespaceID/keys': typeof AdminNamespaceIDKeysRoute
  '/admin/$namespaceID/': typeof AdminNamespaceIDIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/$namespaceID'
    | '/admin/'
    | '/admin/$namespaceID/keys'
    | '/admin/$namespaceID/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/admin/$namespaceID/keys' | '/admin/$namespaceID'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/$namespaceID'
    | '/admin/'
    | '/admin/$namespaceID/keys'
    | '/admin/$namespaceID/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$namespaceID': {
      id: '/admin/$namespaceID'
      path: '/$namespaceID'
      fullPath: '/admin/$namespaceID'
      preLoaderRoute: typeof AdminNamespaceIDRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$namespaceID/': {
      id: '/admin/$namespaceID/'
      path: '/'
      fullPath: '/admin/$namespaceID/'
      preLoaderRoute: typeof AdminNamespaceIDIndexRouteImport
      parentRoute: typeof AdminNamespaceIDRoute
    }
    '/admin/$namespaceID/keys': {
      id: '/admin/$namespaceID/keys'
      path: '/keys'
      fullPath: '/admin/$namespaceID/keys'
      preLoaderRoute: typeof AdminNamespaceIDKeysRouteImport
      parentRoute: typeof AdminNamespaceIDRoute
    }
  }
}

interface AdminNamespaceIDRouteChildren {
  AdminNamespaceIDKeysRoute: typeof AdminNamespaceIDKeysRoute
  AdminNamespaceIDIndexRoute: typeof AdminNamespaceIDIndexRoute
}

const AdminNamespaceIDRouteChildren: AdminNamespaceIDRouteChildren = {
  AdminNamespaceIDKeysRoute: AdminNamespaceIDKeysRoute,
  AdminNamespaceIDIndexRoute: AdminNamespaceIDIndexRoute,
}

const AdminNamespaceIDRouteWithChildren =
  AdminNamespaceIDRoute._addFileChildren(AdminNamespaceIDRouteChildren)

interface AdminRouteChildren {
  AdminNamespaceIDRoute: typeof AdminNamespaceIDRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminNamespaceIDRoute: AdminNamespaceIDRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
