// Code generated by tygo. DO NOT EDIT.

//////////
// source: actors.go

export type AuthMethod = string;
export const PasswordAuthMethod: AuthMethod = "password";
export const ApiKeyAuthMethod: AuthMethod = "api_key";
export const GoogleAuthMethod: AuthMethod = "google_auth";
export const GithubAuthMethod: AuthMethod = "github_auth";
export type ActorType = string;
export const HumanActorType: ActorType = "human";
export const ServiceActorType: ActorType = "service";
export const MachineActorType: ActorType = "machine";
export interface Actor {
  id: string;
  project_id?: string;
  auth_method: AuthMethod;
  verified_at?: string;
  password_hash?: string;
  email?: string;
  type: ActorType;
  metadata?: any /* json.RawMessage */;
  created_at: string;
  updated_at: string;
  deleted_at?: string;
}
export interface ActorProfile {
  actor_id: string;
  profile: any /* json.RawMessage */;
  updated_at: string;
}
export type OAuthProvider = string;
export const GoogleIdentityProvider: OAuthProvider = "google";
export const GithubIdentityProvider: OAuthProvider = "github";
export interface ActorExternalIdentities {
  id: string;
  actor_id: string;
  provider: OAuthProvider;
  subject: string;
  email?: string;
  token_expires_at?: string;
  created_at: string;
  updated_at: string;
}

//////////
// source: api_keys.go

export interface ApiKeys {
  id: string;
  actor_id: string;
  project_id?: string;
  name: string;
  key_prefix: string;
  key_hash: string;
  metadata: any /* json.RawMessage */;
  expires_at: string;
  revoked_at: string;
  last_used_at: string;
  created_at: string;
}

//////////
// source: auth.go

export interface AccessSub {
  id: string;
  project_id?: string;
  email?: string;
  type: ActorType;
  capabilities: any /* json.RawMessage */;
  metadata: any /* json.RawMessage */;
}
export interface AccessClaims {
  sub: AccessSub;
  RegisteredClaims: any /* jwt.RegisteredClaims */;
}
export interface RefreshSub {
  access_jti: string;
}
export interface RefreshClaims {
  sub: RefreshSub;
  RegisteredClaims: any /* jwt.RegisteredClaims */;
}
export interface VerificationSub {
  subject: string;
}
export interface VerificationClaims {
  sub: VerificationSub;
  RegisteredClaims: any /* jwt.RegisteredClaims */;
}
export interface ResetPasswordSub {
  subject: string;
  project_id?: string;
}
export interface ResetPasswordClaims {
  sub: ResetPasswordSub;
  RegisteredClaims: any /* jwt.RegisteredClaims */;
}
export interface IDXRegisterRequest {
  email: string;
  password: string;
}
export interface IDXRegisterInput {
  Email: string;
  Password: string;
}
export interface IDXLoginRequest {
  email: string;
  password: string;
}
export interface IDXLoginInput {
  email: string;
  password: string;
}
export interface SetupInput {
  Email: string;
  Password: string;
}
export interface LogoutInput {
  AccessToken: string;
  RefreshToken: string;
}
export interface UserTokensOutput {
  access_token: string;
  refresh_token: string;
  access_expires_at: string;
  refresh_expires_at: string;
  domain: string;
}
export interface UserTokensResponse {
  access_token_string: string;
  refresh_token_string: string;
  access_expires_at: string;
  refresh_expires_at: string;
  domain: string;
}
export interface RefreshInput {
  refresh_cookie: string;
  agent: string;
  ip: string;
}

//////////
// source: blacklist.go

export type BlacklistEntryType = string;
export const BlacklistEntryTypeActor: BlacklistEntryType = "actor";
export const BlacklistEntryTypeToken: BlacklistEntryType = "token";
export const BlacklistEntryTypeApiKey: BlacklistEntryType = "api_key";
export const BlacklistEntryTypeEmail: BlacklistEntryType = "email";
export const BlacklistEntryTypeIP: BlacklistEntryType = "ip";
export interface BlacklistEntry {
  id: string;
  created_by_actor_id?: string;
  project_id?: string;
  type: BlacklistEntryType;
  target: string;
  reason?: string;
  metadata?: any /* json.RawMessage */;
  created_at: string;
  expires_at?: string;
}

//////////
// source: crypto_keys.go

export type CryptoKeyType = string;
export const EncryptionCryptoKeyType: CryptoKeyType = "encryption";
export const SigningCryptoKeyType: CryptoKeyType = "signing";
export type CryptoKeyStatus = string;
export const CryptoKeyStatusActive: CryptoKeyStatus = "active";
export const CryptoKeyStatusRetiring: CryptoKeyStatus = "retiring";
export const CryptoKeyStatusRetired: CryptoKeyStatus = "retired";
export const CryptoKeyStatusRevoked: CryptoKeyStatus = "revoked";
export interface CryptoKey {
  id: string;
  project_id?: string;
  type: CryptoKeyType;
  status: CryptoKeyStatus;
  public_key: string;
  algorithm: string;
  metadata: any /* json.RawMessage */;
  active: boolean;
  created_at: string;
  rotated_at?: string;
  expires_at?: string;
}

//////////
// source: organizations.go

export interface Organizations {
  id: string;
  owner_id: string;
  name: string;
  slug: string;
  metadata: any /* json.RawMessage */;
  created_at: string;
  deleted_at: string;
}
export type OrganizationRole = string;
export const OrganizationRoleMember: OrganizationRole = "member";
export const OrganizationRoleAdmin: OrganizationRole = "admin";
export const OrganizationRoleOwner: OrganizationRole = "owner";
export interface OrganizationMembers {
  organization_id: string;
  actor_id: string;
  role: OrganizationRole;
  metadata: any /* json.RawMessage */;
  joined_at: string;
}

//////////
// source: platform_roles.go

export type PlatformRole = string;
export const PlatformRoleSupport: PlatformRole = "support";
export const PlatformRoleAdmin: PlatformRole = "admin";
export const PlatformRoleSuperAdmin: PlatformRole = "super_admin";
export interface PlatformRoleRelation {
  actor_id: string;
  role: PlatformRole;
  metadata?: any /* json.RawMessage */;
  created_at: string;
}

//////////
// source: projects.go

export interface Project {
  id: string;
  organization_id?: string;
  owner_id: string;
  name: string;
  slug: string;
  domain?: string;
  domain_verified_at?: string;
  metadata: any /* json.RawMessage */;
  created_at?: string;
  deleted_at?: string;
}
export interface ProjectDomainChallenges {
  id: string;
  project_id: string;
  domain: string;
  token: string;
  created_at: string;
  expires_at: string;
  verified_at: string;
}
export type ProjectRole = string;
export const ProjectRoleMember: ProjectRole = "member";
export const ProjectRoleAdmin: ProjectRole = "admin";
export const ProjectRoleOwner: ProjectRole = "owner";
export interface ProjectMembers {
  project_id: string;
  actor_id: string;
  role: ProjectRole;
  metadata: any /* json.RawMessage */;
  joined_at?: string;
}
export interface ProjectOAuthProviders {
  id: string;
  project_id: string;
  provider: OAuthProvider;
  client_id: string;
  encrypted_client_secret: string;
  scopes: string[];
  enabled: boolean;
  created_at: string;
  updated_at: string;
}
