/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Payssage API
 * Payssage is TrieOH's payments service: wallet and seller management,
 * payment intents (checkout), payment-provider OAuth connections
 * (MercadoPago), and the webhook pipeline that fans provider events out
 * to tenant webhook endpoints.
 *
 * ## Authentication
 *
 * All endpoints except `POST /webhooks/{provider}` (provider calls it)
 * and `GET /providers/{provider}/callback` (browser redirect target)
 * require a bearer JWT issued by IdentityX:
 *
 * | Scheme | Header |
 * |---|---|
 * | Bearer JWT | `Authorization: Bearer <token>` |
 *
 * ## Response envelope
 *
 * Every JSON response is the `fun.Response` envelope:
 *
 * ```json
 * {
 *   "code": 200,
 *   "message": "",
 *   "data": { "...": "operation payload" },
 *   "error": null,
 *   "pagination": null,
 *   "timestamp": "2026-01-01T12:00:00Z",
 *   "module": "Payssage"
 * }
 * ```
 *
 * - Success: `data` carries the payload. Errors: `error` carries an
 *   `AppError` — `{ "code", "message", "fields", "meta" }`.
 * - `pagination` is reserved for paged list endpoints (currently
 *   unused by Payssage routes).
 *
 * ## Error codes → HTTP status
 *
 * The `error.code` sentinel maps to the HTTP status:
 *
 * | code | status |
 * |---|---|
 * | `BAD_REQUEST`, `VALIDATION_ERROR` | 400 |
 * | `UNAUTHORIZED` | 401 |
 * | `PAYMENT_REQUIRED` | 402 |
 * | `FORBIDDEN` | 403 |
 * | `NOT_FOUND` | 404 |
 * | `METHOD_NOT_ALLOWED` | 405 |
 * | `CONFLICT` | 409 |
 * | `UNPROCESSABLE_ENTITY` | 422 |
 * | `TOO_MANY_REQUESTS` | 429 |
 * | `INTERNAL_ERROR` | 500 |
 * | `NOT_IMPLEMENTED` | 501 |
 * | `BAD_GATEWAY` | 502 |
 * | `SERVICE_UNAVAILABLE` | 503 |
 *
 * ## Amounts
 *
 * All monetary amounts are `amount_cents` / `price_cents` — integer
 * cents (`int64`), never floats.
 *
 * ## Webhooks for tenants
 *
 * When a provider event arrives at `POST /webhooks/{provider}`, Payssage
 * records a webhook event and dispatches one delivery per webhook
 * endpoint registered on the event's wallet. Each delivery POSTs to the
 * endpoint URL:
 *
 * | Header | Value |
 * |---|---|
 * | `Content-Type` | `application/json` |
 * | `X-Payssage-Signature` | `hex( HMAC-SHA256( payload, endpoint.secret ) )` |
 * | `X-Payssage-Event-Type` | Normalized event type (e.g. `payment.succeeded`) |
 *
 * The body is a JSON envelope carrying the raw provider event payload
 * plus the correlation key — the Payssage `intent_id` (never a
 * provider-specific id):
 *
 * ```json
 * {
 *   "intent_id": "...", "wallet_id": "...", "provider": "mercadopago",
 *   "external_id": "<mp_payment_id>", "event_type": "payment.succeeded",
 *   "payload": { ...raw provider payload... }
 * }
 * ```
 *
 * Verify the signature before trusting the payload. Deliveries are
 * retried up to **5 attempts** (any 2xx counts as success; request
 * failures and non-2xx count as failed attempts), after which the
 * delivery is marked `failed`.
 *
 * ## Rate limits
 *
 * The harness applies a fixed rate limit of 400 requests/second with a
 * burst of 20, keyed by client IP. Exceeded requests receive
 * `429 TOO_MANY_REQUESTS`.
 *
 * OpenAPI spec version: 0.1.0
 */
import type {
  AddOrganizationMemberRequest,
  BadRequestResponse,
  BindCollectorRequest,
  Collector,
  ConflictResponse,
  ConnectRequest,
  CreateIntentRequest,
  CreateOrganizationRequest,
  CreateWalletRequest,
  CreateWebhookEndpointRequest,
  ForbiddenResponse,
  GetHealth200,
  HardCreateIntentRequest,
  Intent,
  InternalServerErrorResponse,
  NotFoundResponse,
  Organization,
  OrganizationMember,
  ProviderCallbackParams,
  ReceiveWebhookBody,
  RemoveOrganizationMemberRequest,
  RevokeRequest,
  Seller,
  SetFeeBPSRequest,
  SetSandboxRequest,
  UnauthorizedResponse,
  Uuid,
  Wallet,
  WebhookDelivery,
  WebhookEndpoint,
  WebhookEvent
} from './schemas';

import { customInstance } from '../../api-client/src/orval-mutator';
export type getOpenAPISpecResponse200 = {
  data: string
  status: 200
}

export type getOpenAPISpecResponseSuccess = (getOpenAPISpecResponse200) & {
  headers: Headers;
};
;

export type getOpenAPISpecResponse = (getOpenAPISpecResponseSuccess)

export const getGetOpenAPISpecUrl = () => {




  return `/docs/openapi.yml`
}

/**
 * Returns this service's OpenAPI 3.1 specification in YAML — the
 * same content as api/<svc>/api-spec.yml, embedded and served by
 * the harness. Docs tooling fetches this URL to render the API
 * reference. Public.
 * @summary Get the OpenAPI specification
 */
export const getOpenAPISpec = async ( options?: Parameters<typeof customInstance>[1]): Promise<getOpenAPISpecResponse> => {

  return customInstance<getOpenAPISpecResponse>(getGetOpenAPISpecUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type getHealthResponse200 = {
  data: GetHealth200
  status: 200
}

export type getHealthResponseSuccess = (getHealthResponse200) & {
  headers: Headers;
};
;

export type getHealthResponse = (getHealthResponseSuccess)

export const getGetHealthUrl = () => {




  return `/health`
}

/**
 * Harness-owned liveness probe. Public.
 * @summary Health check
 */
export const getHealth = async ( options?: Parameters<typeof customInstance>[1]): Promise<getHealthResponse> => {

  return customInstance<getHealthResponse>(getGetHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type listOrganizationsResponse200 = {
  data: Organization[]
  status: 200
}

export type listOrganizationsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listOrganizationsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listOrganizationsResponseSuccess = (listOrganizationsResponse200) & {
  headers: Headers;
};
export type listOrganizationsResponseError = (listOrganizationsResponse401 | listOrganizationsResponse500) & {
  headers: Headers;
};

export type listOrganizationsResponse = (listOrganizationsResponseSuccess | listOrganizationsResponseError)

export const getListOrganizationsUrl = () => {




  return `/organizations`
}

/**
 * Lists the organizations the authenticated actor belongs to.
 * @summary List your organizations
 */
export const listOrganizations = async ( options?: Parameters<typeof customInstance>[1]): Promise<listOrganizationsResponse> => {

  return customInstance<listOrganizationsResponse>(getListOrganizationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type createOrganizationResponse201 = {
  data: Organization
  status: 201
}

export type createOrganizationResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createOrganizationResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createOrganizationResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type createOrganizationResponseSuccess = (createOrganizationResponse201) & {
  headers: Headers;
};
export type createOrganizationResponseError = (createOrganizationResponse400 | createOrganizationResponse401 | createOrganizationResponse500) & {
  headers: Headers;
};

export type createOrganizationResponse = (createOrganizationResponseSuccess | createOrganizationResponseError)

export const getCreateOrganizationUrl = () => {




  return `/organizations`
}

/**
 * Creates an organization owned by the authenticated actor.
 * @summary Create an organization
 */
export const createOrganization = async (createOrganizationRequest: CreateOrganizationRequest, options?: Parameters<typeof customInstance>[1]): Promise<createOrganizationResponse> => {

  return customInstance<createOrganizationResponse>(getCreateOrganizationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOrganizationRequest)
  }
);}



export type listOrganizationMembersResponse200 = {
  data: OrganizationMember[]
  status: 200
}

export type listOrganizationMembersResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listOrganizationMembersResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type listOrganizationMembersResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type listOrganizationMembersResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listOrganizationMembersResponseSuccess = (listOrganizationMembersResponse200) & {
  headers: Headers;
};
export type listOrganizationMembersResponseError = (listOrganizationMembersResponse401 | listOrganizationMembersResponse403 | listOrganizationMembersResponse404 | listOrganizationMembersResponse500) & {
  headers: Headers;
};

export type listOrganizationMembersResponse = (listOrganizationMembersResponseSuccess | listOrganizationMembersResponseError)

export const getListOrganizationMembersUrl = (organizationId: string,) => {




  return `/organizations/${organizationId}/members`
}

/**
 * Lists the members of an organization. The actor must be a member
 * of the organization.
 * @summary List organization members
 */
export const listOrganizationMembers = async (organizationId: string, options?: Parameters<typeof customInstance>[1]): Promise<listOrganizationMembersResponse> => {

  return customInstance<listOrganizationMembersResponse>(getListOrganizationMembersUrl(organizationId),
  {
    ...options,
    method: 'GET'


  }
);}



export type addOrganizationMemberResponse201 = {
  data: void
  status: 201
}

export type addOrganizationMemberResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type addOrganizationMemberResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type addOrganizationMemberResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type addOrganizationMemberResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type addOrganizationMemberResponse409 = {
  data: ConflictResponse
  status: 409
}

export type addOrganizationMemberResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type addOrganizationMemberResponseSuccess = (addOrganizationMemberResponse201) & {
  headers: Headers;
};
export type addOrganizationMemberResponseError = (addOrganizationMemberResponse400 | addOrganizationMemberResponse401 | addOrganizationMemberResponse403 | addOrganizationMemberResponse404 | addOrganizationMemberResponse409 | addOrganizationMemberResponse500) & {
  headers: Headers;
};

export type addOrganizationMemberResponse = (addOrganizationMemberResponseSuccess | addOrganizationMemberResponseError)

export const getAddOrganizationMemberUrl = (organizationId: string,) => {




  return `/organizations/${organizationId}/members`
}

/**
 * Adds an existing actor (by email) to the organization with the
 * given role. The actor must be an admin or owner.
 * @summary Add an organization member
 */
export const addOrganizationMember = async (organizationId: string,
    addOrganizationMemberRequest: AddOrganizationMemberRequest, options?: Parameters<typeof customInstance>[1]): Promise<addOrganizationMemberResponse> => {

  return customInstance<addOrganizationMemberResponse>(getAddOrganizationMemberUrl(organizationId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addOrganizationMemberRequest)
  }
);}



export type removeOrganizationMemberResponse200 = {
  data: unknown
  status: 200
}

export type removeOrganizationMemberResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type removeOrganizationMemberResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type removeOrganizationMemberResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type removeOrganizationMemberResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type removeOrganizationMemberResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type removeOrganizationMemberResponseSuccess = (removeOrganizationMemberResponse200) & {
  headers: Headers;
};
export type removeOrganizationMemberResponseError = (removeOrganizationMemberResponse400 | removeOrganizationMemberResponse401 | removeOrganizationMemberResponse403 | removeOrganizationMemberResponse404 | removeOrganizationMemberResponse500) & {
  headers: Headers;
};

export type removeOrganizationMemberResponse = (removeOrganizationMemberResponseSuccess | removeOrganizationMemberResponseError)

export const getRemoveOrganizationMemberUrl = (organizationId: string,) => {




  return `/organizations/${organizationId}/members`
}

/**
 * Removes an actor (by email) from the organization. The actor must
 * be an admin or owner.
 * @summary Remove an organization member
 */
export const removeOrganizationMember = async (organizationId: string,
    removeOrganizationMemberRequest: RemoveOrganizationMemberRequest, options?: Parameters<typeof customInstance>[1]): Promise<removeOrganizationMemberResponse> => {

  return customInstance<removeOrganizationMemberResponse>(getRemoveOrganizationMemberUrl(organizationId),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(removeOrganizationMemberRequest)
  }
);}



export type getOrganizationMemberByIDResponse200 = {
  data: OrganizationMember
  status: 200
}

export type getOrganizationMemberByIDResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getOrganizationMemberByIDResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getOrganizationMemberByIDResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getOrganizationMemberByIDResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getOrganizationMemberByIDResponseSuccess = (getOrganizationMemberByIDResponse200) & {
  headers: Headers;
};
export type getOrganizationMemberByIDResponseError = (getOrganizationMemberByIDResponse401 | getOrganizationMemberByIDResponse403 | getOrganizationMemberByIDResponse404 | getOrganizationMemberByIDResponse500) & {
  headers: Headers;
};

export type getOrganizationMemberByIDResponse = (getOrganizationMemberByIDResponseSuccess | getOrganizationMemberByIDResponseError)

export const getGetOrganizationMemberByIDUrl = (organizationId: string,
    memberId: Uuid,) => {




  return `/organizations/${organizationId}/member/${memberId}`
}

/**
 * Fetches a single organization member row by member ID.
 * @summary Get an organization member by ID
 */
export const getOrganizationMemberByID = async (organizationId: string,
    memberId: Uuid, options?: Parameters<typeof customInstance>[1]): Promise<getOrganizationMemberByIDResponse> => {

  return customInstance<getOrganizationMemberByIDResponse>(getGetOrganizationMemberByIDUrl(organizationId,memberId),
  {
    ...options,
    method: 'GET'


  }
);}



export type getOrganizationMemberByEmailResponse200 = {
  data: OrganizationMember
  status: 200
}

export type getOrganizationMemberByEmailResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getOrganizationMemberByEmailResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getOrganizationMemberByEmailResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getOrganizationMemberByEmailResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getOrganizationMemberByEmailResponseSuccess = (getOrganizationMemberByEmailResponse200) & {
  headers: Headers;
};
export type getOrganizationMemberByEmailResponseError = (getOrganizationMemberByEmailResponse401 | getOrganizationMemberByEmailResponse403 | getOrganizationMemberByEmailResponse404 | getOrganizationMemberByEmailResponse500) & {
  headers: Headers;
};

export type getOrganizationMemberByEmailResponse = (getOrganizationMemberByEmailResponseSuccess | getOrganizationMemberByEmailResponseError)

export const getGetOrganizationMemberByEmailUrl = (organizationId: string,
    memberEmail: string,) => {




  return `/organizations/${organizationId}/member/${memberEmail}:by_email`
}

/**
 * AIP custom method (`:verb` suffix per AIP-136). Fetches a single
 * organization member by email address.
 * @summary Get an organization member by email
 */
export const getOrganizationMemberByEmail = async (organizationId: string,
    memberEmail: string, options?: Parameters<typeof customInstance>[1]): Promise<getOrganizationMemberByEmailResponse> => {

  return customInstance<getOrganizationMemberByEmailResponse>(getGetOrganizationMemberByEmailUrl(organizationId,memberEmail),
  {
    ...options,
    method: 'GET'


  }
);}



export type listWalletsResponse201 = {
  data: Wallet[]
  status: 201
}

export type listWalletsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listWalletsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listWalletsResponseSuccess = (listWalletsResponse201) & {
  headers: Headers;
};
export type listWalletsResponseError = (listWalletsResponse401 | listWalletsResponse500) & {
  headers: Headers;
};

export type listWalletsResponse = (listWalletsResponseSuccess | listWalletsResponseError)

export const getListWalletsUrl = () => {




  return `/wallets`
}

/**
 * Lists the wallets owned by the authenticated actor. NOTE: this
 * endpoint currently returns 201 (a known quirk of the current
 * implementation) — documented as-is.
 * @summary List your wallets
 */
export const listWallets = async ( options?: Parameters<typeof customInstance>[1]): Promise<listWalletsResponse> => {

  return customInstance<listWalletsResponse>(getListWalletsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type createWalletResponse201 = {
  data: Wallet
  status: 201
}

export type createWalletResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createWalletResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createWalletResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type createWalletResponseSuccess = (createWalletResponse201) & {
  headers: Headers;
};
export type createWalletResponseError = (createWalletResponse400 | createWalletResponse401 | createWalletResponse500) & {
  headers: Headers;
};

export type createWalletResponse = (createWalletResponseSuccess | createWalletResponseError)

export const getCreateWalletUrl = () => {




  return `/wallets`
}

/**
 * Creates a wallet owned by the authenticated actor, optionally
 * scoped to an organization. Wallets are the ownership unit for
 * webhook endpoints, sellers, and payment intents.
 * @summary Create a wallet
 */
export const createWallet = async (createWalletRequest: CreateWalletRequest, options?: Parameters<typeof customInstance>[1]): Promise<createWalletResponse> => {

  return customInstance<createWalletResponse>(getCreateWalletUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createWalletRequest)
  }
);}



export type getWalletResponse201 = {
  data: Wallet
  status: 201
}

export type getWalletResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getWalletResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getWalletResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getWalletResponseSuccess = (getWalletResponse201) & {
  headers: Headers;
};
export type getWalletResponseError = (getWalletResponse401 | getWalletResponse404 | getWalletResponse500) & {
  headers: Headers;
};

export type getWalletResponse = (getWalletResponseSuccess | getWalletResponseError)

export const getGetWalletUrl = (walletId: string,) => {




  return `/wallets/${walletId}`
}

/**
 * Fetches a single wallet. NOTE: this endpoint currently returns
 * 201 (a known quirk of the current implementation) — documented
 * as-is.
 * @summary Get a wallet by ID
 */
export const getWallet = async (walletId: string, options?: Parameters<typeof customInstance>[1]): Promise<getWalletResponse> => {

  return customInstance<getWalletResponse>(getGetWalletUrl(walletId),
  {
    ...options,
    method: 'GET'


  }
);}



export type setWalletFeeResponse200 = {
  data: unknown
  status: 200
}

export type setWalletFeeResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type setWalletFeeResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type setWalletFeeResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type setWalletFeeResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type setWalletFeeResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type setWalletFeeResponseSuccess = (setWalletFeeResponse200) & {
  headers: Headers;
};
export type setWalletFeeResponseError = (setWalletFeeResponse400 | setWalletFeeResponse401 | setWalletFeeResponse403 | setWalletFeeResponse404 | setWalletFeeResponse500) & {
  headers: Headers;
};

export type setWalletFeeResponse = (setWalletFeeResponseSuccess | setWalletFeeResponseError)

export const getSetWalletFeeUrl = (walletId: string,) => {




  return `/wallets/${walletId}/fee`
}

/**
 * Sets the wallet's marketplace fee in basis points (bps; 100 bps =
 * 1%). The authenticated actor must own the wallet.
 * @summary Set a wallet's fee
 */
export const setWalletFee = async (walletId: string,
    setFeeBPSRequest: SetFeeBPSRequest, options?: Parameters<typeof customInstance>[1]): Promise<setWalletFeeResponse> => {

  return customInstance<setWalletFeeResponse>(getSetWalletFeeUrl(walletId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(setFeeBPSRequest)
  }
);}



export type setWalletSandboxResponse200 = {
  data: unknown
  status: 200
}

export type setWalletSandboxResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type setWalletSandboxResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type setWalletSandboxResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type setWalletSandboxResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type setWalletSandboxResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type setWalletSandboxResponseSuccess = (setWalletSandboxResponse200) & {
  headers: Headers;
};
export type setWalletSandboxResponseError = (setWalletSandboxResponse400 | setWalletSandboxResponse401 | setWalletSandboxResponse403 | setWalletSandboxResponse404 | setWalletSandboxResponse500) & {
  headers: Headers;
};

export type setWalletSandboxResponse = (setWalletSandboxResponseSuccess | setWalletSandboxResponseError)

export const getSetWalletSandboxUrl = (walletId: string,) => {




  return `/wallets/${walletId}/sandbox`
}

/**
 * Toggles the wallet's sandbox mode. Sandbox wallets only accept
 * sandbox intents. The authenticated actor must own the wallet.
 * @summary Set a wallet's sandbox state
 */
export const setWalletSandbox = async (walletId: string,
    setSandboxRequest: SetSandboxRequest, options?: Parameters<typeof customInstance>[1]): Promise<setWalletSandboxResponse> => {

  return customInstance<setWalletSandboxResponse>(getSetWalletSandboxUrl(walletId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(setSandboxRequest)
  }
);}



export type bindCollectorResponse204 = {
  data: void
  status: 204
}

export type bindCollectorResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type bindCollectorResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type bindCollectorResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type bindCollectorResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type bindCollectorResponseSuccess = (bindCollectorResponse204) & {
  headers: Headers;
};
export type bindCollectorResponseError = (bindCollectorResponse401 | bindCollectorResponse403 | bindCollectorResponse404 | bindCollectorResponse500) & {
  headers: Headers;
};

export type bindCollectorResponse = (bindCollectorResponseSuccess | bindCollectorResponseError)

export const getBindCollectorUrl = (walletId: string,) => {




  return `/wallets/${walletId}/collector`
}

/**
 * Binds the wallet's payment collector (the provider account that
 * receives funds) after an OAuth connect. The actor must own the
 * wallet.
 * @summary Bind a collector to a wallet
 */
export const bindCollector = async (walletId: string,
    bindCollectorRequest: BindCollectorRequest, options?: Parameters<typeof customInstance>[1]): Promise<bindCollectorResponse> => {

  return customInstance<bindCollectorResponse>(getBindCollectorUrl(walletId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(bindCollectorRequest)
  }
);}



export type unbindCollectorResponse204 = {
  data: void
  status: 204
}

export type unbindCollectorResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type unbindCollectorResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type unbindCollectorResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type unbindCollectorResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type unbindCollectorResponseSuccess = (unbindCollectorResponse204) & {
  headers: Headers;
};
export type unbindCollectorResponseError = (unbindCollectorResponse401 | unbindCollectorResponse403 | unbindCollectorResponse404 | unbindCollectorResponse500) & {
  headers: Headers;
};

export type unbindCollectorResponse = (unbindCollectorResponseSuccess | unbindCollectorResponseError)

export const getUnbindCollectorUrl = (walletId: string,) => {




  return `/wallets/${walletId}/collector`
}

/**
 * Unbinds the wallet's payment collector. The actor must own the
 * wallet.
 * @summary Unbind a collector from a wallet
 */
export const unbindCollector = async (walletId: string, options?: Parameters<typeof customInstance>[1]): Promise<unbindCollectorResponse> => {

  return customInstance<unbindCollectorResponse>(getUnbindCollectorUrl(walletId),
  {
    ...options,
    method: 'DELETE'


  }
);}



export type listOrganizationWalletsResponse201 = {
  data: Wallet[]
  status: 201
}

export type listOrganizationWalletsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listOrganizationWalletsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type listOrganizationWalletsResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type listOrganizationWalletsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listOrganizationWalletsResponseSuccess = (listOrganizationWalletsResponse201) & {
  headers: Headers;
};
export type listOrganizationWalletsResponseError = (listOrganizationWalletsResponse401 | listOrganizationWalletsResponse403 | listOrganizationWalletsResponse404 | listOrganizationWalletsResponse500) & {
  headers: Headers;
};

export type listOrganizationWalletsResponse = (listOrganizationWalletsResponseSuccess | listOrganizationWalletsResponseError)

export const getListOrganizationWalletsUrl = (organizationId: string,) => {




  return `/organizations/${organizationId}/wallets`
}

/**
 * Lists the wallets scoped to an organization. The actor must
 * belong to the organization.
 * @summary List organization wallets
 */
export const listOrganizationWallets = async (organizationId: string, options?: Parameters<typeof customInstance>[1]): Promise<listOrganizationWalletsResponse> => {

  return customInstance<listOrganizationWalletsResponse>(getListOrganizationWalletsUrl(organizationId),
  {
    ...options,
    method: 'GET'


  }
);}



export type listCollectorsResponse200 = {
  data: Collector[]
  status: 200
}

export type listCollectorsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listCollectorsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listCollectorsResponseSuccess = (listCollectorsResponse200) & {
  headers: Headers;
};
export type listCollectorsResponseError = (listCollectorsResponse401 | listCollectorsResponse500) & {
  headers: Headers;
};

export type listCollectorsResponse = (listCollectorsResponseSuccess | listCollectorsResponseError)

export const getListCollectorsUrl = () => {




  return `/collectors`
}

/**
 * Lists the collectors (provider accounts that receive funds)
 * owned by the authenticated actor.
 * @summary List your collectors
 */
export const listCollectors = async ( options?: Parameters<typeof customInstance>[1]): Promise<listCollectorsResponse> => {

  return customInstance<listCollectorsResponse>(getListCollectorsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type getCollectorResponse200 = {
  data: Collector
  status: 200
}

export type getCollectorResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getCollectorResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getCollectorResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getCollectorResponseSuccess = (getCollectorResponse200) & {
  headers: Headers;
};
export type getCollectorResponseError = (getCollectorResponse401 | getCollectorResponse404 | getCollectorResponse500) & {
  headers: Headers;
};

export type getCollectorResponse = (getCollectorResponseSuccess | getCollectorResponseError)

export const getGetCollectorUrl = (collectorId: Uuid,) => {




  return `/collectors/${collectorId}`
}

/**
 * Fetches a single collector owned by the authenticated actor.
 * @summary Get a collector by ID
 */
export const getCollector = async (collectorId: Uuid, options?: Parameters<typeof customInstance>[1]): Promise<getCollectorResponse> => {

  return customInstance<getCollectorResponse>(getGetCollectorUrl(collectorId),
  {
    ...options,
    method: 'GET'


  }
);}



export type listOrganizationCollectorsResponse200 = {
  data: Collector[]
  status: 200
}

export type listOrganizationCollectorsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listOrganizationCollectorsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type listOrganizationCollectorsResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type listOrganizationCollectorsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listOrganizationCollectorsResponseSuccess = (listOrganizationCollectorsResponse200) & {
  headers: Headers;
};
export type listOrganizationCollectorsResponseError = (listOrganizationCollectorsResponse401 | listOrganizationCollectorsResponse403 | listOrganizationCollectorsResponse404 | listOrganizationCollectorsResponse500) & {
  headers: Headers;
};

export type listOrganizationCollectorsResponse = (listOrganizationCollectorsResponseSuccess | listOrganizationCollectorsResponseError)

export const getListOrganizationCollectorsUrl = (organizationId: string,) => {




  return `/organizations/${organizationId}/collectors`
}

/**
 * Lists the collectors scoped to an organization. The actor must
 * belong to the organization.
 * @summary List organization collectors
 */
export const listOrganizationCollectors = async (organizationId: string, options?: Parameters<typeof customInstance>[1]): Promise<listOrganizationCollectorsResponse> => {

  return customInstance<listOrganizationCollectorsResponse>(getListOrganizationCollectorsUrl(organizationId),
  {
    ...options,
    method: 'GET'


  }
);}



export type listWalletSellersResponse200 = {
  data: Seller[]
  status: 200
}

export type listWalletSellersResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listWalletSellersResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type listWalletSellersResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type listWalletSellersResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listWalletSellersResponseSuccess = (listWalletSellersResponse200) & {
  headers: Headers;
};
export type listWalletSellersResponseError = (listWalletSellersResponse401 | listWalletSellersResponse403 | listWalletSellersResponse404 | listWalletSellersResponse500) & {
  headers: Headers;
};

export type listWalletSellersResponse = (listWalletSellersResponseSuccess | listWalletSellersResponseError)

export const getListWalletSellersUrl = (walletId: string,) => {




  return `/wallets/${walletId}/sellers`
}

/**
 * Lists the sellers (provider accounts that split transactions)
 * bound to the wallet. The actor must own the wallet.
 * @summary List a wallet's sellers
 */
export const listWalletSellers = async (walletId: string, options?: Parameters<typeof customInstance>[1]): Promise<listWalletSellersResponse> => {

  return customInstance<listWalletSellersResponse>(getListWalletSellersUrl(walletId),
  {
    ...options,
    method: 'GET'


  }
);}



export type listIntentsByProfileResponse200 = {
  data: Intent[]
  status: 200
}

export type listIntentsByProfileResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listIntentsByProfileResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listIntentsByProfileResponseSuccess = (listIntentsByProfileResponse200) & {
  headers: Headers;
};
export type listIntentsByProfileResponseError = (listIntentsByProfileResponse401 | listIntentsByProfileResponse500) & {
  headers: Headers;
};

export type listIntentsByProfileResponse = (listIntentsByProfileResponseSuccess | listIntentsByProfileResponseError)

export const getListIntentsByProfileUrl = () => {




  return `/intents`
}

/**
 * Lists the payment intents created by the authenticated actor.
 * @summary List your payment intents
 */
export const listIntentsByProfile = async ( options?: Parameters<typeof customInstance>[1]): Promise<listIntentsByProfileResponse> => {

  return customInstance<listIntentsByProfileResponse>(getListIntentsByProfileUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type getIntentResponse200 = {
  data: Intent
  status: 200
}

export type getIntentResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getIntentResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getIntentResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getIntentResponseSuccess = (getIntentResponse200) & {
  headers: Headers;
};
export type getIntentResponseError = (getIntentResponse401 | getIntentResponse404 | getIntentResponse500) & {
  headers: Headers;
};

export type getIntentResponse = (getIntentResponseSuccess | getIntentResponseError)

export const getGetIntentUrl = (intentId: string,) => {




  return `/intents/${intentId}`
}

/**
 * Fetches a single payment intent (checkout attempt) by ID.
 * @summary Get a payment intent
 */
export const getIntent = async (intentId: string, options?: Parameters<typeof customInstance>[1]): Promise<getIntentResponse> => {

  return customInstance<getIntentResponse>(getGetIntentUrl(intentId),
  {
    ...options,
    method: 'GET'


  }
);}



export type cancelIntentResponse200 = {
  data: Intent
  status: 200
}

export type cancelIntentResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type cancelIntentResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type cancelIntentResponse409 = {
  data: ConflictResponse
  status: 409
}

export type cancelIntentResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type cancelIntentResponseSuccess = (cancelIntentResponse200) & {
  headers: Headers;
};
export type cancelIntentResponseError = (cancelIntentResponse401 | cancelIntentResponse404 | cancelIntentResponse409 | cancelIntentResponse500) & {
  headers: Headers;
};

export type cancelIntentResponse = (cancelIntentResponseSuccess | cancelIntentResponseError)

export const getCancelIntentUrl = (intentId: string,) => {




  return `/intents/${intentId}/cancel`
}

/**
 * Cancels a pending payment intent and returns its updated state.
 * Only intents still `pending` (or otherwise cancellable) can be
 * cancelled.
 * @summary Cancel a payment intent
 */
export const cancelIntent = async (intentId: string, options?: Parameters<typeof customInstance>[1]): Promise<cancelIntentResponse> => {

  return customInstance<cancelIntentResponse>(getCancelIntentUrl(intentId),
  {
    ...options,
    method: 'POST'


  }
);}



export type refundIntentResponse200 = {
  data: Intent
  status: 200
}

export type refundIntentResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type refundIntentResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type refundIntentResponse409 = {
  data: ConflictResponse
  status: 409
}

export type refundIntentResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type refundIntentResponseSuccess = (refundIntentResponse200) & {
  headers: Headers;
};
export type refundIntentResponseError = (refundIntentResponse401 | refundIntentResponse404 | refundIntentResponse409 | refundIntentResponse500) & {
  headers: Headers;
};

export type refundIntentResponse = (refundIntentResponseSuccess | refundIntentResponseError)

export const getRefundIntentUrl = (intentId: string,) => {




  return `/intents/${intentId}/refund`
}

/**
 * Fully refunds a `succeeded` payment intent and returns its updated
 * state. The intent status stays `succeeded` until the provider's
 * `payment.refunded` webhook confirms the refund (webhook-only
 * confirmation, mirroring approval). Only `succeeded` intents are
 * refundable; an already-`refunded` intent returns as-is (idempotent).
 * Full refund only in v1 — no amount parameter (partials are a later
 * additive change).
 * @summary Refund a succeeded payment intent (full refund)
 */
export const refundIntent = async (intentId: string, options?: Parameters<typeof customInstance>[1]): Promise<refundIntentResponse> => {

  return customInstance<refundIntentResponse>(getRefundIntentUrl(intentId),
  {
    ...options,
    method: 'POST'


  }
);}



export type listWalletIntentsResponse200 = {
  data: Intent[]
  status: 200
}

export type listWalletIntentsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listWalletIntentsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type listWalletIntentsResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type listWalletIntentsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listWalletIntentsResponseSuccess = (listWalletIntentsResponse200) & {
  headers: Headers;
};
export type listWalletIntentsResponseError = (listWalletIntentsResponse401 | listWalletIntentsResponse403 | listWalletIntentsResponse404 | listWalletIntentsResponse500) & {
  headers: Headers;
};

export type listWalletIntentsResponse = (listWalletIntentsResponseSuccess | listWalletIntentsResponseError)

export const getListWalletIntentsUrl = (walletId: string,) => {




  return `/wallets/${walletId}/intents`
}

/**
 * Lists the payment intents raised against the wallet. The actor
 * must own the wallet.
 * @summary List a wallet's payment intents
 */
export const listWalletIntents = async (walletId: string, options?: Parameters<typeof customInstance>[1]): Promise<listWalletIntentsResponse> => {

  return customInstance<listWalletIntentsResponse>(getListWalletIntentsUrl(walletId),
  {
    ...options,
    method: 'GET'


  }
);}



export type checkoutResponse201 = {
  data: Intent
  status: 201
}

export type checkoutResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type checkoutResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type checkoutResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type checkoutResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type checkoutResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type checkoutResponseSuccess = (checkoutResponse201) & {
  headers: Headers;
};
export type checkoutResponseError = (checkoutResponse400 | checkoutResponse401 | checkoutResponse403 | checkoutResponse404 | checkoutResponse500) & {
  headers: Headers;
};

export type checkoutResponse = (checkoutResponseSuccess | checkoutResponseError)

export const getCheckoutUrl = (walletId: string,) => {




  return `/wallets/${walletId}/intents`
}

/**
 * Starts a checkout: creates a payment intent against the wallet
 * for the given seller, currency, and amount. The provider handles
 * the payment out-of-band and reports the result via webhook. The
 * actor must own the wallet. See the `Intent` schema for the
 * provider-specific checkout data carried in
 * `checkout_provider_data`.
 * @summary Create a payment intent (checkout)
 */
export const checkout = async (walletId: string,
    createIntentRequest: CreateIntentRequest, options?: Parameters<typeof customInstance>[1]): Promise<checkoutResponse> => {

  return customInstance<checkoutResponse>(getCheckoutUrl(walletId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createIntentRequest)
  }
);}



export type listOrganizationIntentsResponse200 = {
  data: Intent[]
  status: 200
}

export type listOrganizationIntentsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listOrganizationIntentsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type listOrganizationIntentsResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type listOrganizationIntentsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listOrganizationIntentsResponseSuccess = (listOrganizationIntentsResponse200) & {
  headers: Headers;
};
export type listOrganizationIntentsResponseError = (listOrganizationIntentsResponse401 | listOrganizationIntentsResponse403 | listOrganizationIntentsResponse404 | listOrganizationIntentsResponse500) & {
  headers: Headers;
};

export type listOrganizationIntentsResponse = (listOrganizationIntentsResponseSuccess | listOrganizationIntentsResponseError)

export const getListOrganizationIntentsUrl = (organizationId: string,) => {




  return `/organizations/${organizationId}/intents`
}

/**
 * Lists the payment intents raised against wallets scoped to the
 * organization. The actor must belong to the organization.
 * @summary List organization payment intents
 */
export const listOrganizationIntents = async (organizationId: string, options?: Parameters<typeof customInstance>[1]): Promise<listOrganizationIntentsResponse> => {

  return customInstance<listOrganizationIntentsResponse>(getListOrganizationIntentsUrl(organizationId),
  {
    ...options,
    method: 'GET'


  }
);}



export type hardCreateIntentResponse201 = {
  data: Intent
  status: 201
}

export type hardCreateIntentResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type hardCreateIntentResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type hardCreateIntentResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type hardCreateIntentResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type hardCreateIntentResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type hardCreateIntentResponseSuccess = (hardCreateIntentResponse201) & {
  headers: Headers;
};
export type hardCreateIntentResponseError = (hardCreateIntentResponse400 | hardCreateIntentResponse401 | hardCreateIntentResponse403 | hardCreateIntentResponse404 | hardCreateIntentResponse500) & {
  headers: Headers;
};

export type hardCreateIntentResponse = (hardCreateIntentResponseSuccess | hardCreateIntentResponseError)

export const getHardCreateIntentUrl = () => {




  return `/testmode/intents/create`
}

/**
 * Test-mode helper: hard-creates an intent with full control over
 * its status, provider, and provider data — no payment provider is
 * contacted. Use to simulate provider outcomes (e.g. seed a
 * `succeeded` intent so downstream systems observe the webhook
 * flow). Must be a wallet owner.
 * @summary Create an intent directly (test mode)
 */
export const hardCreateIntent = async (hardCreateIntentRequest: HardCreateIntentRequest, options?: Parameters<typeof customInstance>[1]): Promise<hardCreateIntentResponse> => {

  return customInstance<hardCreateIntentResponse>(getHardCreateIntentUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(hardCreateIntentRequest)
  }
);}



export type testmodeRefundIntentResponse200 = {
  data: Intent
  status: 200
}

export type testmodeRefundIntentResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type testmodeRefundIntentResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type testmodeRefundIntentResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type testmodeRefundIntentResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type testmodeRefundIntentResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type testmodeRefundIntentResponseSuccess = (testmodeRefundIntentResponse200) & {
  headers: Headers;
};
export type testmodeRefundIntentResponseError = (testmodeRefundIntentResponse400 | testmodeRefundIntentResponse401 | testmodeRefundIntentResponse403 | testmodeRefundIntentResponse404 | testmodeRefundIntentResponse500) & {
  headers: Headers;
};

export type testmodeRefundIntentResponse = (testmodeRefundIntentResponseSuccess | testmodeRefundIntentResponseError)

export const getTestmodeRefundIntentUrl = (intentId: string,) => {




  return `/testmode/intents/${intentId}/refund`
}

/**
 * Test-mode helper: flips a `succeeded` intent to `refunded` and
 * stamps a fake refund marker in provider_data — no payment provider
 * is contacted. Use to simulate the provider's `payment.refunded`
 * outcome for downstream testing without a real refund.
 * @summary Refund an intent directly (test mode)
 */
export const testmodeRefundIntent = async (intentId: string, options?: Parameters<typeof customInstance>[1]): Promise<testmodeRefundIntentResponse> => {

  return customInstance<testmodeRefundIntentResponse>(getTestmodeRefundIntentUrl(intentId),
  {
    ...options,
    method: 'POST'


  }
);}



export type connectProviderResponse200 = {
  data: string
  status: 200
}

export type connectProviderResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type connectProviderResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type connectProviderResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type connectProviderResponseSuccess = (connectProviderResponse200) & {
  headers: Headers;
};
export type connectProviderResponseError = (connectProviderResponse400 | connectProviderResponse401 | connectProviderResponse500) & {
  headers: Headers;
};

export type connectProviderResponse = (connectProviderResponseSuccess | connectProviderResponseError)

export const getConnectProviderUrl = (provider: string,) => {




  return `/providers/${provider}/connect`
}

/**
 * Starts an OAuth connection to the given payment provider
 * (`mercadopago`). Callers must pass the flow (`collector` or
 * `seller`) and the final redirect URL (where the user lands after
 * the provider's consent screen). The provider redirect URI is
 * Payssage's own callback (`/providers/{provider}/callback`),
 * configured on the server (`MP_REDIRECT_URI`) — callers never
 * supply one. The response carries the URL to send the user to.
 * @summary Start a payment-provider OAuth connection
 */
export const connectProvider = async (provider: string,
    connectRequest: ConnectRequest, options?: Parameters<typeof customInstance>[1]): Promise<connectProviderResponse> => {

  return customInstance<connectProviderResponse>(getConnectProviderUrl(provider),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(connectRequest)
  }
);}



export type providerCallbackResponse200 = {
  data: string
  status: 200
}

export type providerCallbackResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type providerCallbackResponseSuccess = (providerCallbackResponse200) & {
  headers: Headers;
};
export type providerCallbackResponseError = (providerCallbackResponse400) & {
  headers: Headers;
};

export type providerCallbackResponse = (providerCallbackResponseSuccess | providerCallbackResponseError)

export const getProviderCallbackUrl = (provider: string,
    params: ProviderCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/providers/${provider}/callback?${stringifiedParams}` : `/providers/${provider}/callback`
}

/**
 * Browser redirect target: the provider lands here after the user
 * authorizes. Payssage exchanges the code, stores the provider
 * credential, and redirects the browser to the `final_redirect_url`
 * captured at connect time. Public — the provider's OAuth flow
 * cannot send an Authorization header.
 * @summary Payment-provider OAuth callback
 */
export const providerCallback = async (provider: string,
    params: ProviderCallbackParams, options?: Parameters<typeof customInstance>[1]): Promise<providerCallbackResponse> => {

  return customInstance<providerCallbackResponse>(getProviderCallbackUrl(provider,params),
  {
    ...options,
    method: 'GET'


  }
);}



export type revokeProviderResponse204 = {
  data: void
  status: 204
}

export type revokeProviderResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type revokeProviderResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type revokeProviderResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type revokeProviderResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type revokeProviderResponseSuccess = (revokeProviderResponse204) & {
  headers: Headers;
};
export type revokeProviderResponseError = (revokeProviderResponse400 | revokeProviderResponse401 | revokeProviderResponse404 | revokeProviderResponse500) & {
  headers: Headers;
};

export type revokeProviderResponse = (revokeProviderResponseSuccess | revokeProviderResponseError)

export const getRevokeProviderUrl = (provider: string,) => {




  return `/providers/${provider}/revoke`
}

/**
 * Revokes a connected provider credential (collector or seller).
 * @summary Revoke a payment-provider connection
 */
export const revokeProvider = async (provider: string,
    revokeRequest: RevokeRequest, options?: Parameters<typeof customInstance>[1]): Promise<revokeProviderResponse> => {

  return customInstance<revokeProviderResponse>(getRevokeProviderUrl(provider),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(revokeRequest)
  }
);}



export type receiveWebhookResponse200 = {
  data: unknown
  status: 200
}

export type receiveWebhookResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type receiveWebhookResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type receiveWebhookResponseSuccess = (receiveWebhookResponse200) & {
  headers: Headers;
};
export type receiveWebhookResponseError = (receiveWebhookResponse400 | receiveWebhookResponse404) & {
  headers: Headers;
};

export type receiveWebhookResponse = (receiveWebhookResponseSuccess | receiveWebhookResponseError)

export const getReceiveWebhookUrl = (provider: string,) => {




  return `/webhooks/${provider}`
}

/**
 * Ingestion endpoint called by the payment provider (e.g.
 * MercadoPago) when a payment event occurs. Payssage verifies the
 * provider signature, normalizes the event, stores it, and
 * dispatches deliveries to every webhook endpoint on the event's
 * wallet. Returns 200 even for expected-and-ignored cases
 * (unknown event types, duplicate deliveries) so the provider does
 * not retry; bad signatures return an error. Public — providers
 * cannot send an Authorization header.
 * @summary Receive a provider webhook
 */
export const receiveWebhook = async (provider: string,
    receiveWebhookBody: ReceiveWebhookBody, options?: Parameters<typeof customInstance>[1]): Promise<receiveWebhookResponse> => {

  return customInstance<receiveWebhookResponse>(getReceiveWebhookUrl(provider),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(receiveWebhookBody)
  }
);}



export type listWebhookEndpointsResponse200 = {
  data: WebhookEndpoint[]
  status: 200
}

export type listWebhookEndpointsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listWebhookEndpointsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type listWebhookEndpointsResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type listWebhookEndpointsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listWebhookEndpointsResponseSuccess = (listWebhookEndpointsResponse200) & {
  headers: Headers;
};
export type listWebhookEndpointsResponseError = (listWebhookEndpointsResponse401 | listWebhookEndpointsResponse403 | listWebhookEndpointsResponse404 | listWebhookEndpointsResponse500) & {
  headers: Headers;
};

export type listWebhookEndpointsResponse = (listWebhookEndpointsResponseSuccess | listWebhookEndpointsResponseError)

export const getListWebhookEndpointsUrl = (walletId: string,) => {




  return `/wallets/${walletId}/webhooks/endpoints`
}

/**
 * Lists the webhook endpoints registered on the wallet. The actor
 * must own the wallet.
 * @summary List a wallet's webhook endpoints
 */
export const listWebhookEndpoints = async (walletId: string, options?: Parameters<typeof customInstance>[1]): Promise<listWebhookEndpointsResponse> => {

  return customInstance<listWebhookEndpointsResponse>(getListWebhookEndpointsUrl(walletId),
  {
    ...options,
    method: 'GET'


  }
);}



export type createWebhookEndpointResponse201 = {
  data: WebhookEndpoint
  status: 201
}

export type createWebhookEndpointResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createWebhookEndpointResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createWebhookEndpointResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type createWebhookEndpointResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type createWebhookEndpointResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type createWebhookEndpointResponseSuccess = (createWebhookEndpointResponse201) & {
  headers: Headers;
};
export type createWebhookEndpointResponseError = (createWebhookEndpointResponse400 | createWebhookEndpointResponse401 | createWebhookEndpointResponse403 | createWebhookEndpointResponse404 | createWebhookEndpointResponse500) & {
  headers: Headers;
};

export type createWebhookEndpointResponse = (createWebhookEndpointResponseSuccess | createWebhookEndpointResponseError)

export const getCreateWebhookEndpointUrl = (walletId: string,) => {




  return `/wallets/${walletId}/webhooks/endpoints`
}

/**
 * Registers a tenant webhook endpoint on the wallet. Payssage will
 * POST provider events to `url` (see the top-level "Webhooks for
 * tenants" section for the delivery envelope and signature
 * headers). The returned `secret` is used to verify the
 * `X-Payssage-Signature` header on each delivery. The actor must
 * own the wallet.
 * @summary Create a webhook endpoint
 */
export const createWebhookEndpoint = async (walletId: string,
    createWebhookEndpointRequest: CreateWebhookEndpointRequest, options?: Parameters<typeof customInstance>[1]): Promise<createWebhookEndpointResponse> => {

  return customInstance<createWebhookEndpointResponse>(getCreateWebhookEndpointUrl(walletId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createWebhookEndpointRequest)
  }
);}



export type getWebhookEndpointResponse200 = {
  data: WebhookEndpoint
  status: 200
}

export type getWebhookEndpointResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getWebhookEndpointResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getWebhookEndpointResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getWebhookEndpointResponseSuccess = (getWebhookEndpointResponse200) & {
  headers: Headers;
};
export type getWebhookEndpointResponseError = (getWebhookEndpointResponse401 | getWebhookEndpointResponse404 | getWebhookEndpointResponse500) & {
  headers: Headers;
};

export type getWebhookEndpointResponse = (getWebhookEndpointResponseSuccess | getWebhookEndpointResponseError)

export const getGetWebhookEndpointUrl = (endpointId: string,) => {




  return `/webhooks/endpoints/${endpointId}`
}

/**
 * Fetches a single webhook endpoint by ID.
 * @summary Get a webhook endpoint
 */
export const getWebhookEndpoint = async (endpointId: string, options?: Parameters<typeof customInstance>[1]): Promise<getWebhookEndpointResponse> => {

  return customInstance<getWebhookEndpointResponse>(getGetWebhookEndpointUrl(endpointId),
  {
    ...options,
    method: 'GET'


  }
);}



export type deleteWebhookEndpointResponse204 = {
  data: void
  status: 204
}

export type deleteWebhookEndpointResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteWebhookEndpointResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteWebhookEndpointResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type deleteWebhookEndpointResponseSuccess = (deleteWebhookEndpointResponse204) & {
  headers: Headers;
};
export type deleteWebhookEndpointResponseError = (deleteWebhookEndpointResponse401 | deleteWebhookEndpointResponse404 | deleteWebhookEndpointResponse500) & {
  headers: Headers;
};

export type deleteWebhookEndpointResponse = (deleteWebhookEndpointResponseSuccess | deleteWebhookEndpointResponseError)

export const getDeleteWebhookEndpointUrl = (endpointId: string,) => {




  return `/webhooks/endpoints/${endpointId}`
}

/**
 * Deletes a webhook endpoint and stops future deliveries to it.
 * @summary Delete a webhook endpoint
 */
export const deleteWebhookEndpoint = async (endpointId: string, options?: Parameters<typeof customInstance>[1]): Promise<deleteWebhookEndpointResponse> => {

  return customInstance<deleteWebhookEndpointResponse>(getDeleteWebhookEndpointUrl(endpointId),
  {
    ...options,
    method: 'DELETE'


  }
);}



export type listWebhookEventsResponse200 = {
  data: WebhookEvent[]
  status: 200
}

export type listWebhookEventsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listWebhookEventsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type listWebhookEventsResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type listWebhookEventsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listWebhookEventsResponseSuccess = (listWebhookEventsResponse200) & {
  headers: Headers;
};
export type listWebhookEventsResponseError = (listWebhookEventsResponse401 | listWebhookEventsResponse403 | listWebhookEventsResponse404 | listWebhookEventsResponse500) & {
  headers: Headers;
};

export type listWebhookEventsResponse = (listWebhookEventsResponseSuccess | listWebhookEventsResponseError)

export const getListWebhookEventsUrl = (walletId: string,) => {




  return `/wallets/${walletId}/webhooks/events`
}

/**
 * Lists the provider webhook events recorded against the wallet.
 * The actor must own the wallet.
 * @summary List a wallet's webhook events
 */
export const listWebhookEvents = async (walletId: string, options?: Parameters<typeof customInstance>[1]): Promise<listWebhookEventsResponse> => {

  return customInstance<listWebhookEventsResponse>(getListWebhookEventsUrl(walletId),
  {
    ...options,
    method: 'GET'


  }
);}



export type getWebhookEventResponse200 = {
  data: WebhookEvent
  status: 200
}

export type getWebhookEventResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getWebhookEventResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getWebhookEventResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getWebhookEventResponseSuccess = (getWebhookEventResponse200) & {
  headers: Headers;
};
export type getWebhookEventResponseError = (getWebhookEventResponse401 | getWebhookEventResponse404 | getWebhookEventResponse500) & {
  headers: Headers;
};

export type getWebhookEventResponse = (getWebhookEventResponseSuccess | getWebhookEventResponseError)

export const getGetWebhookEventUrl = (eventId: Uuid,) => {




  return `/webhooks/events/${eventId}`
}

/**
 * Fetches a single webhook event (normalized provider event) by ID.
 * `payload` is the raw provider payload as received.
 * @summary Get a webhook event
 */
export const getWebhookEvent = async (eventId: Uuid, options?: Parameters<typeof customInstance>[1]): Promise<getWebhookEventResponse> => {

  return customInstance<getWebhookEventResponse>(getGetWebhookEventUrl(eventId),
  {
    ...options,
    method: 'GET'


  }
);}



export type listWebhookDeliveriesResponse200 = {
  data: WebhookDelivery[]
  status: 200
}

export type listWebhookDeliveriesResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listWebhookDeliveriesResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type listWebhookDeliveriesResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listWebhookDeliveriesResponseSuccess = (listWebhookDeliveriesResponse200) & {
  headers: Headers;
};
export type listWebhookDeliveriesResponseError = (listWebhookDeliveriesResponse401 | listWebhookDeliveriesResponse404 | listWebhookDeliveriesResponse500) & {
  headers: Headers;
};

export type listWebhookDeliveriesResponse = (listWebhookDeliveriesResponseSuccess | listWebhookDeliveriesResponseError)

export const getListWebhookDeliveriesUrl = (endpointId: string,) => {




  return `/webhooks/endpoints/${endpointId}/deliveries`
}

/**
 * Lists the delivery attempts made to a webhook endpoint. Each
 * delivery tracks retries: up to 5 attempts before it is marked
 * `failed`.
 * @summary List an endpoint's deliveries
 */
export const listWebhookDeliveries = async (endpointId: string, options?: Parameters<typeof customInstance>[1]): Promise<listWebhookDeliveriesResponse> => {

  return customInstance<listWebhookDeliveriesResponse>(getListWebhookDeliveriesUrl(endpointId),
  {
    ...options,
    method: 'GET'


  }
);}



export type getWebhookDeliveryResponse200 = {
  data: WebhookDelivery
  status: 200
}

export type getWebhookDeliveryResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getWebhookDeliveryResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getWebhookDeliveryResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getWebhookDeliveryResponseSuccess = (getWebhookDeliveryResponse200) & {
  headers: Headers;
};
export type getWebhookDeliveryResponseError = (getWebhookDeliveryResponse401 | getWebhookDeliveryResponse404 | getWebhookDeliveryResponse500) & {
  headers: Headers;
};

export type getWebhookDeliveryResponse = (getWebhookDeliveryResponseSuccess | getWebhookDeliveryResponseError)

export const getGetWebhookDeliveryUrl = (deliveryId: Uuid,) => {




  return `/webhooks/deliveries/${deliveryId}`
}

/**
 * Fetches a single delivery attempt, including its current status,
 * attempt count, and the last response received from the endpoint.
 * @summary Get a webhook delivery
 */
export const getWebhookDelivery = async (deliveryId: Uuid, options?: Parameters<typeof customInstance>[1]): Promise<getWebhookDeliveryResponse> => {

  return customInstance<getWebhookDeliveryResponse>(getGetWebhookDeliveryUrl(deliveryId),
  {
    ...options,
    method: 'GET'


  }
);}
