/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Informd API
 * Informd is TrieOH's forms service: namespaces (tenant grouping),
 * forms, steps (sections), fields (question definitions), and
 * responses (submissions).
 *
 * ## Authentication
 *
 * | Scheme | Header | Notes |
 * |---|---|---|
 * | Bearer JWT | `Authorization: Bearer <token>` | IdentityX access token. |
 * | API key | `X-API-KEY: <key>` | IdentityX API key. |
 *
 * `anyAuth` endpoints accept either. Namespace routes (`/namespaces...`)
 * require a JWT (`jwt` only). The following routes are public:
 * `GET /forms/{form_id}/asnwerable` (public answer view — note the
 * original spelling, part of the interface) and
 * `POST /forms/{form_id}/responses` (public submission).
 *
 * ## Response envelope
 *
 * Every JSON response is the `fun.Response` envelope:
 *
 * ```json
 * {
 *   "code": 200,
 *   "message": "",
 *   "data": { "...": "operation payload" },
 *   "error": null,
 *   "pagination": null,
 *   "timestamp": "2026-01-01T12:00:00Z",
 *   "module": "Informd"
 * }
 * ```
 *
 * - Success: `data` carries the payload. Errors: `error` carries an
 *   `AppError` — `{ "code", "message", "fields", "meta" }`.
 * - `pagination` is reserved for paged list endpoints (currently
 *   unused by Informd routes).
 *
 * ## Error codes → HTTP status
 *
 * The `error.code` sentinel maps to the HTTP status:
 *
 * | code | status |
 * |---|---|
 * | `BAD_REQUEST`, `VALIDATION_ERROR` | 400 |
 * | `UNAUTHORIZED` | 401 |
 * | `PAYMENT_REQUIRED` | 402 |
 * | `FORBIDDEN` | 403 |
 * | `NOT_FOUND` | 404 |
 * | `METHOD_NOT_ALLOWED` | 405 |
 * | `CONFLICT` | 409 |
 * | `UNPROCESSABLE_ENTITY` | 422 |
 * | `TOO_MANY_REQUESTS` | 429 |
 * | `INTERNAL_ERROR` | 500 |
 * | `NOT_IMPLEMENTED` | 501 |
 * | `BAD_GATEWAY` | 502 |
 * | `SERVICE_UNAVAILABLE` | 503 |
 *
 * ## Form model
 *
 * A form has steps, each step has fields, each field may have a select
 * configuration (when `type` is `select`). The `full` view
 * (`GET /forms/{form_id}/full`) returns the form with steps, fields,
 * and their answers; the `asnwerable` view returns the same shape
 * without answers, for respondents.
 *
 * ### Duplicated namespaced routes
 *
 * Several form/step/field operations exist twice: anchored on the form
 * (`/forms/{form_id}/...`) and on the namespace
 * (`/namespaces/{namespace_id}/forms/{form_id}/...`). Both are live
 * routes; the namespaced variants are scheduled for removal (the form
 * already anchors via its namespace). Keep using the `/forms/...`
 * variants in new code.
 *
 * ## Rate limits
 *
 * The harness applies a fixed rate limit of 400 requests/second with a
 * burst of 20, keyed by client IP. Exceeded requests receive
 * `429 TOO_MANY_REQUESTS`.
 *
 * OpenAPI spec version: 0.1.0
 */

export * from './addFormMemberRequest';
export * from './addNamespaceMemberRequest';
export * from './answer';
export * from './answerAnswer';
export * from './badRequestResponse';
export * from './conflictResponse';
export * from './createFieldRequest';
export * from './createFieldRequestConfig';
export * from './createFieldRequestDefaultValue';
export * from './createFieldRequestPlaceholder';
export * from './createFieldSelectConfigRequest';
export * from './createFieldSelectConfigRequestOptionsItem';
export * from './createFormRequest';
export * from './createNamespaceRequest';
export * from './createStepRequest';
export * from './editSelectConfigRequest';
export * from './editSelectConfigRequestOptionsItem';
export * from './error';
export * from './errorCode';
export * from './errorDebug';
export * from './errorFieldsItem';
export * from './errorMeta';
export * from './errorResponse';
export * from './field';
export * from './fieldAnswerable';
export * from './fieldConfig';
export * from './fieldDefaultValue';
export * from './fieldPlaceholder';
export * from './fieldSelectConfig';
export * from './fieldSelectConfigOptionsItem';
export * from './fieldType';
export * from './forbiddenResponse';
export * from './form';
export * from './formAnswerable';
export * from './formMember';
export * from './formMemberRole';
export * from './formStatus';
export * from './fullAnswer';
export * from './fullField';
export * from './fullForm';
export * from './fullStep';
export * from './getFormResponseCount200';
export * from './getFormResponseCountNamespaced200';
export * from './getHealth200';
export * from './internalServerErrorResponse';
export * from './namespace';
export * from './namespaceMember';
export * from './namespaceMemberRole';
export * from './notFoundResponse';
export * from './nullableUUID';
export * from './paginationMeta';
export * from './removeFormMemberRequest';
export * from './removeNamespaceMemberRequest';
export * from './response';
export * from './responseData';
export * from './selectBehaviour';
export * from './selectValueType';
export * from './step';
export * from './stepAnswerable';
export * from './submitAnswer';
export * from './submitAnswerAnswer';
export * from './submitRequest';
export * from './unauthorizedResponse';
export * from './updateFieldRequest';
export * from './updateFieldRequestConfig';
export * from './updateFieldRequestDefaultValue';
export * from './updateFieldRequestPlaceholder';
export * from './updateStepRequest';
export * from './uuid';
