services:
  univents-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    working_dir: /app
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST_TEST}:${POSTGRES_PORT}/${POSTGRES_TEST_DB}?sslmode=disable"

      PORT: ${PORT:-8080}

      ENV: "test"

      DISABLE_RATE_LIMIT: true

      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS}

      REDIS_ADDR: ${REDIS_TEST_ADDR:-univents-redis:6379}
      REDIS_DB: ${REDIS_DB:-0}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      GOAUTH_URL: ${GOAUTH_URL:-http://go-auth:8080}
      GOAUTH_API_KEY: ${GOAUTH_API_KEY}
      GO_AUTH_PROJECT_ID: ${GO_AUTH_PROJECT_ID}

    depends_on:
      univents-test-database:
        condition: service_started
      univents-test-redis:
        condition: service_started
    networks:
      - testnet
      - univents-net
    command: ["go", "test", "-v", "./testing_framework/..."]

  univents-test-database:
    image: postgres:18
    command:
      - postgres
      - -c
      - log_statement=none
      - -c
      - log_min_messages=fatal
      - -c
      - log_min_error_statement=fatal
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    ports:
      - "5435:5432"
    networks:
      - testnet

  univents-test-redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --save "" --appendonly no
    ports:
      - "6381:6379"
    networks:
      - testnet

networks:
  testnet:
    driver: bridge
  univents-net:
    external: true