services:
  go-auth-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    working_dir: /app
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST_TEST}:${POSTGRES_PORT}/${POSTGRES_TEST_DB}?sslmode=disable"

      # SMTP (MailHog)
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""
      SMTP_FROM: "noreply@goauth.local"
      SMTP_TLS: "false"
      SMTP_STARTTLS: "false"

      MODULE: "go-auth-test"

      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS}
      ISSUER: ${ISSUER:-GoAuth}
      ENV: ${ENV:-development}
      API_URL: ${API_URL:-http://localhost:8080}
      APP_URL: ${APP_URL:-http://localhost:8080}

      DISABLE_RATE_LIMIT: ${DISABLE_RATE_LIMIT:-true}
      INCLUDE_DEBUG_CAUSES: ${INCLUDE_DEBUG_CAUSES:-true}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-1d5be275ff0376f9311c564868f7f4ba550753e5e46ad9acfe48fee7fd2de1ba}

    depends_on:
      mailhog:
        condition: service_healthy
      go-auth-test-database:
        condition: service_started
    networks:
      - testnet
    command: ["go", "test", "-v", "./testing_framework/..."]

  go-auth-test-database:
    image: postgres:18
    command:
      - postgres
      - -c
      - log_statement=${POSTGRES_LOG_STATEMENT:-none}
      - -c
      - log_min_messages=${POSTGRES_LOG_MIN_MESSAGES:-fatal}
      - -c
      - log_min_error_statement=${POSTGRES_LOG_MIN_ERROR_STATEMENT:-fatal}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    ports:
      - "5433:5432"
    networks:
      - testnet

  mailhog:
    image: mailhog/mailhog
    command: > 
      sh -c "MailHog >/dev/null 2>&1"
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - testnet
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8025" ]
      interval: 2s
      timeout: 1s
      retries: 10

networks:
  testnet:
    driver: bridge

