import type { FieldDefinitionResultI } from "./types"

export const defaultEmailVersionField: FieldDefinitionResultI = {
  key: "email",
  title: "Email",
  type: "email",
  owner: "system",
  mutable: false,
  required: true,
  position: -1,
  default_value: '',
  options: [],
  required_rules: [],
  visibility_rules: [],
  id: 'emailTemplate',
  object_id: 'emailTemplate',
  description: "",
  placeholder: "",
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const defaultPasswordVersionField: FieldDefinitionResultI = {
  key: "password",
  title: "Password",
  type: "string",
  owner: "system",
  mutable: false,
  required: true,
  position: -1,
  default_value: '',
  options: [],
  required_rules: [],
  visibility_rules: [],
  id: 'passwordTemplate',
  object_id: 'passwordTemplate',
  description: "",
  placeholder: "",
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}