/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EnvIdRouteImport } from './routes/$envId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnvIdIndexRouteImport } from './routes/$envId/index'
import { Route as EnvIdRelationshipsRouteImport } from './routes/$envId/relationships'
import { Route as EnvIdCheckRouteImport } from './routes/$envId/check'

const EnvIdRoute = EnvIdRouteImport.update({
  id: '/$envId',
  path: '/$envId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvIdIndexRoute = EnvIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnvIdRoute,
} as any)
const EnvIdRelationshipsRoute = EnvIdRelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => EnvIdRoute,
} as any)
const EnvIdCheckRoute = EnvIdCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => EnvIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$envId': typeof EnvIdRouteWithChildren
  '/$envId/check': typeof EnvIdCheckRoute
  '/$envId/relationships': typeof EnvIdRelationshipsRoute
  '/$envId/': typeof EnvIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$envId/check': typeof EnvIdCheckRoute
  '/$envId/relationships': typeof EnvIdRelationshipsRoute
  '/$envId': typeof EnvIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$envId': typeof EnvIdRouteWithChildren
  '/$envId/check': typeof EnvIdCheckRoute
  '/$envId/relationships': typeof EnvIdRelationshipsRoute
  '/$envId/': typeof EnvIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$envId'
    | '/$envId/check'
    | '/$envId/relationships'
    | '/$envId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$envId/check' | '/$envId/relationships' | '/$envId'
  id:
    | '__root__'
    | '/'
    | '/$envId'
    | '/$envId/check'
    | '/$envId/relationships'
    | '/$envId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnvIdRoute: typeof EnvIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$envId': {
      id: '/$envId'
      path: '/$envId'
      fullPath: '/$envId'
      preLoaderRoute: typeof EnvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$envId/': {
      id: '/$envId/'
      path: '/'
      fullPath: '/$envId/'
      preLoaderRoute: typeof EnvIdIndexRouteImport
      parentRoute: typeof EnvIdRoute
    }
    '/$envId/relationships': {
      id: '/$envId/relationships'
      path: '/relationships'
      fullPath: '/$envId/relationships'
      preLoaderRoute: typeof EnvIdRelationshipsRouteImport
      parentRoute: typeof EnvIdRoute
    }
    '/$envId/check': {
      id: '/$envId/check'
      path: '/check'
      fullPath: '/$envId/check'
      preLoaderRoute: typeof EnvIdCheckRouteImport
      parentRoute: typeof EnvIdRoute
    }
  }
}

interface EnvIdRouteChildren {
  EnvIdCheckRoute: typeof EnvIdCheckRoute
  EnvIdRelationshipsRoute: typeof EnvIdRelationshipsRoute
  EnvIdIndexRoute: typeof EnvIdIndexRoute
}

const EnvIdRouteChildren: EnvIdRouteChildren = {
  EnvIdCheckRoute: EnvIdCheckRoute,
  EnvIdRelationshipsRoute: EnvIdRelationshipsRoute,
  EnvIdIndexRoute: EnvIdIndexRoute,
}

const EnvIdRouteWithChildren = EnvIdRoute._addFileChildren(EnvIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnvIdRoute: EnvIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
