// Code generated by tygo. DO NOT EDIT.

//////////
// source: answers.go

export interface Answer {
  id: string;
  response_id: string;
  field_id?: string;
  answer?: any /* json.RawMessage */;
  answered_at: string;
  updated_at?: string;
}
export interface SubmitAnswer {
  field_id?: string;
  answer?: any /* json.RawMessage */;
}
export interface SubmitAnswerInput {
  field_id?: string;
  answer?: any /* json.RawMessage */;
  response_id: string;
}
export interface SubmitRequest {
  email?: string;
  answers: SubmitAnswer[];
}
export interface SubmitInput {
  form_id: string;
  email?: string;
  answers: SubmitAnswerInput[];
}

//////////
// source: fields.go

export type FieldType = string;
export const FieldTypeString: FieldType = "string";
export const FieldTypeEmail: FieldType = "email";
export const FieldTypeInt: FieldType = "int";
export const FieldTypeFloat: FieldType = "float";
export const FieldTypeBool: FieldType = "bool";
export const FieldTypeDate: FieldType = "date";
export const FieldTypeTime: FieldType = "time";
export const FieldTypeDatetime: FieldType = "datetime";
export const FieldTypeSelect: FieldType = "select";
export const FieldTypeFile: FieldType = "file";
export const FieldTypePhone: FieldType = "phone";
export const FieldTypeURL: FieldType = "url";
export type SelectBehaviour = string;
export const SelectBehaviourCheckbox: SelectBehaviour = "checkbox";
export const SelectBehaviourRadio: SelectBehaviour = "radio";
export const SelectBehaviourDropdownCheckbox: SelectBehaviour = "dropdown-checkbox";
export const SelectBehaviourDropdownRadio: SelectBehaviour = "dropdown-radio";
export type SelectValueType = string;
export const SelectValueTypeString: SelectValueType = "string";
export const SelectValueTypeEmail: SelectValueType = "email";
export const SelectValueTypeInt: SelectValueType = "int";
export const SelectValueTypeFloat: SelectValueType = "float";
export const SelectValueTypeDate: SelectValueType = "date";
export const SelectValueTypeTime: SelectValueType = "time";
export const SelectValueTypeDatetime: SelectValueType = "datetime";
export const SelectValueTypePhone: SelectValueType = "phone";
export const SelectValueTypeURL: SelectValueType = "url";
export interface Field {
  id: string;
  step_id: string;
  key: string;
  title: string;
  description?: string;
  position_hint: number /* int */;
  required: boolean;
  type: FieldType;
  placeholder?: any /* json.RawMessage */;
  default_value?: any /* json.RawMessage */;
  config?: any /* json.RawMessage */;
  created_at: string;
  updated_at: string;
}
export interface FieldSelectConfig {
  field_id: string;
  behaviour: SelectBehaviour;
  value_type: SelectValueType;
  options: any /* json.RawMessage */;
}
/**
 * CreateFieldRequest is the HTTP request body for creating a field.
 * SelectConfig is only required when Type is "select".
 */
export interface CreateFieldRequest {
  key: string;
  title: string;
  description?: string;
  position_hint: number /* int */;
  required: boolean;
  type: FieldType;
  placeholder?: any /* json.RawMessage */;
  default_value?: any /* json.RawMessage */;
  config?: any /* json.RawMessage */;
  select_config?: CreateFieldSelectConfigRequest;
}
export interface CreateFieldSelectConfigRequest {
  behaviour: SelectBehaviour;
  value_type: SelectValueType;
  options: any /* json.RawMessage */;
}
export interface CreateStepFieldInput {
  FormID: string;
  StepID: string;
  Key: string;
  Title: string;
  Description?: string;
  PositionHint: number /* int */;
  Required: boolean;
  Type: FieldType;
  Placeholder?: any /* json.RawMessage */;
  DefaultValue?: any /* json.RawMessage */;
  Config?: any /* json.RawMessage */;
  SelectConfig?: CreateFieldSelectConfigRequest;
}
export interface CreateNamespacedStepFieldInput {
  NamespaceID: string;
  FormID: string;
  StepID: string;
  Key: string;
  Title: string;
  Description?: string;
  PositionHint: number /* int */;
  Required: boolean;
  Type: FieldType;
  Placeholder?: any /* json.RawMessage */;
  DefaultValue?: any /* json.RawMessage */;
  Config?: any /* json.RawMessage */;
  SelectConfig?: CreateFieldSelectConfigRequest;
}
export interface UpdateFieldRequest {
  id: string;
  key: string;
  title: string;
  description?: string;
  position_hint: number /* int */;
  required: boolean;
  type: FieldType;
  placeholder?: any /* json.RawMessage */;
  default_value?: any /* json.RawMessage */;
  config?: any /* json.RawMessage */;
  select_config?: CreateFieldSelectConfigRequest;
}
export interface UpdateStepFieldInput {
  StepID: string;
  ID: string;
  Key: string;
  Title: string;
  Description?: string;
  PositionHint: number /* int */;
  Required: boolean;
  Type: FieldType;
  Placeholder?: any /* json.RawMessage */;
  DefaultValue?: any /* json.RawMessage */;
  Config?: any /* json.RawMessage */;
  SelectConfig?: CreateFieldSelectConfigRequest;
}
export interface UpdateNamespacedStepFieldInput {
  NamespaceID: string;
  FormID: string;
  StepID: string;
  ID: string;
  Key: string;
  Title: string;
  Description?: string;
  PositionHint: number /* int */;
  Required: boolean;
  Type: FieldType;
  Placeholder?: any /* json.RawMessage */;
  DefaultValue?: any /* json.RawMessage */;
  Config?: any /* json.RawMessage */;
  SelectConfig?: CreateFieldSelectConfigRequest;
}

//////////
// source: forms.go

export type FormStatus = string;
export const FormStatusDraft: FormStatus = "draft";
export const FormStatusOpen: FormStatus = "open";
export const FormStatusClosed: FormStatus = "closed";
export const FormStatusArchived: FormStatus = "archived";
export interface Form {
  id: string;
  namespace_id?: string;
  owner_id: string;
  created_by: string;
  title: string;
  status: FormStatus;
  opened_at?: string;
  closed_at?: string;
  archived_at?: string;
  created_at: string;
  updated_at: string;
}
export interface CreateFormRequest {
  title: string;
}
export type FormMemberRole = string;
export const FormMemberRoleViewer: FormMemberRole = "viewer";
export const FormMemberRoleEditor: FormMemberRole = "editor";
export const FormMemberRoleAdmin: FormMemberRole = "admin";
export const FormMemberRoleOwner: FormMemberRole = "owner";
export interface FormMember {
  user_id: string;
  form_id: string;
  role: FormMemberRole;
  added_at: string;
  added_by: string;
}
export interface AddFormMemberRequest {
  user_id: string;
  role: FormMemberRole;
}
export interface AddFormMemberInput {
  user_id: string;
  form_id: string;
  role: FormMemberRole;
}
export interface AddNamespaceFormMemberInput {
  user_id: string;
  namespace_id: string;
  form_id: string;
  role: FormMemberRole;
}
export interface RemoveFormMemberRequest {
  user_id: string;
}
export interface RemoveFormMemberInput {
  user_id: string;
  form_id: string;
}
export interface RemoveNamespaceFormMemberInput {
  user_id: string;
  namespace_id: string;
  form_id: string;
}
export interface FullForm {
  form: Form;
  steps: FullStep[];
}
export interface FormAnswerable {
  form: Form;
  steps: StepAnswerable[];
}
export interface FullStep {
  step: Step;
  fields: FullField[];
}
export interface StepAnswerable {
  step: Step;
  fields: FieldAnswerable[];
}
export interface FieldAnswerable {
  field: Field;
  field_select_config?: FieldSelectConfig;
}
export interface FullField {
  field: Field;
  answers: FullAnswer[];
}
export interface FullAnswer {
  answer: Answer;
  responder: string;
}

//////////
// source: namespaces.go

export interface Namespace {
  id: string;
  owner_id: string;
  name: string;
  created_at: string;
  updated_at: string;
}
export type NamespaceMemberRole = string;
export const NamespaceMemberRoleViewer: NamespaceMemberRole = "viewer";
export const NamespaceMemberRoleEditor: NamespaceMemberRole = "editor";
export const NamespaceMemberRoleAdmin: NamespaceMemberRole = "admin";
export const NamespaceMemberRoleOwner: NamespaceMemberRole = "owner";
export interface NamespaceMember {
  user_id: string;
  namespace_id: string;
  role: NamespaceMemberRole;
  added_at: string;
  added_by: string;
}
export interface CreateNamespaceRequest {
  name: string;
}
export interface AddNamespaceMemberRequest {
  user_id: string;
  role: NamespaceMemberRole;
}
export interface AddNamespaceMemberInput {
  user_id: string;
  role: NamespaceMemberRole;
  namespace_id: string;
}
export interface RemoveNamespaceMemberRequest {
  user_id: string;
}
export interface RemoveNamespaceMemberInput {
  user_id: string;
  namespace_id: string;
}

//////////
// source: responders.go

export interface Responder {
  id: string;
  user_id?: string;
  email: string;
}

//////////
// source: responses.go

export interface Response {
  id: string;
  form_id: string;
  invite_id?: string;
  responder_id?: string;
  email?: string;
  started_at: string;
  finished_at?: string;
}

//////////
// source: steps.go

export interface Step {
  id: string;
  form_id: string;
  title: string;
  description?: string;
  position_hint: number /* int */;
}
export interface CreateStepRequest {
  title: string;
  description?: string;
  position_hint: number /* int */;
}
export interface CreateFormStepInput {
  form_id: string;
  title: string;
  description?: string;
  position_hint: number /* int */;
}
export interface CreateNamespacedFormStepInput {
  namespace_id: string;
  form_id: string;
  title: string;
  description?: string;
  position_hint: number /* int */;
}
export interface UpdateStepRequest {
  id: string;
  title: string;
  description?: string;
  position_hint: number /* int */;
}
export interface UpdateFormStepInput {
  FormID: string;
  ID: string;
  Title: string;
  Description?: string;
  PositionHint: number /* int */;
}
export interface UpdateNamespacedFormStepInput {
  NamespaceID: string;
  FormID: string;
  ID: string;
  Title: string;
  Description?: string;
  PositionHint: number /* int */;
}
