// Code generated by tygo. DO NOT EDIT.

//////////
// source: forms.go

export type FormStatus = string;
export const FormStatusDraft: FormStatus = "draft";
export const FormStatusOpen: FormStatus = "open";
export const FormStatusClosed: FormStatus = "closed";
export const FormStatusArchived: FormStatus = "archived";
export interface Form {
  id: string;
  namespace_id?: string;
  owner_id: string;
  created_by: string;
  title: string;
  status: FormStatus;
  opened_at?: string;
  closed_at?: string;
  archived_at?: string;
  created_at: string;
  updated_at: string;
}
export interface CreateFormRequest {
  title: string;
}
export type FormMemberRole = string;
export const FormMemberRoleViewer: FormMemberRole = "viewer";
export const FormMemberRoleEditor: FormMemberRole = "editor";
export const FormMemberRoleAdmin: FormMemberRole = "admin";
export const FormMemberRoleOwner: FormMemberRole = "owner";
export interface FormMember {
  user_id: string;
  form_id: string;
  role: FormMemberRole;
  added_at: string;
  added_by: string;
}
export interface AddFormMemberRequest {
  user_id: string;
  role: FormMemberRole;
}
export interface AddFormMemberInput {
  user_id: string;
  form_id: string;
  role: FormMemberRole;
}
export interface AddNamespaceFormMemberInput {
  user_id: string;
  namespace_id: string;
  form_id: string;
  role: FormMemberRole;
}
export interface RemoveFormMemberRequest {
  user_id: string;
}
export interface RemoveFormMemberInput {
  user_id: string;
  form_id: string;
}
export interface RemoveNamespaceFormMemberInput {
  user_id: string;
  namespace_id: string;
  form_id: string;
}

//////////
// source: namespaces.go

export interface Namespace {
  id: string;
  owner_id: string;
  name: string;
  created_at: string;
  updated_at: string;
}
export type NamespaceMemberRole = string;
export const NamespaceMemberRoleViewer: NamespaceMemberRole = "viewer";
export const NamespaceMemberRoleEditor: NamespaceMemberRole = "editor";
export const NamespaceMemberRoleAdmin: NamespaceMemberRole = "admin";
export const NamespaceMemberRoleOwner: NamespaceMemberRole = "owner";
export interface NamespaceMember {
  user_id: string;
  namespace_id: string;
  role: NamespaceMemberRole;
  added_at: string;
  added_by: string;
}
export interface CreateNamespaceRequest {
  name: string;
}
export interface AddNamespaceMemberRequest {
  user_id: string;
  role: NamespaceMemberRole;
}
export interface AddNamespaceMemberInput {
  user_id: string;
  role: NamespaceMemberRole;
  namespace_id: string;
}
export interface RemoveNamespaceMemberRequest {
  user_id: string;
}
export interface RemoveNamespaceMemberInput {
  user_id: string;
  namespace_id: string;
}

//////////
// source: steps.go

export interface Step {
  id: string;
  form_id: string;
  title: string;
  description?: string;
  position_hint: number /* int */;
}
export interface CreateStepRequest {
  title: string;
  description?: string;
  position_hint: number /* int */;
}
export interface CreateFormStepInput {
  form_id: string;
  title: string;
  description?: string;
  position_hint: number /* int */;
}
export interface CreateNamespacedFormStepInput {
  namespace_id: string;
  form_id: string;
  title: string;
  description?: string;
  position_hint: number /* int */;
}
export interface UpdateStepRequest {
  id: string;
  title: string;
  description?: string;
  position_hint: number /* int */;
}
export interface UpdateFormStepInput {
  FormID: string;
  ID: string;
  Title: string;
  Description?: string;
  PositionHint: number /* int */;
}
export interface UpdateNamespacedFormStepInput {
  NamespaceID: string;
  FormID: string;
  ID: string;
  Title: string;
  Description?: string;
  PositionHint: number /* int */;
}
