import { z } from "zod";

export const EditionSchema = z.object({
    id:                     z.string().uuid(),
    event_id:               z.string().uuid(),
    goauth_scope_id:        z.string().uuid(),
    type:                   z.string(),
    edition_name:           z.string(),
    tagline:                z.string().nullable(),
    description:            z.string().nullable(),
    status:                 z.string(),
    monetary_type:          z.string(),
    registration_opens_at:  z.string().datetime().nullable(),
    registration_closes_at: z.string().datetime().nullable(),
    starts_at:              z.string().datetime(),
    ends_at:                z.string().datetime(),
    timezone:               z.string(),
    location_name:          z.string(),
    location_address:       z.string(),
    logo_url:               z.string().nullable(),
    banner_url:             z.string().nullable(),
    contact_email:          z.string().nullable(),
    contact_phone:          z.string().nullable(),
    organizer_name:         z.string().nullable(),
    created_by:             z.string().uuid(),
    created_at:             z.string().datetime(),
    updated_at:             z.string().datetime(),
    deleted_at:             z.string().datetime().nullable(),
});