import { z } from "zod";

export const EventSchema = z.object({
id:               z.string().uuid(),
owner_id:         z.string().uuid().nullable(),
organization_id:  z.string().uuid().nullable(),
goauth_scope_id:  z.string().uuid(),
name:             z.string(),
acronym:          z.string().nullable(),
slug:             z.string(),
tagline:          z.string().nullable(),
description:      z.string().nullable(),
is_series:        z.boolean(),
editions_count:   z.number().int(),
logo_url:         z.string().nullable(),
banner_url:       z.string().nullable(),
has_gallery:      z.boolean(),
gallery_urls:     z.array(z.string()).nullable(),
contact_email:    z.string().nullable(),
social_links:     z.array(z.any()).nullable(),
status:           z.string(),
created_by:       z.string().uuid(),
created_at:       z.string().datetime(),
updated_at:       z.string().datetime(),
deleted_at:       z.string().datetime().nullable(),
});