/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminWalletsRouteImport } from './routes/admin/wallets'
import { Route as AdminKeysRouteImport } from './routes/admin/keys'
import { Route as AdminOrganizationIDRouteImport } from './routes/admin/$organizationID'
import { Route as CallbackProviderIndexRouteImport } from './routes/callback/$provider/index'
import { Route as AdminOrganizationIDIndexRouteImport } from './routes/admin/$organizationID/index'
import { Route as AdminOrganizationIDMembersRouteImport } from './routes/admin/$organizationID/members'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKeysRoute = AdminKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationIDRoute = AdminOrganizationIDRouteImport.update({
  id: '/$organizationID',
  path: '/$organizationID',
  getParentRoute: () => AdminRoute,
} as any)
const CallbackProviderIndexRoute = CallbackProviderIndexRouteImport.update({
  id: '/callback/$provider/',
  path: '/callback/$provider/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationIDIndexRoute =
  AdminOrganizationIDIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminOrganizationIDRoute,
  } as any)
const AdminOrganizationIDMembersRoute =
  AdminOrganizationIDMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AdminOrganizationIDRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/$organizationID': typeof AdminOrganizationIDRouteWithChildren
  '/admin/keys': typeof AdminKeysRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$organizationID/members': typeof AdminOrganizationIDMembersRoute
  '/admin/$organizationID/': typeof AdminOrganizationIDIndexRoute
  '/callback/$provider/': typeof CallbackProviderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/$organizationID/members': typeof AdminOrganizationIDMembersRoute
  '/admin/$organizationID': typeof AdminOrganizationIDIndexRoute
  '/callback/$provider': typeof CallbackProviderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/$organizationID': typeof AdminOrganizationIDRouteWithChildren
  '/admin/keys': typeof AdminKeysRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$organizationID/members': typeof AdminOrganizationIDMembersRoute
  '/admin/$organizationID/': typeof AdminOrganizationIDIndexRoute
  '/callback/$provider/': typeof CallbackProviderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/$organizationID'
    | '/admin/keys'
    | '/admin/wallets'
    | '/admin/'
    | '/admin/$organizationID/members'
    | '/admin/$organizationID/'
    | '/callback/$provider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/keys'
    | '/admin/wallets'
    | '/admin'
    | '/admin/$organizationID/members'
    | '/admin/$organizationID'
    | '/callback/$provider'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/$organizationID'
    | '/admin/keys'
    | '/admin/wallets'
    | '/admin/'
    | '/admin/$organizationID/members'
    | '/admin/$organizationID/'
    | '/callback/$provider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CallbackProviderIndexRoute: typeof CallbackProviderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/keys': {
      id: '/admin/keys'
      path: '/keys'
      fullPath: '/admin/keys'
      preLoaderRoute: typeof AdminKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$organizationID': {
      id: '/admin/$organizationID'
      path: '/$organizationID'
      fullPath: '/admin/$organizationID'
      preLoaderRoute: typeof AdminOrganizationIDRouteImport
      parentRoute: typeof AdminRoute
    }
    '/callback/$provider/': {
      id: '/callback/$provider/'
      path: '/callback/$provider'
      fullPath: '/callback/$provider/'
      preLoaderRoute: typeof CallbackProviderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$organizationID/': {
      id: '/admin/$organizationID/'
      path: '/'
      fullPath: '/admin/$organizationID/'
      preLoaderRoute: typeof AdminOrganizationIDIndexRouteImport
      parentRoute: typeof AdminOrganizationIDRoute
    }
    '/admin/$organizationID/members': {
      id: '/admin/$organizationID/members'
      path: '/members'
      fullPath: '/admin/$organizationID/members'
      preLoaderRoute: typeof AdminOrganizationIDMembersRouteImport
      parentRoute: typeof AdminOrganizationIDRoute
    }
  }
}

interface AdminOrganizationIDRouteChildren {
  AdminOrganizationIDMembersRoute: typeof AdminOrganizationIDMembersRoute
  AdminOrganizationIDIndexRoute: typeof AdminOrganizationIDIndexRoute
}

const AdminOrganizationIDRouteChildren: AdminOrganizationIDRouteChildren = {
  AdminOrganizationIDMembersRoute: AdminOrganizationIDMembersRoute,
  AdminOrganizationIDIndexRoute: AdminOrganizationIDIndexRoute,
}

const AdminOrganizationIDRouteWithChildren =
  AdminOrganizationIDRoute._addFileChildren(AdminOrganizationIDRouteChildren)

interface AdminRouteChildren {
  AdminOrganizationIDRoute: typeof AdminOrganizationIDRouteWithChildren
  AdminKeysRoute: typeof AdminKeysRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrganizationIDRoute: AdminOrganizationIDRouteWithChildren,
  AdminKeysRoute: AdminKeysRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CallbackProviderIndexRoute: CallbackProviderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
