/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminWalletsRouteImport } from './routes/admin/wallets'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminKeysRouteImport } from './routes/admin/keys'
import { Route as AdminCollectorsRouteImport } from './routes/admin/collectors'
import { Route as AdminOrganizationIDRouteImport } from './routes/admin/$organizationID'
import { Route as CallbackProviderIndexRouteImport } from './routes/callback/$provider/index'
import { Route as AdminOrganizationIDIndexRouteImport } from './routes/admin/$organizationID/index'
import { Route as AdminWalletsWalletIDRouteImport } from './routes/admin/wallets/$walletID'
import { Route as AdminOrganizationIDTransactionsRouteImport } from './routes/admin/$organizationID/transactions'
import { Route as AdminOrganizationIDMembersRouteImport } from './routes/admin/$organizationID/members'
import { Route as AdminOrganizationIDCollectorsRouteImport } from './routes/admin/$organizationID/collectors'
import { Route as AdminWalletsWalletIDIndexRouteImport } from './routes/admin/wallets/$walletID/index'
import { Route as AdminWalletsWalletIDTransactionsRouteImport } from './routes/admin/wallets/$walletID/transactions'
import { Route as AdminWalletsWalletIDSellersRouteImport } from './routes/admin/wallets/$walletID/sellers'
import { Route as AdminWalletsWalletIDConnectSellerRouteImport } from './routes/admin/wallets/$walletID/connect-seller'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKeysRoute = AdminKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectorsRoute = AdminCollectorsRouteImport.update({
  id: '/collectors',
  path: '/collectors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationIDRoute = AdminOrganizationIDRouteImport.update({
  id: '/$organizationID',
  path: '/$organizationID',
  getParentRoute: () => AdminRoute,
} as any)
const CallbackProviderIndexRoute = CallbackProviderIndexRouteImport.update({
  id: '/callback/$provider/',
  path: '/callback/$provider/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationIDIndexRoute =
  AdminOrganizationIDIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminOrganizationIDRoute,
  } as any)
const AdminWalletsWalletIDRoute = AdminWalletsWalletIDRouteImport.update({
  id: '/$walletID',
  path: '/$walletID',
  getParentRoute: () => AdminWalletsRoute,
} as any)
const AdminOrganizationIDTransactionsRoute =
  AdminOrganizationIDTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AdminOrganizationIDRoute,
  } as any)
const AdminOrganizationIDMembersRoute =
  AdminOrganizationIDMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AdminOrganizationIDRoute,
  } as any)
const AdminOrganizationIDCollectorsRoute =
  AdminOrganizationIDCollectorsRouteImport.update({
    id: '/collectors',
    path: '/collectors',
    getParentRoute: () => AdminOrganizationIDRoute,
  } as any)
const AdminWalletsWalletIDIndexRoute =
  AdminWalletsWalletIDIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminWalletsWalletIDRoute,
  } as any)
const AdminWalletsWalletIDTransactionsRoute =
  AdminWalletsWalletIDTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AdminWalletsWalletIDRoute,
  } as any)
const AdminWalletsWalletIDSellersRoute =
  AdminWalletsWalletIDSellersRouteImport.update({
    id: '/sellers',
    path: '/sellers',
    getParentRoute: () => AdminWalletsWalletIDRoute,
  } as any)
const AdminWalletsWalletIDConnectSellerRoute =
  AdminWalletsWalletIDConnectSellerRouteImport.update({
    id: '/connect-seller',
    path: '/connect-seller',
    getParentRoute: () => AdminWalletsWalletIDRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/$organizationID': typeof AdminOrganizationIDRouteWithChildren
  '/admin/collectors': typeof AdminCollectorsRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/wallets': typeof AdminWalletsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/$organizationID/collectors': typeof AdminOrganizationIDCollectorsRoute
  '/admin/$organizationID/members': typeof AdminOrganizationIDMembersRoute
  '/admin/$organizationID/transactions': typeof AdminOrganizationIDTransactionsRoute
  '/admin/wallets/$walletID': typeof AdminWalletsWalletIDRouteWithChildren
  '/admin/$organizationID/': typeof AdminOrganizationIDIndexRoute
  '/callback/$provider/': typeof CallbackProviderIndexRoute
  '/admin/wallets/$walletID/connect-seller': typeof AdminWalletsWalletIDConnectSellerRoute
  '/admin/wallets/$walletID/sellers': typeof AdminWalletsWalletIDSellersRoute
  '/admin/wallets/$walletID/transactions': typeof AdminWalletsWalletIDTransactionsRoute
  '/admin/wallets/$walletID/': typeof AdminWalletsWalletIDIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/collectors': typeof AdminCollectorsRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/wallets': typeof AdminWalletsRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/$organizationID/collectors': typeof AdminOrganizationIDCollectorsRoute
  '/admin/$organizationID/members': typeof AdminOrganizationIDMembersRoute
  '/admin/$organizationID/transactions': typeof AdminOrganizationIDTransactionsRoute
  '/admin/$organizationID': typeof AdminOrganizationIDIndexRoute
  '/callback/$provider': typeof CallbackProviderIndexRoute
  '/admin/wallets/$walletID/connect-seller': typeof AdminWalletsWalletIDConnectSellerRoute
  '/admin/wallets/$walletID/sellers': typeof AdminWalletsWalletIDSellersRoute
  '/admin/wallets/$walletID/transactions': typeof AdminWalletsWalletIDTransactionsRoute
  '/admin/wallets/$walletID': typeof AdminWalletsWalletIDIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/$organizationID': typeof AdminOrganizationIDRouteWithChildren
  '/admin/collectors': typeof AdminCollectorsRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/wallets': typeof AdminWalletsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/$organizationID/collectors': typeof AdminOrganizationIDCollectorsRoute
  '/admin/$organizationID/members': typeof AdminOrganizationIDMembersRoute
  '/admin/$organizationID/transactions': typeof AdminOrganizationIDTransactionsRoute
  '/admin/wallets/$walletID': typeof AdminWalletsWalletIDRouteWithChildren
  '/admin/$organizationID/': typeof AdminOrganizationIDIndexRoute
  '/callback/$provider/': typeof CallbackProviderIndexRoute
  '/admin/wallets/$walletID/connect-seller': typeof AdminWalletsWalletIDConnectSellerRoute
  '/admin/wallets/$walletID/sellers': typeof AdminWalletsWalletIDSellersRoute
  '/admin/wallets/$walletID/transactions': typeof AdminWalletsWalletIDTransactionsRoute
  '/admin/wallets/$walletID/': typeof AdminWalletsWalletIDIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/$organizationID'
    | '/admin/collectors'
    | '/admin/keys'
    | '/admin/transactions'
    | '/admin/wallets'
    | '/admin/'
    | '/admin/$organizationID/collectors'
    | '/admin/$organizationID/members'
    | '/admin/$organizationID/transactions'
    | '/admin/wallets/$walletID'
    | '/admin/$organizationID/'
    | '/callback/$provider/'
    | '/admin/wallets/$walletID/connect-seller'
    | '/admin/wallets/$walletID/sellers'
    | '/admin/wallets/$walletID/transactions'
    | '/admin/wallets/$walletID/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/collectors'
    | '/admin/keys'
    | '/admin/transactions'
    | '/admin/wallets'
    | '/admin'
    | '/admin/$organizationID/collectors'
    | '/admin/$organizationID/members'
    | '/admin/$organizationID/transactions'
    | '/admin/$organizationID'
    | '/callback/$provider'
    | '/admin/wallets/$walletID/connect-seller'
    | '/admin/wallets/$walletID/sellers'
    | '/admin/wallets/$walletID/transactions'
    | '/admin/wallets/$walletID'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/$organizationID'
    | '/admin/collectors'
    | '/admin/keys'
    | '/admin/transactions'
    | '/admin/wallets'
    | '/admin/'
    | '/admin/$organizationID/collectors'
    | '/admin/$organizationID/members'
    | '/admin/$organizationID/transactions'
    | '/admin/wallets/$walletID'
    | '/admin/$organizationID/'
    | '/callback/$provider/'
    | '/admin/wallets/$walletID/connect-seller'
    | '/admin/wallets/$walletID/sellers'
    | '/admin/wallets/$walletID/transactions'
    | '/admin/wallets/$walletID/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CallbackProviderIndexRoute: typeof CallbackProviderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/keys': {
      id: '/admin/keys'
      path: '/keys'
      fullPath: '/admin/keys'
      preLoaderRoute: typeof AdminKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collectors': {
      id: '/admin/collectors'
      path: '/collectors'
      fullPath: '/admin/collectors'
      preLoaderRoute: typeof AdminCollectorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$organizationID': {
      id: '/admin/$organizationID'
      path: '/$organizationID'
      fullPath: '/admin/$organizationID'
      preLoaderRoute: typeof AdminOrganizationIDRouteImport
      parentRoute: typeof AdminRoute
    }
    '/callback/$provider/': {
      id: '/callback/$provider/'
      path: '/callback/$provider'
      fullPath: '/callback/$provider/'
      preLoaderRoute: typeof CallbackProviderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$organizationID/': {
      id: '/admin/$organizationID/'
      path: '/'
      fullPath: '/admin/$organizationID/'
      preLoaderRoute: typeof AdminOrganizationIDIndexRouteImport
      parentRoute: typeof AdminOrganizationIDRoute
    }
    '/admin/wallets/$walletID': {
      id: '/admin/wallets/$walletID'
      path: '/$walletID'
      fullPath: '/admin/wallets/$walletID'
      preLoaderRoute: typeof AdminWalletsWalletIDRouteImport
      parentRoute: typeof AdminWalletsRoute
    }
    '/admin/$organizationID/transactions': {
      id: '/admin/$organizationID/transactions'
      path: '/transactions'
      fullPath: '/admin/$organizationID/transactions'
      preLoaderRoute: typeof AdminOrganizationIDTransactionsRouteImport
      parentRoute: typeof AdminOrganizationIDRoute
    }
    '/admin/$organizationID/members': {
      id: '/admin/$organizationID/members'
      path: '/members'
      fullPath: '/admin/$organizationID/members'
      preLoaderRoute: typeof AdminOrganizationIDMembersRouteImport
      parentRoute: typeof AdminOrganizationIDRoute
    }
    '/admin/$organizationID/collectors': {
      id: '/admin/$organizationID/collectors'
      path: '/collectors'
      fullPath: '/admin/$organizationID/collectors'
      preLoaderRoute: typeof AdminOrganizationIDCollectorsRouteImport
      parentRoute: typeof AdminOrganizationIDRoute
    }
    '/admin/wallets/$walletID/': {
      id: '/admin/wallets/$walletID/'
      path: '/'
      fullPath: '/admin/wallets/$walletID/'
      preLoaderRoute: typeof AdminWalletsWalletIDIndexRouteImport
      parentRoute: typeof AdminWalletsWalletIDRoute
    }
    '/admin/wallets/$walletID/transactions': {
      id: '/admin/wallets/$walletID/transactions'
      path: '/transactions'
      fullPath: '/admin/wallets/$walletID/transactions'
      preLoaderRoute: typeof AdminWalletsWalletIDTransactionsRouteImport
      parentRoute: typeof AdminWalletsWalletIDRoute
    }
    '/admin/wallets/$walletID/sellers': {
      id: '/admin/wallets/$walletID/sellers'
      path: '/sellers'
      fullPath: '/admin/wallets/$walletID/sellers'
      preLoaderRoute: typeof AdminWalletsWalletIDSellersRouteImport
      parentRoute: typeof AdminWalletsWalletIDRoute
    }
    '/admin/wallets/$walletID/connect-seller': {
      id: '/admin/wallets/$walletID/connect-seller'
      path: '/connect-seller'
      fullPath: '/admin/wallets/$walletID/connect-seller'
      preLoaderRoute: typeof AdminWalletsWalletIDConnectSellerRouteImport
      parentRoute: typeof AdminWalletsWalletIDRoute
    }
  }
}

interface AdminOrganizationIDRouteChildren {
  AdminOrganizationIDCollectorsRoute: typeof AdminOrganizationIDCollectorsRoute
  AdminOrganizationIDMembersRoute: typeof AdminOrganizationIDMembersRoute
  AdminOrganizationIDTransactionsRoute: typeof AdminOrganizationIDTransactionsRoute
  AdminOrganizationIDIndexRoute: typeof AdminOrganizationIDIndexRoute
}

const AdminOrganizationIDRouteChildren: AdminOrganizationIDRouteChildren = {
  AdminOrganizationIDCollectorsRoute: AdminOrganizationIDCollectorsRoute,
  AdminOrganizationIDMembersRoute: AdminOrganizationIDMembersRoute,
  AdminOrganizationIDTransactionsRoute: AdminOrganizationIDTransactionsRoute,
  AdminOrganizationIDIndexRoute: AdminOrganizationIDIndexRoute,
}

const AdminOrganizationIDRouteWithChildren =
  AdminOrganizationIDRoute._addFileChildren(AdminOrganizationIDRouteChildren)

interface AdminWalletsWalletIDRouteChildren {
  AdminWalletsWalletIDConnectSellerRoute: typeof AdminWalletsWalletIDConnectSellerRoute
  AdminWalletsWalletIDSellersRoute: typeof AdminWalletsWalletIDSellersRoute
  AdminWalletsWalletIDTransactionsRoute: typeof AdminWalletsWalletIDTransactionsRoute
  AdminWalletsWalletIDIndexRoute: typeof AdminWalletsWalletIDIndexRoute
}

const AdminWalletsWalletIDRouteChildren: AdminWalletsWalletIDRouteChildren = {
  AdminWalletsWalletIDConnectSellerRoute:
    AdminWalletsWalletIDConnectSellerRoute,
  AdminWalletsWalletIDSellersRoute: AdminWalletsWalletIDSellersRoute,
  AdminWalletsWalletIDTransactionsRoute: AdminWalletsWalletIDTransactionsRoute,
  AdminWalletsWalletIDIndexRoute: AdminWalletsWalletIDIndexRoute,
}

const AdminWalletsWalletIDRouteWithChildren =
  AdminWalletsWalletIDRoute._addFileChildren(AdminWalletsWalletIDRouteChildren)

interface AdminWalletsRouteChildren {
  AdminWalletsWalletIDRoute: typeof AdminWalletsWalletIDRouteWithChildren
}

const AdminWalletsRouteChildren: AdminWalletsRouteChildren = {
  AdminWalletsWalletIDRoute: AdminWalletsWalletIDRouteWithChildren,
}

const AdminWalletsRouteWithChildren = AdminWalletsRoute._addFileChildren(
  AdminWalletsRouteChildren,
)

interface AdminRouteChildren {
  AdminOrganizationIDRoute: typeof AdminOrganizationIDRouteWithChildren
  AdminCollectorsRoute: typeof AdminCollectorsRoute
  AdminKeysRoute: typeof AdminKeysRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminWalletsRoute: typeof AdminWalletsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrganizationIDRoute: AdminOrganizationIDRouteWithChildren,
  AdminCollectorsRoute: AdminCollectorsRoute,
  AdminKeysRoute: AdminKeysRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminWalletsRoute: AdminWalletsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CallbackProviderIndexRoute: CallbackProviderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
