/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminWalletsRouteImport } from './routes/admin/wallets'
import { Route as AdminOrganizationIDRouteImport } from './routes/admin/$organizationID'
import { Route as CallbackProviderIndexRouteImport } from './routes/callback/$provider/index'
import { Route as AdminOrganizationIDIndexRouteImport } from './routes/admin/$organizationID/index'
import { Route as AdminOrganizationIDMembersRouteImport } from './routes/admin/$organizationID/members'
import { Route as AdminTempNameIndexRouteImport } from './routes/admin/temp/$name/index'
import { Route as AdminTempNameWebhooksRouteImport } from './routes/admin/temp/$name/webhooks'
import { Route as AdminTempNameKeysRouteImport } from './routes/admin/temp/$name/keys'
import { Route as AdminTempNameProvidersIndexRouteImport } from './routes/admin/temp/$name/providers/index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationIDRoute = AdminOrganizationIDRouteImport.update({
  id: '/$organizationID',
  path: '/$organizationID',
  getParentRoute: () => AdminRoute,
} as any)
const CallbackProviderIndexRoute = CallbackProviderIndexRouteImport.update({
  id: '/callback/$provider/',
  path: '/callback/$provider/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationIDIndexRoute =
  AdminOrganizationIDIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminOrganizationIDRoute,
  } as any)
const AdminOrganizationIDMembersRoute =
  AdminOrganizationIDMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AdminOrganizationIDRoute,
  } as any)
const AdminTempNameIndexRoute = AdminTempNameIndexRouteImport.update({
  id: '/temp/$name/',
  path: '/temp/$name/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTempNameWebhooksRoute = AdminTempNameWebhooksRouteImport.update({
  id: '/temp/$name/webhooks',
  path: '/temp/$name/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTempNameKeysRoute = AdminTempNameKeysRouteImport.update({
  id: '/temp/$name/keys',
  path: '/temp/$name/keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTempNameProvidersIndexRoute =
  AdminTempNameProvidersIndexRouteImport.update({
    id: '/temp/$name/providers/',
    path: '/temp/$name/providers/',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/$organizationID': typeof AdminOrganizationIDRouteWithChildren
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$organizationID/members': typeof AdminOrganizationIDMembersRoute
  '/admin/$organizationID/': typeof AdminOrganizationIDIndexRoute
  '/callback/$provider/': typeof CallbackProviderIndexRoute
  '/admin/temp/$name/keys': typeof AdminTempNameKeysRoute
  '/admin/temp/$name/webhooks': typeof AdminTempNameWebhooksRoute
  '/admin/temp/$name/': typeof AdminTempNameIndexRoute
  '/admin/temp/$name/providers/': typeof AdminTempNameProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/$organizationID/members': typeof AdminOrganizationIDMembersRoute
  '/admin/$organizationID': typeof AdminOrganizationIDIndexRoute
  '/callback/$provider': typeof CallbackProviderIndexRoute
  '/admin/temp/$name/keys': typeof AdminTempNameKeysRoute
  '/admin/temp/$name/webhooks': typeof AdminTempNameWebhooksRoute
  '/admin/temp/$name': typeof AdminTempNameIndexRoute
  '/admin/temp/$name/providers': typeof AdminTempNameProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/$organizationID': typeof AdminOrganizationIDRouteWithChildren
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$organizationID/members': typeof AdminOrganizationIDMembersRoute
  '/admin/$organizationID/': typeof AdminOrganizationIDIndexRoute
  '/callback/$provider/': typeof CallbackProviderIndexRoute
  '/admin/temp/$name/keys': typeof AdminTempNameKeysRoute
  '/admin/temp/$name/webhooks': typeof AdminTempNameWebhooksRoute
  '/admin/temp/$name/': typeof AdminTempNameIndexRoute
  '/admin/temp/$name/providers/': typeof AdminTempNameProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/$organizationID'
    | '/admin/wallets'
    | '/admin/'
    | '/admin/$organizationID/members'
    | '/admin/$organizationID/'
    | '/callback/$provider/'
    | '/admin/temp/$name/keys'
    | '/admin/temp/$name/webhooks'
    | '/admin/temp/$name/'
    | '/admin/temp/$name/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/wallets'
    | '/admin'
    | '/admin/$organizationID/members'
    | '/admin/$organizationID'
    | '/callback/$provider'
    | '/admin/temp/$name/keys'
    | '/admin/temp/$name/webhooks'
    | '/admin/temp/$name'
    | '/admin/temp/$name/providers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/$organizationID'
    | '/admin/wallets'
    | '/admin/'
    | '/admin/$organizationID/members'
    | '/admin/$organizationID/'
    | '/callback/$provider/'
    | '/admin/temp/$name/keys'
    | '/admin/temp/$name/webhooks'
    | '/admin/temp/$name/'
    | '/admin/temp/$name/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CallbackProviderIndexRoute: typeof CallbackProviderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$organizationID': {
      id: '/admin/$organizationID'
      path: '/$organizationID'
      fullPath: '/admin/$organizationID'
      preLoaderRoute: typeof AdminOrganizationIDRouteImport
      parentRoute: typeof AdminRoute
    }
    '/callback/$provider/': {
      id: '/callback/$provider/'
      path: '/callback/$provider'
      fullPath: '/callback/$provider/'
      preLoaderRoute: typeof CallbackProviderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$organizationID/': {
      id: '/admin/$organizationID/'
      path: '/'
      fullPath: '/admin/$organizationID/'
      preLoaderRoute: typeof AdminOrganizationIDIndexRouteImport
      parentRoute: typeof AdminOrganizationIDRoute
    }
    '/admin/$organizationID/members': {
      id: '/admin/$organizationID/members'
      path: '/members'
      fullPath: '/admin/$organizationID/members'
      preLoaderRoute: typeof AdminOrganizationIDMembersRouteImport
      parentRoute: typeof AdminOrganizationIDRoute
    }
    '/admin/temp/$name/': {
      id: '/admin/temp/$name/'
      path: '/temp/$name'
      fullPath: '/admin/temp/$name/'
      preLoaderRoute: typeof AdminTempNameIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/temp/$name/webhooks': {
      id: '/admin/temp/$name/webhooks'
      path: '/temp/$name/webhooks'
      fullPath: '/admin/temp/$name/webhooks'
      preLoaderRoute: typeof AdminTempNameWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/temp/$name/keys': {
      id: '/admin/temp/$name/keys'
      path: '/temp/$name/keys'
      fullPath: '/admin/temp/$name/keys'
      preLoaderRoute: typeof AdminTempNameKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/temp/$name/providers/': {
      id: '/admin/temp/$name/providers/'
      path: '/temp/$name/providers'
      fullPath: '/admin/temp/$name/providers/'
      preLoaderRoute: typeof AdminTempNameProvidersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminOrganizationIDRouteChildren {
  AdminOrganizationIDMembersRoute: typeof AdminOrganizationIDMembersRoute
  AdminOrganizationIDIndexRoute: typeof AdminOrganizationIDIndexRoute
}

const AdminOrganizationIDRouteChildren: AdminOrganizationIDRouteChildren = {
  AdminOrganizationIDMembersRoute: AdminOrganizationIDMembersRoute,
  AdminOrganizationIDIndexRoute: AdminOrganizationIDIndexRoute,
}

const AdminOrganizationIDRouteWithChildren =
  AdminOrganizationIDRoute._addFileChildren(AdminOrganizationIDRouteChildren)

interface AdminRouteChildren {
  AdminOrganizationIDRoute: typeof AdminOrganizationIDRouteWithChildren
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTempNameKeysRoute: typeof AdminTempNameKeysRoute
  AdminTempNameWebhooksRoute: typeof AdminTempNameWebhooksRoute
  AdminTempNameIndexRoute: typeof AdminTempNameIndexRoute
  AdminTempNameProvidersIndexRoute: typeof AdminTempNameProvidersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrganizationIDRoute: AdminOrganizationIDRouteWithChildren,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTempNameKeysRoute: AdminTempNameKeysRoute,
  AdminTempNameWebhooksRoute: AdminTempNameWebhooksRoute,
  AdminTempNameIndexRoute: AdminTempNameIndexRoute,
  AdminTempNameProvidersIndexRoute: AdminTempNameProvidersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CallbackProviderIndexRoute: CallbackProviderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
