/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Univents API
 * Univents is TrieOH's events service: events and editions (runs),
 * ticket types and products, programs (schedules), badge and
 * certification templates, and signature workflows for certificates.
 *
 * ## Authentication
 *
 * All protected endpoints require a bearer JWT issued by IdentityX:
 *
 * | Scheme | Header |
 * |---|---|
 * | Bearer JWT | `Authorization: Bearer <token>` |
 *
 * Public (read-only) endpoints take no auth: event/edition browsing,
 * products, programs, signatures, and certification verification.
 *
 * ### Signature-request tokens
 *
 * The signature fulfillment routes — `POST /signature-requests/fulfill`,
 * `POST /signature-requests/deny`, `POST /signatures/revoke` — are NOT
 * JWT-authenticated. They are authenticated by an HMAC-signed JWT passed
 * as the `token` query parameter (issued when the signature request was
 * created). The token binds the request to a single signature
 * request/edition.
 *
 * ## Response envelope
 *
 * Every JSON response is the `fun.Response` envelope:
 *
 * ```json
 * {
 *   "code": 200,
 *   "message": "",
 *   "data": { "...": "operation payload" },
 *   "error": null,
 *   "pagination": null,
 *   "timestamp": "2026-01-01T12:00:00Z",
 *   "module": "Univents"
 * }
 * ```
 *
 * - Success: `data` carries the payload. Errors: `error` carries an
 *   `AppError` — `{ "code", "message", "fields", "meta" }`.
 * - `pagination` is reserved for paged list endpoints (currently
 *   unused by Univents routes).
 *
 * ## Error codes → HTTP status
 *
 * The `error.code` sentinel maps to the HTTP status:
 *
 * | code | status |
 * |---|---|
 * | `BAD_REQUEST`, `VALIDATION_ERROR` | 400 |
 * | `UNAUTHORIZED` | 401 |
 * | `PAYMENT_REQUIRED` | 402 |
 * | `FORBIDDEN` | 403 |
 * | `NOT_FOUND` | 404 |
 * | `METHOD_NOT_ALLOWED` | 405 |
 * | `CONFLICT` | 409 |
 * | `UNPROCESSABLE_ENTITY` | 422 |
 * | `TOO_MANY_REQUESTS` | 429 |
 * | `INTERNAL_ERROR` | 500 |
 * | `NOT_IMPLEMENTED` | 501 |
 * | `BAD_GATEWAY` | 502 |
 * | `SERVICE_UNAVAILABLE` | 503 |
 *
 * ## Custom methods
 *
 * A few lookups are AIP custom methods (`:verb` suffix, AIP-136): they
 * look up a resource by a natural key instead of its ID:
 *
 * - `GET /events/{event_slug}:by-slug`
 * - `GET /events/{event_slug}:by-slug/editions/{edition_slug}:by-slug`
 * - `GET /editions/{edition_id}/products/{vendor_code}:by-code`
 * - `GET /editions/{edition_id}/variants/{vendor_code}:by-code`
 *
 * These are part of the public interface — the frontend depends on
 * them — and must not be renamed or removed.
 *
 * ## Amounts
 *
 * Prices are integer cents (`price_cents`, `price`) — `int64`, never
 * floats.
 *
 * ## Raw realtime routes (not spec ops)
 *
 * Two live surfaces are **raw routes** — deliberately NOT OpenAPI
 * operations: WebSocket handshakes cannot carry Authorization headers,
 * and streaming responses must bypass the fun/validate envelope machinery
 * (which buffers the body). They are documented here instead.
 *
 * ### `WS /ws?token=...` — per-purchase socket (one-time token)
 *
 * The only live-update channel for a buyer. Opens with the one-time token
 * from `GET /ws/token` (proves prior REST auth for this purchase);
 * missing/already-used/expired tokens are rejected (401). The socket
 * first receives the current state, then live frames until a terminal
 * event closes it:
 *
 * ```json
 * {"type":"purchase.snapshot","payload":{"purchase_id":"…","edition_id":"…","status":"pending","intent_id":"…","intent_status":"pending","total_cents":1234,"items":[],"expires_at":"…"}}
 * {"type":"intent.updated","payload":{"purchase_id":"…","intent_id":"…","status":"succeeded"}}
 * {"type":"purchase.confirmed","payload":{"purchase_id":"…"}}
 * {"type":"purchase.expired","payload":{"purchase_id":"…"}}
 * {"type":"purchase.cancelled","payload":{"purchase_id":"…","status_detail":"insufficient_funds"}}
 * ```
 *
 * The snapshot mirrors the `getCheckout` resume shape (front treats
 * resume == snapshot == checkout uniformly) and carries `intent_status`
 * best-effort when the purchase is pending. A reconnect always uses a
 * fresh token and restores context from the snapshot — no resume polling.
 * The socket closes on any terminal event (confirmed/expired/cancelled)
 * and on the cancelled frame the `status_detail` is the provider's
 * failure vocabulary fetched via `GetIntent` (best-effort).
 *
 * ### `GET /editions/{edition_id}/store/stream` — storefront SSE (public)
 *
 * One stream per edition: on connect it sends `event: snapshot` with a
 * JSON array of every purchasable item's stock position, then relays
 * `event: stock` deltas — `{"id": "…", "item_type": "ticket", "stock": 12}`
 * (`item_type` is one of `ticket | product | program_occurrence`; `stock`
 * is `null` when the item is unlimited). Numbers are always recomputed
 * from the DB by the relay — publishers never send stock values. A `: ping`
 * comment line keeps the stream alive every ~30s.
 *
 * ## Rate limits
 *
 * The harness applies a fixed rate limit of 400 requests/second with a
 * burst of 20, keyed by client IP. Exceeded requests receive
 * `429 TOO_MANY_REQUESTS`.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { BadgePrintItemDesignData } from './badgePrintItemDesignData';
import type { BadgePrintItemOrigin } from './badgePrintItemOrigin';
import type { NullableUUID } from './nullableUUID';
import type { Uuid } from './uuid';

/**
 * The per-emission print payload. Mirrors `models.BadgePrintItem`.
 */
export interface BadgePrintItem {
  emission_id: Uuid;
  user_id: Uuid;
  origin: BadgePrintItemOrigin;
  event_name: string;
  edition_name: string;
  /** @nullable */
  ticket_name?: string | null;
  template_id?: NullableUUID | null;
  /** @nullable */
  template_name?: string | null;
  design_data?: BadgePrintItemDesignData;
  action_url: string;
}
