/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Univents API
 * Univents is TrieOH's events service: events and editions (runs),
 * ticket types and products, programs (schedules), badge and
 * certification templates, and signature workflows for certificates.
 *
 * ## Authentication
 *
 * All protected endpoints require a bearer JWT issued by IdentityX:
 *
 * | Scheme | Header |
 * |---|---|
 * | Bearer JWT | `Authorization: Bearer <token>` |
 *
 * Public (read-only) endpoints take no auth: event/edition browsing,
 * products, programs, signatures, and certification verification.
 *
 * ### Signature-request tokens
 *
 * The signature fulfillment routes — `POST /signature-requests/fulfill`,
 * `POST /signature-requests/deny`, `POST /signatures/revoke` — are NOT
 * JWT-authenticated. They are authenticated by an HMAC-signed JWT passed
 * as the `token` query parameter (issued when the signature request was
 * created). The token binds the request to a single signature
 * request/edition.
 *
 * ## Response envelope
 *
 * Every JSON response is the `fun.Response` envelope:
 *
 * ```json
 * {
 *   "code": 200,
 *   "message": "",
 *   "data": { "...": "operation payload" },
 *   "error": null,
 *   "pagination": null,
 *   "timestamp": "2026-01-01T12:00:00Z",
 *   "module": "Univents"
 * }
 * ```
 *
 * - Success: `data` carries the payload. Errors: `error` carries an
 *   `AppError` — `{ "code", "message", "fields", "meta" }`.
 * - `pagination` is reserved for paged list endpoints (currently
 *   unused by Univents routes).
 *
 * ## Error codes → HTTP status
 *
 * The `error.code` sentinel maps to the HTTP status:
 *
 * | code | status |
 * |---|---|
 * | `BAD_REQUEST`, `VALIDATION_ERROR` | 400 |
 * | `UNAUTHORIZED` | 401 |
 * | `PAYMENT_REQUIRED` | 402 |
 * | `FORBIDDEN` | 403 |
 * | `NOT_FOUND` | 404 |
 * | `METHOD_NOT_ALLOWED` | 405 |
 * | `CONFLICT` | 409 |
 * | `UNPROCESSABLE_ENTITY` | 422 |
 * | `TOO_MANY_REQUESTS` | 429 |
 * | `INTERNAL_ERROR` | 500 |
 * | `NOT_IMPLEMENTED` | 501 |
 * | `BAD_GATEWAY` | 502 |
 * | `SERVICE_UNAVAILABLE` | 503 |
 *
 * ## Custom methods
 *
 * A few lookups are AIP custom methods (`:verb` suffix, AIP-136): they
 * look up a resource by a natural key instead of its ID:
 *
 * - `GET /events/{event_slug}:by-slug`
 * - `GET /events/{event_slug}:by-slug/editions/{edition_slug}:by-slug`
 * - `GET /editions/{edition_id}/products/{vendor_code}:by-code`
 * - `GET /editions/{edition_id}/variants/{vendor_code}:by-code`
 *
 * These are part of the public interface — the frontend depends on
 * them — and must not be renamed or removed.
 *
 * ## Amounts
 *
 * Prices are integer cents (`price_cents`, `price`) — `int64`, never
 * floats.
 *
 * ## Rate limits
 *
 * The harness applies a fixed rate limit of 400 requests/second with a
 * burst of 20, keyed by client IP. Exceeded requests receive
 * `429 TOO_MANY_REQUESTS`.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { EventMemberRole } from './eventMemberRole';
import type { Uuid } from './uuid';

/**
 * Membership of a user in an event. Mirrors `models.EventMember`.
 */
export interface EventMember {
  id: Uuid;
  event_id: Uuid;
  user_id: Uuid;
  role: EventMemberRole;
  created_at: string;
  /** @nullable */
  updated_at?: string | null;
  /** @nullable */
  deleted_at?: string | null;
}
