/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Univents API
 * Univents is TrieOH's events service: events and editions (runs),
 * ticket types and products, programs (schedules), badge and
 * certification templates, and signature workflows for certificates.
 *
 * ## Authentication
 *
 * All protected endpoints require a bearer JWT issued by IdentityX:
 *
 * | Scheme | Header |
 * |---|---|
 * | Bearer JWT | `Authorization: Bearer <token>` |
 *
 * Public (read-only) endpoints take no auth: event/edition browsing,
 * products, programs, signatures, and certification verification.
 *
 * ### Signature-request tokens
 *
 * The signature fulfillment routes — `POST /signature-requests/fulfill`,
 * `POST /signature-requests/deny`, `POST /signatures/revoke` — are NOT
 * JWT-authenticated. They are authenticated by an HMAC-signed JWT passed
 * as the `token` query parameter (issued when the signature request was
 * created). The token binds the request to a single signature
 * request/edition.
 *
 * ## Response envelope
 *
 * Every JSON response is the `fun.Response` envelope:
 *
 * ```json
 * {
 *   "code": 200,
 *   "message": "",
 *   "data": { "...": "operation payload" },
 *   "error": null,
 *   "pagination": null,
 *   "timestamp": "2026-01-01T12:00:00Z",
 *   "module": "Univents"
 * }
 * ```
 *
 * - Success: `data` carries the payload. Errors: `error` carries an
 *   `AppError` — `{ "code", "message", "fields", "meta" }`.
 * - `pagination` is reserved for paged list endpoints (currently
 *   unused by Univents routes).
 *
 * ## Error codes → HTTP status
 *
 * The `error.code` sentinel maps to the HTTP status:
 *
 * | code | status |
 * |---|---|
 * | `BAD_REQUEST`, `VALIDATION_ERROR` | 400 |
 * | `UNAUTHORIZED` | 401 |
 * | `PAYMENT_REQUIRED` | 402 |
 * | `FORBIDDEN` | 403 |
 * | `NOT_FOUND` | 404 |
 * | `METHOD_NOT_ALLOWED` | 405 |
 * | `CONFLICT` | 409 |
 * | `UNPROCESSABLE_ENTITY` | 422 |
 * | `TOO_MANY_REQUESTS` | 429 |
 * | `INTERNAL_ERROR` | 500 |
 * | `NOT_IMPLEMENTED` | 501 |
 * | `BAD_GATEWAY` | 502 |
 * | `SERVICE_UNAVAILABLE` | 503 |
 *
 * ## Custom methods
 *
 * A few lookups are AIP custom methods (`:verb` suffix, AIP-136): they
 * look up a resource by a natural key instead of its ID:
 *
 * - `GET /events/{event_slug}:by-slug`
 * - `GET /events/{event_slug}:by-slug/editions/{edition_slug}:by-slug`
 * - `GET /editions/{edition_id}/products/{vendor_code}:by-code`
 * - `GET /editions/{edition_id}/variants/{vendor_code}:by-code`
 *
 * These are part of the public interface — the frontend depends on
 * them — and must not be renamed or removed.
 *
 * ## Amounts
 *
 * Prices are integer cents (`price_cents`, `price`) — `int64`, never
 * floats.
 *
 * ## Rate limits
 *
 * The harness applies a fixed rate limit of 400 requests/second with a
 * burst of 20, keyed by client IP. Exceeded requests receive
 * `429 TOO_MANY_REQUESTS`.
 *
 * OpenAPI spec version: 0.1.0
 */

export * from './addEventMemberRequest';
export * from './addSignatureRequest';
export * from './badgeEditionEmission';
export * from './badgeEditionEmissionOrigin';
export * from './badgeEditionEmissionStatus';
export * from './badgeEmission';
export * from './badgeEmissionOrigin';
export * from './badgeEmissionStatus';
export * from './badgeOriginGroup';
export * from './badgePrintItem';
export * from './badgePrintItemDesignData';
export * from './badgePrintItemOrigin';
export * from './badgeProfileBadge';
export * from './badgeProfileBadgeDesignData';
export * from './badgeProfileBadgeOrigin';
export * from './badgeProfileGroups';
export * from './badgeTemplate';
export * from './badgeTemplateDesignData';
export * from './badgeTemplateOrigin';
export * from './badRequestResponse';
export * from './cancelSignatureRequestBody';
export * from './certEmissionError';
export * from './certification';
export * from './certificationTemplate';
export * from './certificationTemplateDesignData';
export * from './certificationTemplateKind';
export * from './certificationTemplateProgram';
export * from './certTemplateProgramRequest';
export * from './completeEventPaymentsRequest';
export * from './conflictResponse';
export * from './connectEventPaymentsRequest';
export * from './connectEventPaymentsResult';
export * from './createBadgeTemplateRequest';
export * from './createBadgeTemplateRequestDesignData';
export * from './createCertificationTemplateRequest';
export * from './createCertificationTemplateRequestDesignData';
export * from './createEditionRequest';
export * from './createEventRequest';
export * from './createInitialProductRequest';
export * from './createProductVariantRequest';
export * from './createProgramOccurrenceRequest';
export * from './createProgramRequest';
export * from './createSignatureRequestRequest';
export * from './createTicketTypeRequest';
export * from './denySignatureRequestBody';
export * from './denySignatureRequestParams';
export * from './edition';
export * from './error';
export * from './errorCode';
export * from './errorDebug';
export * from './errorFieldsItem';
export * from './errorMeta';
export * from './errorResponse';
export * from './event';
export * from './eventMember';
export * from './eventMemberRole';
export * from './eventStatus';
export * from './eventStyle';
export * from './forbiddenResponse';
export * from './fulfillSignatureRequestBody';
export * from './fulfillSignatureRequestParams';
export * from './getEditionBadgesPrintParams';
export * from './getHealth200';
export * from './internalServerErrorResponse';
export * from './invalidCertReason';
export * from './notFoundResponse';
export * from './nullableUUID';
export * from './paginationMeta';
export * from './patchEditionRequest';
export * from './patchEventRequest';
export * from './patchProductRequest';
export * from './patchProductVariantRequest';
export * from './patchProgramOccurrenceRequest';
export * from './patchProgramRequest';
export * from './patchTicketTypeRequest';
export * from './product';
export * from './productVariant';
export * from './program';
export * from './programKind';
export * from './programOccurrence';
export * from './receivePayssageWebhookRequest';
export * from './receivePayssageWebhookRequestPayload';
export * from './removeEventMemberBody';
export * from './response';
export * from './responseData';
export * from './revokeSignatureParams';
export * from './signature';
export * from './signatureRequest';
export * from './signatureRequestStatus';
export * from './ticketType';
export * from './unauthorizedResponse';
export * from './updateBadgeTemplateRequest';
export * from './updateBadgeTemplateRequestDesignData';
export * from './updateCertificationTemplateRequest';
export * from './updateCertificationTemplateRequestDesignData';
export * from './uuid';
export * from './verifyCertResponse';
