// Code generated by tygo. DO NOT EDIT.

//////////
// source: intents.go

export interface Intent {
  id: string;
  workspace_id: string;
  amount: number /* int64 */;
  currency: string;
  status: IntentStatus;
  provider: string;
  metadata: any /* json.RawMessage */;
  seller_credential_id?: string;
  created_at: string;
  updated_at: string;
  /**
   * Only one of these will be non-nil, determined by Provider.
   */
  mercadopago_data?: MercadoPagoIntentData;
}
export interface MercadoPagoIntentData {
  order_id: string;
  order_status: string;
  order_status_detail: string;
  transaction_id: string;
  transaction_status: string;
  transaction_status_detail: string;
  payment_method_id: string;
  payment_method_type: string;
  pix_qr_code?: string; // FIXME maybe dont send this or the one below
  pix_qr_code_base64?: string;
}
export type IntentStatus = string;
export const IntentStatusPending: IntentStatus = "pending";
export const IntentStatusSucceeded: IntentStatus = "succeeded";
export const IntentStatusCancelled: IntentStatus = "cancelled";
export const IntentStatusFailed: IntentStatus = "failed";

//////////
// source: marketplaces.go

export interface MarketplaceConfig {
  id: string;
  workspace_id: string;
  credential_id: string;
  provider: string;
  fee_bps: number /* int */; // 500 = 5.00%
  created_at: string;
  updated_at: string;
}

//////////
// source: oauth.go

export interface OAuthState {
  State: string;
  WorkspaceID: string;
  Provider: string;
  Flow: string; // "setup" or "connect"
  IsMarketplace: boolean;
  FeeBps: number /* int */;
  FinalRedirectURL: string;
  CreatedAt: string;
  ExpiresAt: string;
}
export const OAuthFlowSetup = "setup";
export const OAuthFlowConnect = "connect";
export interface ProviderCredential {
  ID: string;
  WorkspaceID: string;
  Provider: string;
  Credentials: ProviderCredentialData;
  CreatedAt: string;
  RevokedAt?: string;
}
export interface ProviderCredentialData {
  access_token: string;
  refresh_token?: string;
  provider_user_id?: number /* int */; // MP seller ID
  public_key?: string;
}

//////////
// source: orgs.go

export interface Organization {
  id: string;
  owner_id: string;
  name: string;
  slug: string;
  created_at: string;
  deleted_at?: string;
}
export type OrganizationRole = string;
export const OrganizationRoleMember: OrganizationRole = "member";
export const OrganizationRoleAdmin: OrganizationRole = "admin";
export const OrganizationRoleOwner: OrganizationRole = "owner";
export interface OrganizationMember {
  organization_id: string;
  member_id: string;
  role: OrganizationRole;
  joined_at: string;
}
export interface CreateOrganizationRequest {
  name: string;
  slug: string;
}
export interface CreateOrganizationInput {
  name: string;
  slug: string;
}
export interface AddOrganizationMemberRequest {
  actor_email: string;
  role: OrganizationRole;
}
export interface AddOrganizationMemberInput {
  actor_email: string;
  role: OrganizationRole;
  organization_id: string;
}
export interface RemoveOrganizationMemberRequest {
  actor_email: string;
}
export interface RemoveOrganizationMemberInput {
  actor_email: string;
  organization_id: string;
}

//////////
// source: wallets.go

export interface Wallet {
  id: string;
  owner_id: string;
  organization_id?: string;
  name: string;
  sandbox: boolean;
  fee_bps: number /* int */;
  created_at: string;
}
export interface CreateWalletRequest {
  name: string;
  organization_id?: string;
}
export interface CreateWalletInput {
  name: string;
  organization_id?: string;
}
export interface SetFeeBPSRequest {
  fee_bps: number /* int */;
  organization_id?: string;
}
export interface SetFeeBPSInput {
  wallet_id: string;
  fee_bps: number /* int */;
  organization_id?: string;
}
export interface SetSandboxRequest {
  sandbox: boolean;
  organization_id?: string;
}
export interface SetSandboxInput {
  wallet_id: string;
  sandbox: boolean;
  organization_id?: string;
}

//////////
// source: webhooks.go

export type DeliveryStatus = string;
export const DeliveryStatusPending: DeliveryStatus = "pending";
export const DeliveryStatusDelivered: DeliveryStatus = "delivered";
export const DeliveryStatusFailed: DeliveryStatus = "failed";
export const EventPaymentSucceeded = "payment.succeeded";
export const EventPaymentFailed = "payment.failed";
export const EventPaymentCancelled = "payment.cancelled";
export interface WebhookPayload {
  event: string;
  intent_id: string;
  workspace_id: string;
  amount: number /* int64 */;
  currency: string;
  provider: string;
  metadata: any /* json.RawMessage */;
  /**
   * Provider Specific Data
   */
  mercado_pago_data?: MercadoPagoIntentData;
}
export interface WebhookDelivery {
  id: string;
  endpoint_id: string;
  intent_id: string;
  event: string;
  payload: any /* json.RawMessage */;
  status: DeliveryStatus;
  attempts: number /* int */;
  last_attempted_at?: string;
  created_at: string;
}
export const MaxDeliverRetries = 5;
export interface DeliverWebhookPayload {
  delivery_id: string;
  endpoint_id: string;
  url: string;
  secret: string;
  payload: string /* []byte */;
}
export interface WebhookEndpoint {
  id: string;
  scope_id: string;
  workspace_id: string;
  url: string;
  created_at: string;
  deleted_at?: string;
}
export interface WebhookEventOriginal {
  ID: string;
  WorkspaceID?: string;
  IntentID?: string;
  Provider: string;
  ExternalID?: string;
  EventType: string;
  Payload: string /* []byte */;
  ReceivedAt: string;
}

//////////
// source: workspaces.go

export interface Workspace {
  id: string;
  scope_id: string;
  user_id: string;
  name: string;
  sandbox: boolean;
  created_at: string;
  updated_at: string;
}
