import { RouterProvider, createRouter } from '@tanstack/solid-router';
import { TanStackQueryProvider, createQueryClient } from '@trieoh/front-core/solid';
import { AuthProvider, type AuthService } from '@trieoh/identityx-sdk-ts-solid';
import './App.css';

// Generated by @tanstack/router-plugin from the files under src/routes —
// TanStack derives full typesafety for <Link>, params, and loader data
// from this tree.
import { routeTree } from './routeTree.gen';

const router = createRouter({
  routeTree,
  context: {
    auth: undefined as { auth: AuthService; isAuthenticated: boolean } | undefined,
  },
  defaultPendingComponent: () => <main>Loading…</main>,
});

// Registers the router's types library-wide, so `to`/`params` on every
// <Link> typecheck against the actual routes.
declare module '@tanstack/solid-router' {
  interface Register {
    router: typeof router;
  }
}

// The app root: the plugin's generated entries render this component,
// wrapped in src/Document.tsx.
export default function App() {
  return (
    <TanStackQueryProvider client={createQueryClient()}>
      <AuthProvider
        baseURL={import.meta.env.VITE_AUTH_API_URL}
        projectId={import.meta.env.VITE_TRIEOH_AUTH_PROJECT_ID}
      >
        <RouterProvider router={router} />
      </AuthProvider>
    </TanStackQueryProvider>
  );
}
