/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CheckoutsPurchaseIdRouteImport } from './routes/checkouts/$purchaseId'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileConfigRouteImport } from './routes/profile/config'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as EventsSlugIndexRouteImport } from './routes/events/$slug/index'
import { Route as EventsSlugCheckoutRouteImport } from './routes/events/$slug/checkout'
import { Route as EventsSlugProgramsRouteImport } from './routes/events/$slug/programs'
import { Route as EventsSlugStoreRouteImport } from './routes/events/$slug/store'
import { Route as ProfileActorIdIndexRouteImport } from './routes/profile/$actorId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutsPurchaseIdRoute = CheckoutsPurchaseIdRouteImport.update({
  id: '/checkouts/$purchaseId',
  path: '/checkouts/$purchaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileConfigRoute = ProfileConfigRouteImport.update({
  id: '/profile/config',
  path: '/profile/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const EventsSlugIndexRoute = EventsSlugIndexRouteImport.update({
  id: '/events/$slug/',
  path: '/events/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugCheckoutRoute = EventsSlugCheckoutRouteImport.update({
  id: '/events/$slug/checkout',
  path: '/events/$slug/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugProgramsRoute = EventsSlugProgramsRouteImport.update({
  id: '/events/$slug/programs',
  path: '/events/$slug/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugStoreRoute = EventsSlugStoreRouteImport.update({
  id: '/events/$slug/store',
  path: '/events/$slug/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileActorIdIndexRoute = ProfileActorIdIndexRouteImport.update({
  id: '/profile/$actorId/',
  path: '/profile/$actorId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/checkouts/$purchaseId': typeof CheckoutsPurchaseIdRoute
  '/profile/config': typeof ProfileConfigRoute
  '/profile/edit': typeof ProfileEditRoute
  '/events/': typeof EventsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/events/$slug/checkout': typeof EventsSlugCheckoutRoute
  '/events/$slug/programs': typeof EventsSlugProgramsRoute
  '/events/$slug/store': typeof EventsSlugStoreRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
  '/profile/$actorId/': typeof ProfileActorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/checkouts/$purchaseId': typeof CheckoutsPurchaseIdRoute
  '/profile/config': typeof ProfileConfigRoute
  '/profile/edit': typeof ProfileEditRoute
  '/events': typeof EventsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/events/$slug/checkout': typeof EventsSlugCheckoutRoute
  '/events/$slug/programs': typeof EventsSlugProgramsRoute
  '/events/$slug/store': typeof EventsSlugStoreRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/events/$slug': typeof EventsSlugIndexRoute
  '/profile/$actorId': typeof ProfileActorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/checkouts/$purchaseId': typeof CheckoutsPurchaseIdRoute
  '/profile/config': typeof ProfileConfigRoute
  '/profile/edit': typeof ProfileEditRoute
  '/events/': typeof EventsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/events/$slug/checkout': typeof EventsSlugCheckoutRoute
  '/events/$slug/programs': typeof EventsSlugProgramsRoute
  '/events/$slug/store': typeof EventsSlugStoreRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
  '/profile/$actorId/': typeof ProfileActorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/checkouts/$purchaseId'
    | '/profile/config'
    | '/profile/edit'
    | '/events/'
    | '/profile/'
    | '/events/$slug/checkout'
    | '/events/$slug/programs'
    | '/events/$slug/store'
    | '/admin/events/'
    | '/events/$slug/'
    | '/profile/$actorId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/checkouts/$purchaseId'
    | '/profile/config'
    | '/profile/edit'
    | '/events'
    | '/profile'
    | '/events/$slug/checkout'
    | '/events/$slug/programs'
    | '/events/$slug/store'
    | '/admin/events'
    | '/events/$slug'
    | '/profile/$actorId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/checkouts/$purchaseId'
    | '/profile/config'
    | '/profile/edit'
    | '/events/'
    | '/profile/'
    | '/events/$slug/checkout'
    | '/events/$slug/programs'
    | '/events/$slug/store'
    | '/admin/events/'
    | '/events/$slug/'
    | '/profile/$actorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  CheckoutsPurchaseIdRoute: typeof CheckoutsPurchaseIdRoute
  ProfileConfigRoute: typeof ProfileConfigRoute
  ProfileEditRoute: typeof ProfileEditRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  EventsSlugCheckoutRoute: typeof EventsSlugCheckoutRoute
  EventsSlugProgramsRoute: typeof EventsSlugProgramsRoute
  EventsSlugStoreRoute: typeof EventsSlugStoreRoute
  EventsSlugIndexRoute: typeof EventsSlugIndexRoute
  ProfileActorIdIndexRoute: typeof ProfileActorIdIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkouts/$purchaseId': {
      id: '/checkouts/$purchaseId'
      path: '/checkouts/$purchaseId'
      fullPath: '/checkouts/$purchaseId'
      preLoaderRoute: typeof CheckoutsPurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/config': {
      id: '/profile/config'
      path: '/profile/config'
      fullPath: '/profile/config'
      preLoaderRoute: typeof ProfileConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/$slug/': {
      id: '/events/$slug/'
      path: '/events/$slug'
      fullPath: '/events/$slug/'
      preLoaderRoute: typeof EventsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/checkout': {
      id: '/events/$slug/checkout'
      path: '/events/$slug/checkout'
      fullPath: '/events/$slug/checkout'
      preLoaderRoute: typeof EventsSlugCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/programs': {
      id: '/events/$slug/programs'
      path: '/events/$slug/programs'
      fullPath: '/events/$slug/programs'
      preLoaderRoute: typeof EventsSlugProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/store': {
      id: '/events/$slug/store'
      path: '/events/$slug/store'
      fullPath: '/events/$slug/store'
      preLoaderRoute: typeof EventsSlugStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$actorId/': {
      id: '/profile/$actorId/'
      path: '/profile/$actorId'
      fullPath: '/profile/$actorId/'
      preLoaderRoute: typeof ProfileActorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsIndexRoute: AdminEventsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  CheckoutsPurchaseIdRoute: CheckoutsPurchaseIdRoute,
  ProfileConfigRoute: ProfileConfigRoute,
  ProfileEditRoute: ProfileEditRoute,
  EventsIndexRoute: EventsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  EventsSlugCheckoutRoute: EventsSlugCheckoutRoute,
  EventsSlugProgramsRoute: EventsSlugProgramsRoute,
  EventsSlugStoreRoute: EventsSlugStoreRoute,
  EventsSlugIndexRoute: EventsSlugIndexRoute,
  ProfileActorIdIndexRoute: ProfileActorIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
