/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsSlugIndexRouteImport } from './routes/events/$slug/index'
import { Route as EventsSlugProgramsRouteImport } from './routes/events/$slug/programs'
import { Route as EventsSlugStoreRouteImport } from './routes/events/$slug/store'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugIndexRoute = EventsSlugIndexRouteImport.update({
  id: '/events/$slug/',
  path: '/events/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugProgramsRoute = EventsSlugProgramsRouteImport.update({
  id: '/events/$slug/programs',
  path: '/events/$slug/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugStoreRoute = EventsSlugStoreRouteImport.update({
  id: '/events/$slug/store',
  path: '/events/$slug/store',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/events/': typeof EventsIndexRoute
  '/events/$slug/programs': typeof EventsSlugProgramsRoute
  '/events/$slug/store': typeof EventsSlugStoreRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/events': typeof EventsIndexRoute
  '/events/$slug/programs': typeof EventsSlugProgramsRoute
  '/events/$slug/store': typeof EventsSlugStoreRoute
  '/events/$slug': typeof EventsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/events/': typeof EventsIndexRoute
  '/events/$slug/programs': typeof EventsSlugProgramsRoute
  '/events/$slug/store': typeof EventsSlugStoreRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/events/'
    | '/events/$slug/programs'
    | '/events/$slug/store'
    | '/events/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/events'
    | '/events/$slug/programs'
    | '/events/$slug/store'
    | '/events/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/events/'
    | '/events/$slug/programs'
    | '/events/$slug/store'
    | '/events/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  EventsIndexRoute: typeof EventsIndexRoute
  EventsSlugProgramsRoute: typeof EventsSlugProgramsRoute
  EventsSlugStoreRoute: typeof EventsSlugStoreRoute
  EventsSlugIndexRoute: typeof EventsSlugIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/': {
      id: '/events/$slug/'
      path: '/events/$slug'
      fullPath: '/events/$slug/'
      preLoaderRoute: typeof EventsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/programs': {
      id: '/events/$slug/programs'
      path: '/events/$slug/programs'
      fullPath: '/events/$slug/programs'
      preLoaderRoute: typeof EventsSlugProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/store': {
      id: '/events/$slug/store'
      path: '/events/$slug/store'
      fullPath: '/events/$slug/store'
      preLoaderRoute: typeof EventsSlugStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  EventsIndexRoute: EventsIndexRoute,
  EventsSlugProgramsRoute: EventsSlugProgramsRoute,
  EventsSlugStoreRoute: EventsSlugStoreRoute,
  EventsSlugIndexRoute: EventsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
